### ISSUE TITLE
Error with getApplication

### ISSUE THREAD

**Issue by Redstonneur1256** [DV8FromTheWorld/JDA#1006]
When getApplications() is completeted on JDAClient, restaction return a parse error for avatar
![Capture1](https://user-images.githubusercontent.com/29004178/57802799-0ddda380-7757-11e9-9f59-d8f7cfff218a.PNG)

**Comment by MinnDevelopment** [comment]
JDAClient is deprecated and has been removed in v4. This will not be fixed.
