### ISSUE TITLE
java.lang.NoClassDefFoundError: net/dv8tion/jda/JDABuilder

### ISSUE THREAD

**Issue by jb42300** [DV8FromTheWorld/JDA#101]
I have the jar implemented in my project... But why would it say this? `java.lang.NoClassDefFoundError: net/dv8tion/jda/JDABuilder
`

**Comment by DV8FromTheWorld** [comment]
Caused by JDA (and most likely its dependencies) not being present in the built jar. Try using something like Maven's Shade plugin or Gradle's ShadowJar plugin.
