### ISSUE TITLE
Add voice kick support

### ISSUE THREAD

**Issue by Simon-official** [DV8FromTheWorld/JDA#1039]
### General Troubleshooting
- [x]  I have checked for similar issues.
- [x]   I have updated to the latest JDA version.
- [x]   I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [ ]   Bug Report
- [x]   Feature Request

### Description
Disconnect a user from a voice channel, without moving/kicking him. 
[Modify Guild Member](https://discordapp.com/developers/docs/resources/guild#modify-guild-member)

**Comment by Andre601** [comment]
JDA 4 already has the option to kick a user from VC by providing `null` as channel.

**Comment by MinnDevelopment** [comment]
This is already available in JDA v4 with [`guild.kickVoiceMember(member).queue()`](https://ci.dv8tion.net/job/JDA4-Beta/javadoc/net/dv8tion/jda/api/entities/Guild.html#kickVoiceMember(net.dv8tion.jda.api.entities.Member))
