### ISSUE TITLE
Why does JDA contain JNA?

### ISSUE THREAD

**Issue by stefan-reich** [DV8FromTheWorld/JDA#1049]
Hi,

I think the JNA that the JDA fat jar bundles (older than JNA 5.0, right?) is causing problems in my setup.

Why is JNA contained in JDA at all? Can I just remove it?

Thanks

**Comment by MCOfficer** [comment]
As far as i know, it's only there for opus-java. 

You can try the v4 Beta, which uses a slightly newer version, or you can use the no-opus jar. alternatively, you might want to use a build tool such as maven or gradle and get JDA directly from the repositories.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Comment by stefan-reich** [comment]
Well, isn't it good to have this here as a FAQ? In Discord, you'd have to ask again and again. Solution (noopus) works fine, thanks.

**Comment by MinnDevelopment** [comment]
It is in the readme which you should look at first anyway.
