### ISSUE TITLE
Role management not working

### ISSUE THREAD

**Issue by YamiZee** [DV8FromTheWorld/JDA#106]
Roles can be created, but they cannot be edited. Nothing happens when attempting to do so.

**Comment by jagrosh** [comment]
Are you calling .update() ?

**Comment by MinnDevelopment** [comment]
^ We need more information on what exactly is not working in this case. Be sure to check the documentation for the methods you are trying to use.

**Comment by DV8FromTheWorld** [comment]
Yep. Gonna chalk this up to you most likely not called `.update()`

**Comment by YamiZee** [comment]
I wasn't even aware of that, thanks for noticing. One thing though, I had done multiple changes to the role and only the first (change name) was applied when i ran the method. This was fixed by running the method after every single change. That seems odd to me but maybe that was intended.

**Comment by DV8FromTheWorld** [comment]
No. That is not intended. You make all the changes to a role that you want, and after you are done, call `.update()`. Same way as when using the client you modify settings before either selecting `cancel` or `okay`

**Comment by YamiZee** [comment]
Alright, ive got it sorted out. No issues here
