### ISSUE TITLE
JDA#awaitReady unexpected behaviour 

### ISSUE THREAD

**Issue by Shea4** [DV8FromTheWorld/JDA#1064]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the 4.BETA.0_19.
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

When using JDA#awaitReady the thread doesn't seem to be blocked or at least not for all shards, causing an IllegalStateException to occur on my print due to the shards not being ready when trying to get the available guilds. My code for reference: https://github.com/sx4-discord-bot/Sx4/blob/master/Sx4/src/main/java/com/sx4/core/Sx4Bot.java#L262

### Expected Behavior

The thread to be blocked until all shards are ready.

### Code Example or Reproduction Steps

Use a new instance of DefaultShardManager, loop through all the shards and use JDA#awaitReady to block until each shard is ready.

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment]
The `getShards()` only returns the currently started shards which might not be all of them yet. After building the shard manager lazily starts the shards one after another and puts them in the shard cache. I recommend counting `ReadyEvent`s instead.

**Comment by Shea4** [comment]
Ah my bad, this worked for me on v3 and didn't see any change logs for it or I may have missed it.

**Comment by MinnDevelopment** [comment]
This is a race-condition so the JDA version doesn't matter.
