### ISSUE TITLE
Releasing WebSocketClient.decompressBuffer

### ISSUE THREAD

**Issue by stefan-reich** [DV8FromTheWorld/JDA#1066]
Is it possible to release or shrink the decompressBuffer in WebSocketClient? It takes ~8 MB in my process.

[For background: [The variable decompressBuffer](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java) is a SoftReference. SoftReferences are not a very good idea in general... it appears they're just not cleared at all if your application has enough memory at its disposal (which it should anyway).]

Many greetings

**Comment by MinnDevelopment** [comment]
SoftReference is the right choice for a cached buffer. This is intended behavior and will not be changed.

**Comment by stefan-reich** [comment]
I'm just asking if there is a way to programmatically clear it when the bot is idle. Would it break anything? Probably not, as a SoftReference is something that is meant to be cleared at unforeseen times. So I could just hack it in there... thanks.

**Comment by MinnDevelopment** [comment]
The bot is never idle, it constantly receives new events from discord which need to be decompressed.
