### ISSUE TITLE
voice channel quality (Bitrate)

### ISSUE THREAD

**Issue by loucaslt** [DV8FromTheWorld/JDA#1069]
Hello.
I made a TempsChannels bot and...
since the last update from Discord with the Nitro Boosting, we can have server with voice quality up to 384 kbts. But, when i create copy from a voice channel with a voice quality with 384 kbts, i have an exception. I can only set the bitrate up to 128000.

I think this is an error. I'm using the lasted version from the JDA v4. (0_32)

**Comment by MinnDevelopment** [comment]
Please open a new issue and use the bug report template this time. You didn't provide any useful information here such as code or exceptions. We have these templates for a reason.
