### ISSUE TITLE
I can't add a role to a new member

### ISSUE THREAD

**Issue by Corazun** [DV8FromTheWorld/JDA#1089]
Hello, I recently started to use JDA and I watched some tutorials but they seems outdated, I found into one how to add a role to a new member, here's the code :
Main.java : 
```JAVA
public static void main(String[] args) throws LoginException {
		
		jda = new JDABuilder(AccountType.BOT).setToken("XXX").build();
		jda.getPresence().setActivity(Activity.watching("Help players"));
		
		jda.addEventListener(new Listeners());
			
	}
```
Listeners.java : 
```JAVA
public void onPlayerJoin(GuildMemberJoinEvent event) {
			
		event.getGuild().addRoleToMember(event.getMember(), (Role) event.getGuild().getRolesByName("Joueur", true)).complete();
		
	}
```

**Comment by caneleex** [comment]
This is not the place to get a support. Join JDA's Discord guild to receive asked help.

**Comment by Andre601** [comment]
`getRolesByName(String name, boolean gnoreCase)` returns a list and not a single role like `addRoleToMember` requires.

Also `onPlayerJoin` is not a valid name. It is always in the format `onX(XEvent event)`

Check the wiki and javadocs please.
