### ISSUE TITLE
GuildController?

### ISSUE THREAD

**Issue by Redemption2033** [DV8FromTheWorld/JDA#1090]
The GuildController class doesn't exist anymore? What do I use instead of it to create a role or give a user a role? I have been Googling around like crazy and everything comes back to GuildController but it simply does not exist in my jar.

**Comment by MCOfficer** [comment]
>  I have been Googling around like crazy

search [the docs](https://ci.dv8tion.net/job/JDA/javadoc/) instead.

**Comment by Andre601** [comment]
I would read things like the release page on GitHub or like the wiki.

**Comment by Kian738** [comment]
what can i use instead of this: 			
`GuildController Controller = vc.getGuild().getController();`

**Comment by Andre601** [comment]
Use methods directly through Guild
