### ISSUE TITLE
[Question] Where is "net.dv8tion.jda.webhook" package in 4.0?

### ISSUE THREAD

**Issue by PanSzelescik** [DV8FromTheWorld/JDA#1097]
This is question, not bug

**Comment by duncte123** [comment]
They can be found over here now https://github.com/MinnDevelopment/discord-webhooks
In the future please ask your questions in the JDA discord (https://discord.gg/0hMr4ce0tIl3SLv5) as the issue tracker is reserved for feature requests and bug.

**Comment by PanSzelescik** [comment]
Okay thanks, and sorry
