### ISSUE TITLE
Emoji errors

### ISSUE THREAD

**Issue by djpgamer7** [DV8FromTheWorld/JDA#1099]
#Bug Report

I am trying to create a verification bot using reactions but every emoji I use it says emoji not found and I whenever I try to print the emoji name to the console when I react it just says null.

### Expected Behavior

That the emoji is recognized using my handler.

### Code Example or Reproduction Steps

N/A

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
