### ISSUE TITLE
ClassNotFound: org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by TheDutchMC04** [DV8FromTheWorld/JDA#1102]
## General Troubleshooting  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
If you have a reproducible behavior, please provide some details for us.
After compiling, and loading the mod in this case up, it will throw errors, specifically ClassNotFound org.slf4j.LoggerFactory, class is present
### Expected Behavior
I expected it to run just fine

### Code Example or Reproduction Steps
How to reproduce 
- Download Forge MDK
- extract MDK, gradlew setupDecompWorkspace, gradlew eclipse
- open the project in Eclipse, add the gradle lines needed for JDA and shadowJar
- gradlew shadowJar
- Install a Forge server, copy the mod from <project>/build/libs to server/mods
- launch server
### Exception or Error
https://pastebin.com/i57QpjpV

**Comment by MinnDevelopment** [comment]
This sounds more like an issue with the modloader/runtime than it is with JDA. We don't do anything with class loading.

**Comment by TheDutchMC04** [comment]
I figured it out, relocating the packages did the trick
