### ISSUE TITLE
Catching RestAction return fail: [ErrorResponseException] 10014

### ISSUE THREAD

**Issue by AyUniz** [DV8FromTheWorld/JDA#1107]
Hello ! 

I have an error while trying to do a reaction on a embed using 

>                     message.getChannel().sendMessage(embed.build()).queue(msgE1 -> {
>                         msgE1.addReaction(":one").queue();
>                         msgE1.addReaction(":two:").queue();
>                     });

But i have this: 

> [ForkJoinPool.commonPool-worker-3] ERROR RestAction - RestAction queue returned failure: [ErrorResponseException] 10014: Unknown Emoji
> net.dv8tion.jda.api.exceptions.ContextException
> 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:52)
> 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:62)
> 	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:168)
> 	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:303)
> 	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:272)
> 	at fr.ayuniz.botca.commands.SondageCommand.lambda$execute$7(SondageCommand.java:129)
> 	at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:83)
> 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Well, i understand that it's because of my emoji. But why ?
I tried everything...

**Comment by Andre601** [comment]
Use the unicode emoji instead of the name.
So instead of `:one:` (You have a typo there btw) you use `\u20E3\u0031` and instead of `:two:` you use `\u20E3\u0032`

Also, the issue tracker is reserved for bug reports and feature requests and yours is none of those.
For support, join the [JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp)

**Comment by MinnDevelopment** [comment]
You have to use unicode emoji for reactions, this is outlined in the documentation including an example.

**Comment by AyUniz** [comment]
how can you get these unicode please ?
