### ISSUE TITLE
Trivia fails to start

### ISSUE THREAD

**Issue by moomoomoo309** [DV8FromTheWorld/JDA#1109]
- [ X ] I have checked for similar issues.
- [ X ] I have updated to the [latest JDA version][download].
- [ X ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

When starting a trivia game several days after the lobby was created, it errors rather than starting the game.

### Expected Behavior

The game should start normally.

### Code Example or Reproduction Steps

1. Start a trivia game.
2. Let KekBot accumulate a bunch of garbage so the guild cache's UpstreamReference becomes invalid.
3. Try to start a game.

The error is very clear what's happening in the JDA side, but since the Game class holds onto the guild reference only, it can't recreate the guild from its id. It should probably check if the reference exists, and if it doesn't, it should recreate it from the id and replace the reference. JDA doesn't really make it clear that TextChannels, Guilds, etc. are ephemeral and are held only by WeakReferences. It's an implementation detail you'd never notice, since it's not documented. This also might manifest as a bug in JDA or a feature request for it, since it should probably do that on its own if the stuff in the cache expires but the object is still needed. You could also force it to hold onto the reference by getting the channel and setting it as a member of the Game object, since that would hold a strong reference to it.

### Exception or Error

[traceback.txt](https://github.com/DV8FromTheWorld/JDA/files/3672583/traceback.txt)

**Comment by MinnDevelopment** [comment]
This is not the place for bot support.

> JDA doesn't really make it clear that TextChannels, Guilds, etc. are ephemeral and are held only by WeakReferences

This is outlined in detail in our README: https://github.com/DV8FromTheWorld/JDA#entity-lifetimes

**Comment by moomoomoo309** [comment]
I'm an idiot and I put this bug report on the wrong repo, so sorry!
