### ISSUE TITLE
VoiceChannel#getUsers() is returning users that are not connected and duplicate values

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#112]
I am trying to get my bot to stop playing when the bot has left the voice channel, but it appears like `VoiceChannel#getUsers()` is returning a wrong list of users in a voice channel.
![image](https://cloud.githubusercontent.com/assets/2582617/17848454/f1d30528-6853-11e6-95f7-298f24701d52.png)
This is the result of me and the bot joining and leaving the voice channel a few times. 
I am runing JDA `2.2.1_355`.

**Comment by MinnDevelopment** [comment]
I will investigate this issue asap

**Comment by DV8FromTheWorld** [comment]
@MinnDevelopment Any news on this one?

**Comment by MinnDevelopment** [comment]
We need more info on how to reproduce this bug.

**Comment by DV8FromTheWorld** [comment]
As I stated in #126 I think this is now fixed as of the latest version of 3.x. If someone could confirm this, that'd be great.

**Comment by MinnDevelopment** [comment]
This error seems to be resolved.
