### ISSUE TITLE
commons-collections4 should be api dependency

### ISSUE THREAD

**Issue by Vampire** [DV8FromTheWorld/JDA#1120]
In your build script you define `implementation("org.apache.commons:commons-collections4:4.1")`.
But `commons-collections4` is used in your API (e. g. as return type of several methods in `Message`).
Due to that it should instead be declared as `api("org.apache.commons:commons-collections4:4.1")`.

This is not only a philosophical change, this is how `api` and `implementation` are meant to be used.
And for me it also has a practical impact. (That I of course can work-around easily by including the lib on my compile classpath manually, but I shouldn't need to)

Due to it being defined as `implementation` dependency it lands as `runtime`-scoped dependency in the published POM and thus is not part of the compile classpath of Gradle 5+ consumers.

Now I have a project that is a consumer and have a Spock test that mocks a method call of `Message`.
This causes the test compilation to fail as the Spock Groovy AST transformation tries to get the methods of `Message` and fails with a `NoClassDefFoundError` as `Bag` is not on the compile classpath.

**Comment by MinnDevelopment** [comment]
You're right, I forgot to change it to api when I added the bag methods. PRs welcome.

**Comment by Andre601** [comment]
So just change a dependency to api?
