### ISSUE TITLE
event.getMember().getVoiceState() --- it return null

### ISSUE THREAD

**Issue by HearthunterPro** [DV8FromTheWorld/JDA#1127]
I cant get VoiceState ,it return null

https://i.imgur.com/yyzeh1H.png

**Comment by duncte123** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to https://discord.gg/0hMr4ce0tIl3SLv5 to receive the needed help.

**Comment by MinnDevelopment** [comment]
From the documentation:
> This will be null when the CacheFlag.VOICE_STATE is disabled manually

You disabled it with the `JDABuilder` through either `setDisabledCacheFlags` or `setEnabledCacheFlags`.
