### ISSUE TITLE
Not a problem, just a question.

### ISSUE THREAD

**Issue by MAKSHOUW** [DV8FromTheWorld/JDA#1136]
Hello !
Is it possible to detect that a channel changes position on the Discord and specifically know the person who changed the position of that channel?

Thanks u so much

**Comment by caneleex** [comment]
Copied from @MinnDevelopment: The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [JDA's guild](discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Comment by kantenkugel** [comment]
@caneleex please refrain from posting that without giving some answer as well...

Alternatively, just let Staff answer and we will post that whenever suitable

@MAKSHOUW detecting a position change is done via event listener. (CategoryChangePositionEvent, XXXChannelChangePositionEvent, XXXChannelUpdateParentEvent)
Finding out who changed it will probably require you to look through audit logs, unless there is a getter on the event (JDA can only provide data in the event that is actually sent from discord)
