### ISSUE TITLE
aarch64-linux-gnu libopus.so inclusion

### ISSUE THREAD

**Issue by wipeDx** [DV8FromTheWorld/JDA#115]
Hey guys,

I have a pine64 which has an arm64 processor.
Whenever I want to use the audiomanager, it crashes since the natives for aarch64-linux-gnu aren't there.

This is easily fixed by recompiling JDA from the source and adding the **libopus.so** (I could provide that, if necessary) into **main/resources/natives/linux-aarch64**

**Comment by DV8FromTheWorld** [comment]
I would love to do this, however, I would need to be the one to do the compilation of the libopus.so, specifically for security's sake. If I could get access to an arm64 environment to build and test with, I'd be happy to do it.

For now however, you can prevent jda from crashing by disabling audio with JDABuilder

**Comment by wipeDx** [comment]
There's no need for that. I found and actually easier way to import the required file.
But yeah, in that case I can understand that you can't include it.
Thanks either way!

You could get access to an arm64 environment with either the pine64 or the (newish) pi3, if you're really interested into buying one.

I guess this can be closed now! Thanks again for the quick response.

**Comment by DV8FromTheWorld** [comment]
Yeah, it is just the source of the compiled file that I'm concerned about. Just for the sake security.

If someone provides me with 10 minutes of ssh access on an arm64 environment I'll be sure to include it.
