### ISSUE TITLE
Unicode from message not got properly for £

### ISSUE THREAD

**Issue by tyhdefu** [DV8FromTheWorld/JDA#1162]
## Bug Report

I try to get the user's message with £ in and it gets � instead of £. Normally printing £ works just fine as well as a face.

### Expected Behavior

Gets £ instead of �, logs to the console £

### Code Example or Reproduction Steps

```java
public static void main(String[] args) throws LoginException {
        System.out.println("Testing £ 😀");
        JDA jdaBot = new JDABuilder(AccountType.BOT).setToken("MYTOKEN").build();
        jdaBot.addEventListener(new Bot());
    }
    private final static Pattern pattern = Pattern.compile("#([A-Z][A-Z0-9][A-Z0-9.][A-Z0-9]?)(?![A-Z0-9])", Pattern.CASE_INSENSITIVE);

    @Override
    public void onMessageReceived(MessageReceivedEvent e) {
        Message MsgObj = e.getMessage();
        String message = MsgObj.getContentStripped();

        System.out.println("Received a message: '" + message + "'");
```

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment]
JDA does not change the encoding of the string. I assume either your console doesn't support this non-ascii character or your java is not using UTF-8.

1. Make sure all your files are encoded in UTF-8
2. Make sure the encoding is set to UTF-8 in the compiler `-encoding utf8`
3. Make sure java runs with UTF-8 encoding `-Dfile.encoding=utf-8`

In any case, I cannot reproduce any issues with character encoding.
