### ISSUE TITLE
Question: Possible to update/set activity once bot has been built?

### ISSUE THREAD

**Issue by brandy** [DV8FromTheWorld/JDA#1172]
I have the below code: 

```java
       JDABuilder builder = new JDABuilder("keeeey");
        builder.setStatus(OnlineStatus.ONLINE);
        builder.setActivity(Activity.playing("1/10"));
        builder.build();
```

Is it possible to update the bot activity once the bot has been built? I'm looking to update the bot activity message every 30ish mins but can't seem to get it to update.

**Comment by Andre601** [comment]
The issue tracker is not suited for asking questions.
Please join the [JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp) for proper support.

And to answer your question: You can change the activity through the JDA instance by using `JDA#getPresence().setActivity(Activity)`.

You could f.e. Listen for the `ReadyEvent` and then do `event.getPresence().setActivity(Activity.playing("game"))`

**Comment by brandy** [comment]
@Andre601 Thanks for the reply, I joined the discord server for future questions. Sorry about that.

Closing issue
