### ISSUE TITLE
[2.2.1_358] Long message doesn't sending 

### ISSUE THREAD

**Issue by gt22** [DV8FromTheWorld/JDA#118]
When I trying to send a bit long message (http://pastebin.com/3J9iD3Dq) it simply doesn't sending, if i remove the logest line it works perfectly, but adding \n in middle doesn't help.
Method call:
`reply(msg, "Комманды:\n" + FormatUtils.foramtHelp());`
(FormatUtils.formateHelp() return the message i gave link before)

Methods:

`public static void reply(Message orig, String reply) {
		reply(orig.getChannel(), orig.getAuthor(), reply);
 }`

`public static void reply(MessageChannel cn, User sender, String text) {
		sendMessage(cn, new MessageBuilder().appendMention(sender).appendString(" " + text).build());
 }`

`public static void sendMessage(MessageChannel cn, Message msg) {
		cn.sendMessage(msg);
}`

**Comment by DV8FromTheWorld** [comment]
Is the message you're attempting to send over 2000 characters in length?

**Comment by DinosParkour** [comment]
Are there any errors in your console?

**Comment by DV8FromTheWorld** [comment]
Oh. What you attached IS the message you tried to send. It looked like a message log to me before I translated it. My bad.

**Comment by gt22** [comment]
Forget to say: I can send this message manually, but the bot can't.

**Comment by gt22** [comment]
@DinosParkour No errors, just nothing.

**Comment by jagrosh** [comment]
One thing to note is that `sendMessage` will attempt to send the message regardless of if the bot is being ratelimited, and if the bot _is_ being limited, it will throw a RateLimitException and it will not attempt to send it again. I'd recommend using `MessageChannel#sendMessageAsync(String, null)` everywhere you currently have `MessageChannel#sendMessage(String)` (for starters)

**Comment by DV8FromTheWorld** [comment]
Are you sure it is actually sending? What I mean is: are you sure the code is actually being executed?

**Comment by DinosParkour** [comment]
I can send the provided text just fine with my bot.

**Comment by gt22** [comment]
@jagrosh Didn't help, also trying to add callback, it doesn't called.
@DV8FromTheWorld Yep, added printnl just before sending ad it works.

**Comment by jagrosh** [comment]
@gt22 If you can share a larger portion of your source code, we might be able to debug the issue; Also, which version of JDA do you currently have? Are you using JDA Player/ JDA Client as well?

**Comment by gt22** [comment]
@jagrosh Full code avavable here: https://github.com/ProjectBronzeMinecraftProject/PBBot
Command in com.projectbronze.pbbot.command.Commands
String gen in com.projectbronze.pbbot.utils.FormatUtils
Methods for sending in com.projectbronze.pbbot.Core

**Comment by DV8FromTheWorld** [comment]
So the removal of
`[USER] музыку [название][* количество]/мзк - Включает музыку, если не указано название включает случайную.
`
fixes the issue?

**Comment by gt22** [comment]
@DV8FromTheWorld Yep, actually removing only part after `-` fix it.

**Comment by DV8FromTheWorld** [comment]
What operating system are you using?

**Comment by gt22** [comment]
@DV8FromTheWorld Windows 10

**Comment by DV8FromTheWorld** [comment]
okay, it is quite likely that the JVM is not using unicode because it defaults to the system's file encoding. Could be causing problems.

Are you running the bot in IDE or from CMD?

**Comment by gt22** [comment]
@DV8FromTheWorld IDE (Eclipse), problems with unicode sounds strange, becouse other messages works fine.

**Comment by gt22** [comment]
Ок, it fixed somehow. I don't know how.

**Comment by DV8FromTheWorld** [comment]
Erm. Alrighty. I suppose I'll close this issue then.
