### ISSUE TITLE
user.getAsMention() sometimes returns a weird result (unclickable UserID instead of clickable username?)

### ISSUE THREAD

**Issue by LivacoNew** [DV8FromTheWorld/JDA#1191]
## Bug Report

Not sure if this is something i'm doing wrong or if it's the library, but when I call user.getAsMention(), most of the time it works fine however sometimes I get this;
![](https://upload.livaco.dev/u/OslcBHwt7j.png)
![](https://upload.livaco.dev/u/Mybn5t1Toi.png)

Seems to be quite rare, however it's still an issue.

### Expected Behavior

Tag displays as a mention 100% of the time.

### Code Example or Reproduction Steps
```
public class JoinListener extends ListenerAdapter {
	@Override 
	public void onGuildMemberJoin(GuildMemberJoinEvent event) {
		// Cut a bunch of stuff for the sake of it not being relevant.
		
		EmbedBuilder eb = new EmbedBuilder();
		eb.setTitle("Welcome!");
		eb.setDescription("Welcome to Livaco's Discord Server, " + event.getUser().getAsMention() + "."); // This line's the one where getAsMention is called.
		eb.setColor(new Color(50, 200, 50));
		eb.setThumbnail(event.getUser().getAvatarUrl());
		if(event.getUser().getAvatarUrl() == null) {
			eb.setThumbnail("https://upload.livaco.dev/u/tMwxea1DQI.png");
		}
		eb.setTimestamp(Instant.now());
		traffic.sendMessage(eb.build()).queue();
		
		// Cut a bunch of stuff for the sake of it not being relevant.
	}
}
```

### Exception or Error
N/A

**Comment by duncte123** [comment]
This is not an issue related to JDA, the issue here is that the user in question is not cached in your discord client and it will display the markdown format instead

**Comment by MinnDevelopment** [comment]
This is not a bug in JDA. Discord as a platform just works like this.

**Comment by LivacoNew** [comment]
Thats stupid ngl, oh well. Thanks anyway :)

**Comment by DV8FromTheWorld** [comment]
You could send that message a few seconds after they join instead of immediately. It should resolve correctly if the client has the time to resolve it.

**Comment by jagrosh** [comment]
Mentions in embeds don't necessarily ever resolve; if you want more-reliable resolving, you need to send the mention in the content of the message.
