### ISSUE TITLE
Java heap space, but enough resources are left

### ISSUE THREAD

**Issue by Seblofs** [DV8FromTheWorld/JDA#1194]
![image](https://user-images.githubusercontent.com/40692731/72666050-c22e7880-3a0e-11ea-94a9-d5061ce13a79.png)
That is comming, when i try to start my bot.
But here you can see the workload, while the bot is running: 
![image](https://user-images.githubusercontent.com/40692731/72666063-decab080-3a0e-11ea-989c-2295fa553022.png)
So what can I do?

**Comment by Andre601** [comment]
How do you start the bot?

And the issue tracker is reserved for bug reports and feature requests.
Questions should be asked in the Discord: https://discord.gg/0hMr4ce0tIk3pSjp

**Comment by Seblofs** [comment]
![image](https://user-images.githubusercontent.com/40692731/72666161-d757d700-3a0f-11ea-804a-9deafe2680c5.png)

**Comment by kantenkugel** [comment]
That command sets the maximum amount of ram the bot can allocate to 1 gig (last argument)
also this is a bad way of starting a jar. you should consider creating runnable jars

Part of the issue could be the messages below tho: "suspicious amounts of cached events"
i would try restarting and if that issue persists all the time, something might be wrong (user account?)
Disabling chunking might fix the issue, while introducing a possibly different one (no longer full cache on ready in case you need that)

**Comment by Seblofs** [comment]
i fixed it thanks
