### ISSUE TITLE
... send help

### ISSUE THREAD

**Issue by that-weird-thing** [DV8FromTheWorld/JDA#1199]
I'm able to download all of the files for this program, but can't run them in any way to make any sort of program or anything, and I've been trying for nearly a month now... I'm new to GitHub and I wanted to create my own discord bot, but I can't get it to work. Please help!

**Comment by DV8FromTheWorld** [comment]
https://github.com/DV8FromTheWorld/JDA/wiki/3%29-Getting-Started
