### ISSUE TITLE
RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user

### ISSUE THREAD

**Issue by Zoon20X** [DV8FromTheWorld/JDA#1202]
when 1 person types a command it is supose to run this code `            devent.getAuthor().openPrivateChannel().complete().sendMessage("Hey! Your VerificationCode has Been Generated!\n" + "Use this command in game: ```/verify " +rc+"```");`

it runs perfectly for me and 1 of my friends but a player on my discord tried to run it and it won't open the pm with her, and the code runs an error in console

https://hastebin.com/ubagulaboz.css
i've tried to look for other similar issues but can't figure out how to fix this, also the lines "bot.java:87" is refering to the code above

**Comment by MinnDevelopment** [comment]
The provided code cannot produce this error. You don't use `queue()` anywhere here.

`50007: Cannot send messages to this user`

This means the user either blocked your bot, left the server before it sent the request, or blocks direct messages for the server.

For further assistance, please join our discord server at https://discord.gg/0hMr4ce0tIl3SLv5
