### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Seblofs** [DV8FromTheWorld/JDA#1205]
When i start the Bot nothing happends. On the DiscordServer no one can help me, so maybe here can someone help me.. i hope so...
my main: 
![image](https://user-images.githubusercontent.com/40692731/74588940-3f92dc00-5001-11ea-86ef-6f903d1d3a7c.png)

![image](https://user-images.githubusercontent.com/40692731/74588943-46b9ea00-5001-11ea-8917-e5c403d905ca.png)
Console: 
![image](https://user-images.githubusercontent.com/40692731/74588951-589b8d00-5001-11ea-8339-84b72d196932.png)

**Comment by MinnDevelopment** [comment]
Can you provide me with:

- The JDA version you use
- Your pom.xml
- Output of `mvn dependency:tree -Dverbose` (with gist)

Please post either a gist or codeblock. Screenshots make this a lot more difficult.

**Comment by kantenkugel** [comment]
Also (what i already suggested in the server): Set the root logger to TRACE to get all messages of init

**Comment by Seblofs** [comment]
I use the newest JDA Version: 4.1.1_101
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>DiscordBot</groupId>
    <artifactId>DiscordBot</artifactId>
    <version>1.0-SNAPSHOT</version>



    <repositories>
        <repository>
            <id>jitpack.io</id>
            <name>JitPack</name>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>jcenter</id>
            <name>JCenter</name>
            <url>https://jcenter.bintray.com</url>
        </repository>
            <repository>
                <id>oss.snapshots</id>
                <name>OSS Sonatype Snapshot Repository</name>
                <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
                <releases>
                    <enabled>false</enabled>
                </releases>
                <snapshots>
                    <enabled>true</enabled>
                </snapshots>
            </repository>



    </repositories>
    <dependencies>

        <dependency>
            <groupId>fr.bmartel</groupId>
            <artifactId>jspeedtest</artifactId>
            <version>LATEST</version>
        </dependency>
        <dependency>
            <groupId>com.moandjiezana.toml</groupId>
            <artifactId>toml4j</artifactId>
            <version>LATEST</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>LATEST</version>
        </dependency>
        <dependency>
            <groupId>com.mashape.unirest</groupId>
            <artifactId>unirest-java</artifactId>
            <version>LATEST</version>
        </dependency>
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>4.1.1_101</version>
        </dependency>
        <dependency>
            <groupId>com.sedmelluq</groupId>
            <artifactId>lavaplayer</artifactId>
            <version>1.3.22</version>
        </dependency>
            <dependency>
                <groupId>org.discordbots</groupId>
                <artifactId>DBL-Java-Library</artifactId>
                <version>2.0.1</version>
            </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.28</version>
        </dependency>
        <dependency>
            <groupId>org.brunocvcunha.jiphy</groupId>
            <artifactId>jiphy</artifactId>
            <version>LATEST</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.8-dmr</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.10</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20190722</version>
        </dependency>
        
    </dependencies>

    <build>
        <plugins>
            <plugin>
                
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>core.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <properties>
        <java.version>1.10</java.version>
        <maven.compiler.source>1.10</maven.compiler.source>
        <maven.compiler.target>1.10</maven.compiler.target>
    </properties>` 

> Output of mvn dependency:tree -Dverbose 
Where can i do this?

**Comment by MinnDevelopment** [comment]
Try updating lavaplayer and jda. I think your version of jackson is outdated.

> Output of mvn dependency:tree -Dverbose
> Where can i do this?

You can run it in your IDE: https://www.jetbrains.com/help/idea/work-with-maven-goals.html

**Comment by Seblofs** [comment]
[Here the output](https://hasteb.in/nicahipo.sql)

**Comment by MinnDevelopment** [comment]
> Try updating lavaplayer and jda. I think your version of jackson is outdated.

Did this resolve the issue?

**Comment by Seblofs** [comment]
> Did this resolve the issue?
Javaplayer and jda has the newest version, or?`

**Comment by MinnDevelopment** [comment]
> Javaplayer and jda has the newest version, or?`

No. JDA is on version `4.1.1_108` and lavaplayer is on version `1.3.34`

**Comment by Seblofs** [comment]
Its working <3

**Comment by Seblofs** [comment]
![image](https://user-images.githubusercontent.com/40692731/74591684-4712af00-501a-11ea-8ee9-300a069285f8.png)
On my vServer says it now this

**Comment by MinnDevelopment** [comment]
Unrelated to this issue. Read the [troubleshooting guide](https://github.com/DV8FromTheWorld/JDA/wiki/19\)-Troubleshooting#noclassdeffounderror-or-classnotfoundexception-on-startup) and join our discord server at https://discord.gg/0hMr4ce0tIl3SLv5 for further help.
