### ISSUE TITLE
After rebooting vServer bot send weird error

### ISSUE THREAD

**Issue by Seblofs** [DV8FromTheWorld/JDA#1208]
`2020-02-27 13:18:57 [JDA MainWS-ReadThread] WARN  net.dv8tion.jda.internal.handle.GuildSetupController  - Accumulating suspicious amounts of cached events during guild setup, something might be wrong. Cached: 8000 Members: 4/86217 Status: CHUNKING GuildId: 264445053596991498 Incomplete: 0/6`

This error came when i tried to start the bot after rebooting my vserver
Edit: on my local pc it works

**Comment by Andre601** [comment]
Please follow the actual issue template.

Also, other devs (including me) encounter this aswell and my thought is, that this is caused by a recent API change from Discord.

Disable the caching/chunking for your bot for now as a workaround.

**Comment by Seblofs** [comment]
My vserver has a bad download atm.
Thanks for helping, i contact the support from my hoster
