### ISSUE TITLE
Memory leak in net.dv8tion.jda.requests.WebSocketClient

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#121]
I discovered some huge spikes in my music bot that causes the program to run out of memory without exiting the process properly.
![image](https://cloud.githubusercontent.com/assets/2582617/18264222/579b273e-740f-11e6-98e9-6264947397e9.png)
I obtained a memory dump from a crash I had while sleeping. Turns out that most of the memory usage comes from net.dv8tion.jda.requests.WebSocketClient. Here's a summary:
![image](https://cloud.githubusercontent.com/assets/2582617/18264293/af861bde-740f-11e6-8dc4-ff519438289d.png)
Here's a report I generated:
[report378760232241.pdf](https://github.com/DV8FromTheWorld/JDA/files/456085/report378760232241.pdf)
I can provide the memory dump if necessary.

Edit: I suspect this has to do with event caching

**Comment by DV8FromTheWorld** [comment]
I believe you are correct about it having to do with event caching, specifically the internal cache in the mWS during init.

**Comment by TheEpTic** [comment]
Can confirm. I remember mentioning this about a month ago but I guess it got lost in the Discord chat.

**Comment by ImAFlyingPancake** [comment]
This leak is very visible when using the Audio API. The more song you play, the more RAM the JVM needs and it grows really fast. (About 1GB RAM per song)

**Comment by DV8FromTheWorld** [comment]
Uh... this leak, which existed in 2.x due to a bug with reconnect, had literally nothing to do with Audio. Additionally, your thought that each song requires an additional 1GB of ram is just not possible. We have multiple bots with tens of thousands of guilds running hundreds of audio connections, simultaneously playing hundreds of songs. They dont requite hundreds of GB of ram.

**Comment by TheEpTic** [comment]
I run a bot with just over 34k guilds. I can agree with DV8 here and say that my bot will sometimes barely hit 4GB of RAM. Although sometimes it will randomly max out the ram, but I don't blame JDA or JDA Player.

**Comment by ImAFlyingPancake** [comment]
Ok I don't know what it's coming from because I followed the example in the documentation for this audio test and the bot was only doing this. Anyway, this is out of the subject. Sorry for the inconvenience.

**Comment by DV8FromTheWorld** [comment]
@Frederikam @TheEpTic I would like an update as to whether or not the same problem has been seen or experienced in JDA 3.

**Comment by TheEpTic** [comment]
So far I'm not seeing it, but I'd wait for @Frederikam's input before marking as resolved.

**Comment by Frederikam** [comment]
I haven't seen this for months.
