### ISSUE TITLE
Get emote by ID doesn't work with lazy loading

### ISSUE THREAD

**Issue by deprilula28** [DV8FromTheWorld/JDA#1238]
### Expected Behavior

I would rather getEmoteById return the emote from that ID

### Code Example or Reproduction Steps

jda.getEmoteById(id)

### Exception or Error

N/A

![Img](https://thats-a.bad-me.me/7LDbDXP.png)
Image: GamesROB is the production bot with pre-lazy loading, GamesROB Dev is running on my machine with lazy loading.

**Comment by deprilula28** [comment]
nvm im stupid

**Comment by DV8FromTheWorld** [comment]
Can you post what you did to fix this issue? (for other people that might encounter it)

**Comment by deprilula28** [comment]
It's retrieveEmoteById(long)

**Comment by DV8FromTheWorld** [comment]
For clarity: 
The reason this didn't work is because the Emote wasn't cached. You need to have the correct CacheFlags and GuildIntents to make sure that these values get cached when they are seen.

Otherwise, you have to use `retrieveEmoteById`
