### ISSUE TITLE
Message.getMentionedMembers() returns diferently when someone pings on mobile.

### ISSUE THREAD

**Issue by LivacoNew** [DV8FromTheWorld/JDA#1242]
## General Troubleshooting

- [ ] I have checked for similar issues.
- [ ] I have updated to the [latest JDA version][download].
- [ ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

For one of my commands the bot checks if the mentions are empty, if they are tell the user to ping a user, and if they aren't gets the first mentioned user as the target. While using the command on the Desktop Client this works fine - while using the command on the Mobile Client the method seems to not pick up the ping, and says that there is no mentions.

Using the command on Desktop:
![Using the command on Desktop.](https://upload.livaco.dev/u/IgtvlWFo2X.png)
Using the command on Mobile:
![Using the command on Mobile.](https://upload.livaco.dev/u/VJi3KIw7kT.png)

### Expected Behavior

Using the command on both clients makes the bot detect them just fine.

### Code Example or Reproduction Steps

Just showing the valid parts of this because A. It's a long file and B. It's a private commission and I don't want to leak code.
```java
Member member;
if(event.getMessage().getMentionedMembers().isEmpty()) {
	channel.sendMessage("Du musst den user pingen (@Name)").queue();
	return;
}
member = event.getMessage().getMentionedMembers().get(0);
```

### Exception or Error

N/A

**Comment by Andre601** [comment]
My guess is, that this is caused by the App (Client) and not the fault of JDA, as it - to my knowledge - checks for any appearance of `<@<userid>>` or `<@!<userid>>` using the pattern `<@!?(\\d+)>`, and compares the IDs with those of Members the bot "knows" (Has in its cache)
So it could be that the mobile app, for whatever reason, sends a different mention type that JDA doesn't know of (yet).
Please run some sort of eval command, to see what the raw message output for both desktop and mobile are.

**Comment by MinnDevelopment** [comment]
I can't reproduce the bug with your reproduction steps on the latest version of JDA **4.1.1_125**.

Desktop:

![image](https://user-images.githubusercontent.com/18090140/77598868-41569600-6f03-11ea-85d7-08d5c92f1039.png)

Mobile (android):

![image](https://user-images.githubusercontent.com/18090140/77598880-4c112b00-6f03-11ea-9fb8-f4c52b835419.png)

**Comment by MinnDevelopment** [comment]
This method only works if the user is actually mentioned. This means the user must be in the guild and (in some situations) also have access to the channel. I don't think this can be a bug in JDA since the behavior is identical no matter what client sends the message.

**Comment by LivacoNew** [comment]
Don't know why but it seems to have fixed itself overnight. Unsure what the cause was but hopefully it won't happen again. Thanks anyway!
