### ISSUE TITLE
Allow to get oldMessage using MessageUpdateEvent

### ISSUE THREAD

**Issue by csskroubledev** [DV8FromTheWorld/JDA#1255]
It will be easier just to use event.getOldMessage() than caching everything to a database.

**Comment by DManstrator** [comment]
JDA has an issue template which should be used for opening issues. To your issue: Discord doesn't provide that info so does JDA.

**Comment by MinnDevelopment** [comment]
Discord doesn't provide this data so we can't either.

**Comment by c0mpiler** [comment]
https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-messageUpdate

https://github.com/discordjs/discord.js/blob/stable/src/client/websocket/handlers/MESSAGE_UPDATE.js#L8

isn't this what the issue is about? Sorry if I am missing something here -
