### ISSUE TITLE
VoiceStatus of users is not correct at startup

### ISSUE THREAD

**Issue by jagrosh** [DV8FromTheWorld/JDA#126]
VoiceStatus appears to only be correct for joins/changes/leaves made after the bot has connected.
Example Scenario:
1. User joins a voice channel
2. Bot starts up
3. User uses a command that requires being in a voice channel
4. According to bot, user is not in the voice channel
5. User moves to a different channel and back
6. User uses same command; success.

Note: Might be related to #112

**Comment by MinnDevelopment** [comment]
This will be addressed in JDA 3.0.

**Comment by DV8FromTheWorld** [comment]
This should be fixed as of the latest build of 3.x. Would really love someone to try reproducing this in 3.x to confirm that it is fix.ed

**Comment by MinnDevelopment** [comment]
This should be fixed in 3.x, if not feel free to open this issue again with new information.
