### ISSUE TITLE
[Question] Get messageId from Message send by bot

### ISSUE THREAD

**Issue by dragonriderworld** [DV8FromTheWorld/JDA#1262]
Hello,
sorry for disturbing, but i found no answer for this question :/

How can I get the messageId from a message my Bot sent by using `TextChannel.sendMessage("Text").queue();`

I don't want to retrieve it from the TextChannel like getLastMessage() or something, couse it's possible that normal users write in that time...is there a way to get the message/messageID directly?

Would be awesome :)

Thnanks for your help^^

**Comment by Andre601** [comment]
Please use one of the issue templates next time, even if none matches your type.

For your question:
You can use the success-consumer of the RestAction, to retrieve the send message object.
https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction#using-queue

**Comment by dragonriderworld** [comment]
Thanks :) 

Will use a template next time^^

Works perfect
