### ISSUE TITLE
onGuildMessageReceived only working with Bot Token

### ISSUE THREAD

**Issue by pelias006** [DV8FromTheWorld/JDA#1264]
```java
@Override
    public void onGuildMessageReceived(@NotNull GuildMessageReceivedEvent event) {
        //Some things here
    }
```
Is only working with Bot Tokens and not with Client Tokens. Is there a fix?

**Comment by DManstrator** [comment]
Please use the Issue Template when opening issues.

Using JDA to automate your own account isn't supported anymore and is against the ToS of Discord.

**Comment by MinnDevelopment** [comment]
JDA no longer supports account type client.
