### ISSUE TITLE
Not sending embed

### ISSUE THREAD

**Issue by adenirlc** [DV8FromTheWorld/JDA#1269]
Hi, i have a problem on send a MessageEmbed!
In the channel text, show `net.dv8tion.jda.api.entities.MessageEmbed@37dd0d69`

Command:
`val embed = getEmbedBase(e.message.author, e.message.member!!)

        embed.apply {
            setTitle("testing embed JDA")
        }

        ChatUtil(e).reply(embed.build())`

ChatUtil:
`fun reply(embed: MessageEmbed, success: Consumer<Message>? = null) {
        reply(build(embed), success)
    }`

Embed Base Function:
`fun getEmbedBase(user: User, member: Member?): EmbedBuilder {
        return EmbedBuilder().apply {
            setThumbnail(user.effectiveAvatarUrl)
            var nickname = user.name

            if (member != null)
                nickname = member.effectiveName

            val ownerEmote = when {
                member?.isOwner == true -> "\uD83D\uDC51"
                else -> ""
            }

            val typeEmote = when {
                user.isBot -> "BOT"
                else -> "NOBOT"
            }

            val statusEmote = when (member?.onlineStatus) {
                OnlineStatus.ONLINE -> "a"
                OnlineStatus.IDLE -> "b"
                OnlineStatus.DO_NOT_DISTURB -> "c"
                else -> "d"
            }

            setTitle("$ownerEmote$typeEmote$statusEmote $nickname", null)
            setColor(Color.BLACK) // Cor do embed (Cor padrão do Discord)

            if (member != null) {
                val highestRole = member.roles.sortedByDescending { it.positionRaw }.firstOrNull()
                if (highestRole != null) {
                    setColor(highestRole.color)
                }
            }
        }
    }`

**Comment by Fabricio20** [comment]
Hey there, seems like you have an issue on your `reply` or your `build` method (not shown here), which is doing a `toString` on the EmbedBuilder instead of `build`ing it.

By the way, for these types of issues I would first ask on our [Discord](https://discord.gg/0hMr4ce0tIk3pSjp) chat.

**Comment by adenirlc** [comment]
OK, thanks .
