### ISSUE TITLE
ConnectionListener only works once per session

### ISSUE THREAD

**Issue by codedcosmos** [DV8FromTheWorld/JDA#1287]
## General Troubleshooting
- [x] I have checked for similar issues.
- [x] I have updated to the [JDA:4.1.1_142](https://github.com/DV8FromTheWorld/JDA).
- [ ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
After creating a simple [ConnectionListener](https://github.com/DV8FromTheWorld/JDA-Audio/blob/master/src/main/java/net/dv8tion/jda/audio/hooks/ConnectionListener.java) class, I am only getting onStatusChange called once. This method should be called at least twice, but typically more if the user speaks more than once.

If the user leaves and rejoins the channel then the method will be called again, but it only happens once for every time the user joins.

### Expected Behavior
When user starts speaking the method onStatusChange should be called once, when they stop it should be called again. 

### Code Example or Reproduction Steps
```
public class AudioReciever implements ConnectionListener {
	@Override
	public void onPing(long ping) {}
	
	@Override
	public void onStatusChange(@Nonnull ConnectionStatus status) {}
	
	@Override
	public void onUserSpeaking(@Nonnull User user, boolean speaking) {
		Log.print("User speaking " + speaking);
	}
}
```

### Code for JDABuilder or DefaultShardManagerBuilder Used
```
JDABuilder builder = JDABuilder.createDefault(token);

builder.setActivity(Activity.listening(".help"));
builder.addEventListeners(commands);
builder.addEventListeners(new EventHandler());
			
// JDA-nas
builder.setAudioSendFactory(new NativeAudioSendFactory());
			
JDA jda = builder.build();
```

### Note
I did make sure to connect the listener, though it would not work at all if this step was skipped.
```
guild.getAudioManager().setConnectionListener(context.getReciever());
```

### Exception or Error
This message only appears once, irregardless if the user continues to speak or stops etc. Also User speaking false never appears.

```
[02:54:22] [JDA AudioWS-ReadThread (guildId: 414261459208372225)] : User speaking true 
```

**Comment by MinnDevelopment** [comment]
Why did you not include your code for `JDABuilder`?

**Comment by MinnDevelopment** [comment]
Discord only sends the speaking update when the flags change from something like VOICE -> SOUNDSHARE. There is no indicator for when a user stops speaking, this is legacy code that discord no longer supports. The client now detects user speaking through the received VOICE packets from the UDP connection.

This is intended behavior.

**Comment by MinnDevelopment** [comment]
In my testing the `onStatusChange` listener works as intended:

```java
public void onStatusChange(ConnectionStatus status) {
  System.out.println(status);
}
```

```
CONNECTING_AWAITING_WEBSOCKET_CONNECT
CONNECTING_AWAITING_AUTHENTICATION
CONNECTING_ATTEMPTING_UDP_DISCOVERY
CONNECTING_AWAITING_READY
CONNECTED
```

**Comment by codedcosmos** [comment]
I thought the JDA builder wasn't applicable, Sorry. I have edited the issue message above to include it.

onStatusChange appears to work as intended for me as well.

> There is no indicator for when a user stops speaking, this is legacy code that discord no longer supports

That is unfortunate as that was exactly what I was hoping to get.

**Comment by DV8FromTheWorld** [comment]
The way to determine that would be to have a timeout when receiving user audio. After > 100ms of not receiving audio from a users, assume they've stopped speaking.

This is, in fact, how the discord client handles it now.

**Comment by codedcosmos** [comment]
Apologies for this late reply, I have tried to implement something similar to what you mention. But the onUserSpeaking() method is only called once. Not once every 100 milliseconds or twice. 

similarly handleCombinedAudio() for AudioReceiveHandler is only called once as well. 

Which method should I be using to see if the user has started speaking at all?
