### ISSUE TITLE
Hit the WebSocket RateLimit!

### ISSUE THREAD

**Issue by Andre601** [DV8FromTheWorld/JDA#1290]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
When building a ShardManager instance using the DefaultShardManagerBuilder and also disabling specific Intents and CacheFlags do I receive these warnings without knowing what the issue is:
```
Hit the WebSocket RateLimit! This can be caused by too many presence or voice status updates (connect/disconnect/mute/deaf). Regular: 0 Voice: 0 Chunking: 503
```
(note that 503 is different depending on the shard)

This starts once the bot connects to the websocket (`Connected to WebSocket!` message) and then spams in regular intervals the console.

## Example Code
Code used to built a ShardManager instance
```java
/*
 * getFileManager() is a getter for a class that loads and handles JSON files.
 * waiter is a EventWaiter (JDA-Utilities) instance.
 * getMessageUtils() is a class for various message-related stuff (in this case getting a random startup message)
 */
DefaultShardManagerBuilder
    .create(
        getFileManager().getString("config", "bot-token"),
        GatewayIntent.GUILD_MEMBERS,
        GatewayIntent.GUILD_MESSAGES,
        GatewayIntent.GUILD_EMOJIS,
        GatewayIntent.GUILD_MESSAGE_REACTIONS
    )
    .disableIntents(
        GatewayIntent.GUILD_VOICE_STATES, 
        GatewayIntent.GUILD_PRESENCES
    )
    .disableCache(
        CacheFlag.ACTIVITY, 
        CacheFlag.VOICE_STATE,
        CacheFlag.CLIENT_STATUS
    )
    .addEventListeners(
        new ReadyListener(this),
        new ConnectionListener(this),
        new GuildListener(this),
        new CommandListener(this, CMD_HANDLER),
        waiter
    )
    .setShardsTotal(-1)
    .setActivity(Activity.of(Activity.ActivityType.DEFAULT, getMessageUtil().getRandomStartupMsg()))
    .setStatus(OnlineStatus.DO_NOT_DISTURB)
    .build();
```

**Comment by MinnDevelopment** [comment]
This is intended behavior. Discord requires to chunk the members for each guild individually. You have to either accept these warnings or disable chunking with `setChunkingFilter(ChunkingFilter.NONE)`.

**Comment by Andre601** [comment]
Would disabling the ChunkingFilter have any major impact on the bot? Like on what methods you can use or the general performance? Or is it neglectable?

**Comment by MinnDevelopment** [comment]
Without chunking, JDA will use lazy loading and start off with a minimal set of members. If the `GUILD_PRESENCES` intent is disabled, we start off with only voice members. With `GUILD_PRESENCES` we start with online members and voice members. Additional members will be loaded once they are active.

There are many ways to load and access members without chunking:

- [retrieveMemberById](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#retrieveMemberById(long))
- [retrieveMembersByPrefix](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#retrieveMembersByPrefix(java.lang.String,int))
- [retrieveMembers](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#retrieveMembers())

**Comment by Andre601** [comment]
Will `Message#getMember()` and similar get methods still work?

**Comment by MinnDevelopment** [comment]
> Will Message#getMember() and similar get methods still work?

Depends on the message origin. In events, yes. When you do `retrieveMessageById` discord currently doesn't provide the member instance, so it will be null.

**Comment by Andre601** [comment]
Thanks for the clarifications.
