### ISSUE TITLE
Please do it as soon as possible!

### ISSUE THREAD

**Issue by Vladimir-Urik** [DV8FromTheWorld/JDA#1299]
**Good morning,**
I would greatly appreciate it if:
- when MessageUpdateEvent gave an old message
- in MessageDeleteEvent it was possible to get the id or name of the person who deleted it

Thank you, I hope you add it soon :)

**Comment by MCOfficer** [comment]
dupes #696 #569

Neither of those is provided by Discord, so it would require a cache to be implemented on JDA's end. I can't speak for the maintainers, but i expect this to be closed. These are things you (or a helper library) is supposed to implement.

PS: For reference, you should split unrelated feature requests into different issues (with descriptive titles for each).

**Comment by Vladimir-Urik** [comment]
I heard it's in the nodejs, etc ... so how can Dyno find out then?
I don't think he would write all the messages to the Database

**Comment by MCOfficer** [comment]
They do, actually. All bots with these features keep a message cache of some sort.

**Comment by MinnDevelopment** [comment]
We can't provide information that doesn't doesn't provide.
