### ISSUE TITLE
GuildMessageReactionRemoveEvent bug

### ISSUE THREAD

**Issue by daviddev16** [DV8FromTheWorld/JDA#1300]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

GuildMessageReactionRemoveEvent is returning "getMember()" as a null object when I tried to get the User name.

### Expected Behavior

bring to my code the object of "getMember().getUser()"

### Code Example or Reproduction Steps

[Code and the thrown exception](https://prnt.sc/sho3b6)

### Code for JDABuilder or DefaultShardManagerBuilder Used

[Code behind the error](https://prnt.sc/sho4h9)

### Exception or Error

[Full Exception Stacktrace](https://prnt.sc/sho4vq)

**Comment by Devoxin** [comment]
This is not a bug.

JDA provides the information it's given by Discord. Because Discord [doesn't provide a member object](https://discord.com/developers/docs/topics/gateway#message-reaction-remove) this information isn't available. Equally, `getMember` is marked nullable so your code should account for this.

**Comment by daviddev16** [comment]
So, how can I get the information about who "unreacted" to the emote?

**Comment by boomboompower** [comment]
> So, how can I get the information about who "unreacted" to the emote?

Make a request to the guild to retrieve a member by the id of the user who removed the emote.

**Comment by daviddev16** [comment]
Ok, I'll try it, thanks by the way!

**Comment by MinnDevelopment** [comment]
Duplicate of #1261 #1275
