### ISSUE TITLE
Json Embed

### ISSUE THREAD

**Issue by Vladimir-Urik** [DV8FromTheWorld/JDA#1304]
Is there any option when I have embed in json can I somehow send using jda?

**Comment by Andre601** [comment]
`JDAImpl.createEmbed(String)` iirc.
The json will however require `"type": "rich"` too.

**Comment by Vladimir-Urik** [comment]
> `JDAImpl.getEntityBuilder().createEmbed(String)` iirc.
> The json will however require `"type": "rich"` too.

How do I get JDAImpl?

**Comment by caneleex** [comment]
`JDAImpl impl = (JDAImpl) jdaObject`

Also, you could've asked in the JDA Guild, not here, but whatever.

**Comment by Andre601** [comment]
Also, use one of the templates next time.
They exist for reasons.

**Comment by Vladimir-Urik** [comment]
Thank you and still the question is there any generator on json emed?

**Comment by MinnDevelopment** [comment]
No, we do not plan to add support for sending raw JSON structures as they are inconsistent and may change in the future.
