### ISSUE TITLE
[Question] Add role to member

### ISSUE THREAD

**Issue by TheSilentPro** [DV8FromTheWorld/JDA#1312]
How do i set Role of a member? Every article i see says Guild.getContoller() but i do not have such method.

Im using JDA 4.1.1_101 no-opus

**Comment by caneleex** [comment]
GuildController has been removed in JDA v4. [Check the migration guide](https://github.com/DV8FromTheWorld/JDA/wiki/0%29-Migrating-to-V4#guildcontroller).

**Comment by MinnDevelopment** [comment]
You have to use [Guild#addRoleToMember](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#addRoleToMember(net.dv8tion.jda.api.entities.Member,net.dv8tion.jda.api.entities.Role))

**Comment by DManstrator** [comment]
@TheSilentPro And update to the most recent version of JDA, you're quite outdated.
