### ISSUE TITLE
Activity not detected

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [DV8FromTheWorld/JDA#1316]
Hey guys,

my bot sometimes detects the current Activity of a member, sometimes don't. I have cache and intents enabled, but nothing helps.

**Comment by caneleex** [comment]
Filling out the issue template would be a lot better as you can provide your `JDABuilder` code there.

**Comment by MinnDevelopment** [comment]
Please fill out the issue template. Just saying "my code isn't working" without providing any code is completely useless. We have these templates for a reason.
