### ISSUE TITLE
Is AccountType.CLIENT still usable? 

### ISSUE THREAD

**Issue by gitvitox** [DV8FromTheWorld/JDA#1319]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ] I have checked for similar issues.
- [ ] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

Hello,
I just wanted to ask if you can still use `AccountType.CLIENT`. Because it seems that I cannot register any events with it (Will never be executed). If I use `AccountType.BOT` everything just works fine.

## Example Code

```java
public class Main extends ListenerAdapter {

    public static void main(String[] arguments) throws Exception {
        JDA builder = new JDABuilder(AccountType.CLIENT).setToken("token").addEventListeners(new Main()).build();
    }

    @Override
    public void onReady(ReadyEvent event) {
        System.out.println("test");
    }
}
```

**Comment by DManstrator** [comment]
`AccountType.CLIENT` is not working anymore due to changes of the Discord API and JDA won't fix that since the usage of Selfbots is against Discord's ToS. That constructor is also deprecated, please use the one mentioned in the docs of that contructor instead.

**Comment by MinnDevelopment** [comment]
Support for client accounts has been dropped. The CLIENT account API has diverged too far from the BOT account API so keeping support is no longer viable for us.

It is unlikely that we will support client accounts for the foreseeable future.
