### ISSUE TITLE
Invalid comma for CacheFlag enum

### ISSUE THREAD

**Issue by Lulu13022002** [DV8FromTheWorld/JDA#1335]
## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

There are an invalid comma inside CacheFlag file after MEMBER_OVERRIDES item
https://github.com/DV8FromTheWorld/JDA/blob/9e8408894409bb723d8a0c4adf53f82e753eabfe/src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java#L60

### Expected Behavior

Remove this invalid comma and put the semicolon instead

### Code Example

N/A

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment]
This comma is valid syntax.

**Comment by Andre601** [comment]
Considering that the code is still compiling without any errors can you assume that this comma isn't invalid.

**Comment by Lulu13022002** [comment]
True, but you can remove it without any issues

**Comment by caneleex** [comment]
we need ocd label
