### ISSUE TITLE
Windows deffender blocking the file due to a trojan being detected

### ISSUE THREAD

**Issue by owaingeek** [DV8FromTheWorld/JDA#1352]
![image](https://user-images.githubusercontent.com/41023839/88568529-068b7880-d031-11ea-9f99-ef5dae7005cf.png)
Windows defender removed it and I cant get it. The file is the javadoc one

**Comment by Andre601** [comment]
Use a proper dependency managment like maven or gradle.

The jar files are in no way dangerous. Your defender is just stupid.

**Comment by MinnDevelopment** [comment]
This is an issue with the windows defender not JDA.
