### ISSUE TITLE
Rate Limit 

### ISSUE THREAD

**Issue by DevJoey** [DV8FromTheWorld/JDA#1369]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ x] I have checked for similar issues.
- [ x] I have updated to the [latest JDA version][download]
- [ x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

I have try to shutdown my bot but i get this ugly message 
[DefaultShardManager] INFO RateLimiter - Waiting for 1 bucket(s) to finish. Average queue size of 0 requests

How i can fix this?

## Example Code

shardManager.shutdown();

**Comment by Andre601** [comment]
You can't "fix" this.
This was added a while back, with the reason of informing a user about why a bot might still be online (iirc).

That's not something you can disable to my knowledge (I can be wrong here tho)

**Comment by DManstrator** [comment]
I mean you can adjust the logging level so the message is not displayed but that won't fix the issue that somehow 1 bucket has 0 requests left.

**Comment by Andre601** [comment]
> I mean you can adjust the logging level so the message is not displayed but that won't fix the issue that somehow 1 bucket has 0 requests left.

Not really an issue imo. It's just JDA saying that 1 bucket had 0 requests queued at the time of shutdown, which had to finish first, which in this case would be an instant shutdown.

**Comment by DevJoey** [comment]
Ah ok, thanks for help. Now iknow what the message is :)
