### ISSUE TITLE
get the number of servers the bot is currently in

### ISSUE THREAD

**Issue by KamenkoTV** [DV8FromTheWorld/JDA#1378]

**Comment by DManstrator** [comment]
You can get that by [reading the docs](https://ci.dv8tion.net/job/JDA/javadoc/).

**Comment by MinnDevelopment** [comment]
[JDA#getGuildCache](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#getGuildCache()) then check the size. This only works **after ready** meaning you can use `JDA#awaitReady` after building before using it.
