### ISSUE TITLE
How can I change the nickname of an offline Member?

### ISSUE THREAD

**Issue by DasJNNJ** [DV8FromTheWorld/JDA#1384]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ]  I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

I have tried changing the nickname of my offline friend but it didn't work. The member is always null.

## Example Code

```java
Member member = event.getGuild().getMember(event.getMessage().getMentionedUsers().get(0));
if(member != null) {
    member.modifyNickname("Friend").queue();
} else
    event.getChannel().sendMessage("The member" + member.getUser().getName() + " is null!").queue();
```

**Comment by MCOfficer** [comment]
Most likely caused by caching, read [this](https://github.com/DV8FromTheWorld/JDA/wiki/19)-Troubleshooting#usersmembers-not-in-cache).

**Comment by RedstoneDaedalus** [comment]
1. Message#getMentionedMembers() exists, use it instead.
2. You need to retrieve the member instead of just getting it from cache. (Offline members are less likely to be cached)

**Comment by MinnDevelopment** [comment]
`getMentionedMembers()` should work regardless of the OnlineStatus.

**Comment by RedstoneDaedalus** [comment]
I didn't make myself clear; getMentionedMembers works for offline members, but the strategy that was being used would not, so retrieval would be required.
