### ISSUE TITLE
jda.getGuilds().size(); returning a 0

### ISSUE THREAD

**Issue by Vladimir-Urik** [DV8FromTheWorld/JDA#1391]
## Bug Report

`jda.getGuilds().size();` returning a 0 even though my bot is on 2 servers

JDA VERSION: `4.2.0_204 `

**Comment by caneleex** [comment]
JDA is probably not ready yet. You can use awaitReady() to block until jda has fully loaded.

**Comment by MinnDevelopment** [comment]
Closing because the template wasn't filled out correctly. #1337
