### ISSUE TITLE
How I get a 'JDA' from User (or Member)?

### ISSUE THREAD

**Issue by ramonper** [DV8FromTheWorld/JDA#1393]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
I have to get JDA of Player, but user#getJDA() return a JDA with my bot settings.
Example: I have to change User's presence (user#getJDA#getPresence().setPrecence), how I do it? Get player JDA, but not Bot JDA

## Example Code
user#getJDA#getPresence().setPrecence(Activity.playing("A Game"), true//false);

**Comment by ramonper** [comment]
I'm Brazilian, if you don't understand what I wrote, let me know.

**Comment by DManstrator** [comment]
You can't change the presence / data of another user. Maybe if they grant access to you via. OAuth, you can change stuff for a user but I don't think that you can change their status / activity.

**Comment by MinnDevelopment** [comment]
A bot can only change its own presence. Also its spelld `presence` not `precence`. If you want help you should join our discord: https://discord.gg/0hMr4ce0tIl3SLv5
