### ISSUE TITLE
ListenerAdapter isn't working on all  functions. I used in Version 3.7 onUserTyping and onUserUpdateOnlineStatus.

### ISSUE THREAD

**Issue by andybe** [DV8FromTheWorld/JDA#1397]
## General

EventListener isn't working on all  functions.
  
- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [ ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
Fallow functions are not hired by net.dv8tion.jda.api.hooks.ListenerAdapter (4.2.0)

public void onUserTyping

public void onUserUpdateOnlineStatus

### Expected Behavior

It looks like the  listener only works with generic events.

**Comment by MinnDevelopment** [comment]
- [onUserTyping](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/hooks/ListenerAdapter.html#onUserTyping(net.dv8tion.jda.api.events.user.UserTypingEvent))
- [onUserUpdateOnlineStatus](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/hooks/ListenerAdapter.html#onUserUpdateOnlineStatus(net.dv8tion.jda.api.events.user.update.UserUpdateOnlineStatusEvent))

**Comment by MinnDevelopment** [comment]
You need to enable the [GUILD_MESSAGE_TYPING][1] and [GUILD_PRESENCES][2] intents to use these events. They also require a proper [MemberCachePolicy][3]. See [enableIntents][4] and [setMemberCachePolicy][5]. Also read this wiki article [Gateway Intents and Member Cache Policy][6]

[1]: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/GatewayIntent.html#GUILD_MESSAGE_TYPING
[2]: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/GatewayIntent.html#GUILD_PRESENCES
[3]: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/MemberCachePolicy.html
[4]: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#enableIntents\(net.dv8tion.jda.api.requests.GatewayIntent,net.dv8tion.jda.api.requests.GatewayIntent...\)
[5]: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#setMemberCachePolicy\(net.dv8tion.jda.api.utils.MemberCachePolicy\)
[6]: https://github.com/DV8FromTheWorld/JDA/wiki/Gateway-Intents-and-Member-Cache-Policy

**Comment by andybe** [comment]
@MinnDevelopment  I take a look on that, but doesn't simpleficied the original function as it was before.

**Comment by MinnDevelopment** [comment]
Closing since you didn't fill out the rest of the issue template for bug reports. All the sections are necessary and useful, knowing how you configure the JDABuilder would have been a good point to start with but you omitted it for no reason. #1337

**Comment by andybe** [comment]
https://github.com/DV8FromTheWorld/JDA/wiki/Gateway-Intents-and-Member-Cache-Policy

MemberCachePolicy:
JDABuilder.createDefault(token)
          .enableIntents(GatewayIntent.GUILD_MEMBERS)
          .setMemberCachePolicy(MemberCachePolicy.ALL)
          .builder();
Should be:
JDABuilder.createDefault(token)
          .enableIntents(GatewayIntent.GUILD_MEMBERS)
          .setMemberCachePolicy(MemberCachePolicy.ALL)
          .build(); <---- 

Anyway must enable functionaly what I do not need for such simple bot (My thinking of).
