### ISSUE TITLE
Bot Won't Send Message

### ISSUE THREAD

**Issue by talentedasian** [DV8FromTheWorld/JDA#1419]
So i started building a discord bot, I just went with a very basic event. This event implements the ListenerAdapter. For some reason,
My bot won't send the message when it is running. 
My code looks like this:
`public class BotInfoCommand extends ListenerAdapter {
		static EmbedBuilder embedBuilder;
		
			public void onMessageReceived(MessageReceivedEvent event) {
			super.onMessageReceived(event);
			String message = event.getMessage().getContentRaw();
			if(message.equalsIgnoreCase("!info")){
				try {
					embedBuilder.setAuthor("dsadsa");
					embedBuilder.setColor(Color.black);
					
					event.getChannel().sendMessage(embedBuilder.build()).queue();

				} catch (RejectedExecutionException e) {
					e.printStackTrace();
				}
							}
				
				
			
			
			
			
			
			}`

My main method looks like this:
`public class main {

	public static void main(String[] args) throws LoginException, InterruptedException   {
		JDA jda = JDABuilder.createLight("NzU3NTE3MzcwNjE2MTg0ODgz.X2hjBw.8LiNEOIal9L3cihSBB-BrCLD_z0", GatewayIntent.GUILD_MESSAGES,
				GatewayIntent.GUILD_MESSAGE_TYPING).setStatus(OnlineStatus.DO_NOT_DISTURB).build();

		
		
		jda.addEventListener(BotInfoCommand.class);	
	}`

This concept(Where a member would send a message and the bot would reply)
works when I used intellij maybe a month ago and I'm now using eclipse. I don't know if it's ide related but I think it's that way.

NOTE: THE CONSOLE THAT APPEARS WHEN I RUN MY CODE WAS THE SAME WHEN I USED INTELLIJ.

**Comment by MinnDevelopment** [comment]
#1337

**Comment by DManstrator** [comment]
@talentedasian In case your token was not reset (GH normally detects that and sends a reset request to Discord), you should reset your token as soon as possible.
