### ISSUE TITLE
Stuck at boot up

### ISSUE THREAD

**Issue by gallardoS** [DV8FromTheWorld/JDA#1424]
Hi, my JDA app was working fine until this morning, when I tried to boot it up and it will never starts. It gets stuck at 

`[JDA MainWS-WriteThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket`

I haven't changed anything since the last time it was working. Can anyone help me with this? 

Thank you

**Comment by tma02** [comment]
I'm running into the exact same issue. It looks like awaitReady() never finishes and the JDA instance is stuck in LOADING_SUBSYSTEMS for me.

**Comment by tma02** [comment]
Alright so it turns out Discord now requires intents to be declared on log in, so you'll have to switch to the new JDABuilder methods to do so. After switching to ```JDABuilder.createDefault()``` it's working for me again.

**Comment by MinnDevelopment** [comment]
#1337 Pretty sure your issue is outdated JDA and/or usage of the deprecated constructors.
