### ISSUE TITLE
JDA Gateway-Worker Sending chunking requests for 2 guilds

### ISSUE THREAD

**Issue by derDennis99** [DV8FromTheWorld/JDA#1425]
Hello,
I need demanding help. after I restarted my bot it always comes up when starting:

`22:52:53.576 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.handle.GuildSetupController - Sending chunking requests for 2 guilds
22:52:53.821 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.requests.WebSocketClient - Sending chunk/sync request {"op":8,"d":{"query":"","guild_id":[xxxxx,xxxxx],"limit":0}}
22:53:13.576 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.handle.GuildSetupController - Sending chunking requests for 2 guilds
22:53:13.892 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.requests.WebSocketClient - Sending chunk/sync request {"op":8,"d":{"query":"","guild_id":[[xxxxx,xxxxx],"limit":0}}
22:53:33.577 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.handle.GuildSetupController - Sending chunking requests for 2 guilds
22:53:33.953 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.requests.WebSocketClient - Sending chunk/sync request {"op":8,"d":{"query":"","guild_id":[[xxxxx,xxxxx],"limit":0}}
22:53:53.576 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.handle.GuildSetupController - Sending chunking requests for 2 guilds
22:53:54.019 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.requests.WebSocketClient - Sending chunk/sync request {"op":8,"d":{"query":"","guild_id":[[xxxxx,xxxxx],"limit":0}}
22:54:03.590 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.core.handle.GuildSetupController - Sending chunking requests for 2 guilds`

how can I solve the problem? otherwise everything always worked out ...

Thank you
Dennis

**Comment by MinnDevelopment** [comment]
#1337
