### ISSUE TITLE
JDA stuck on loading

### ISSUE THREAD

**Issue by jiseung2007** [DV8FromTheWorld/JDA#1426]
My Discord bot worked fine two days ago but now I get stuck when loading It stops at

It's what my console says
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-WriteThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
```

I double-checked my code so code wasn't a problem I researched on the internet for 2days and but nothing was solving the problem some say downgrading JDA version works but that also doesn't seem to be fixing my problem. so can anyone help me with this? 

**JDK 1.8
JDA 4.2.0_212
Using Maven
Eclipse**

**Comment by lholl** [comment]
Hey, the problem was solved two issues previously :)
https://github.com/DV8FromTheWorld/JDA/issues/1424

**Comment by MinnDevelopment** [comment]
#1337
