### ISSUE TITLE
JDA is not registering EventListeners

### ISSUE THREAD

**Issue by gabrielcossta** [DV8FromTheWorld/JDA#1427]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ] I have checked for similar issues.
- [ ] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

So, JDA is in maintenance right know? Neither me or my friend's Discord Bot is registering EventListeners. All I can do is make the bot online.

## Example Code

```java
  public void setupBot(){
        try {
            jda = new JDABuilder(AccountType.BOT).setToken("NzY0NTEwODE0ODk5Nzk4MDM2.X4HULg.Dp7BFgQMBJh4wOANm4mpdUaqTvo").build();
            jda.addEventListener(new Authorize());
            jda.addEventListener(new Tickets());
            jda.addEventListener(new Verify());
            activityRunnable();
        } catch (LoginException e) {
            e.printStackTrace();
        }
    }

    public void disable(){
        jda.shutdownNow();
    }

    private void activityRunnable(){
        new Timer().schedule(
                new TimerTask() {
                    @Override
                    public void run() {
                        if (number != Bukkit.getOnlinePlayers().size()) {
                            number = Bukkit.getOnlinePlayers().size();
                            jda.getPresence().setActivity(Activity.playing("jogar.rankupfacturer.tk - " + number + " online"));
                        }
                    }
                }, 1000, 1000*10

        );
    }
```

**Comment by TopiSenpai** [comment]
nice bot token

**Comment by MinnDevelopment** [comment]
You're using a deprecated feature. The `new JDABuilder(...)` constructor has been deprecated for months and should be replaced with the static factory functions. Such as `JDABuilder.createDefault(token)`.

Read up on intents and caching:
- <https://github.com/DV8FromTheWorld/JDA/releases/tag/v4.2.0>
- <https://github.com/DV8FromTheWorld/JDA/wiki/Gateway-Intents-and-Member-Cache-Policy> 
- <https://github.com/DV8FromTheWorld/JDA/wiki/0%29-Migrating-to-V4>
