### ISSUE TITLE
My Bot Listeners are not working anymore

### ISSUE THREAD

**Issue by 10qu** [DV8FromTheWorld/JDA#1428]
I had a working Discord Bot using JDA with Maven. Then I just restarted the Bot and nothing worked anymore. No Listeners are working anymore. The Bot shows up as online, but nothing works anymore. I already created a new "base" just for testing, and it's not working too

**Comment by RedDaedalus** [comment]
#1424

**Comment by Andre601** [comment]
Please follow the issue template. (#1337)

**Comment by MinnDevelopment** [comment]
#1337
