### ISSUE TITLE
Add feature to let the bot stop whatever process it is doing.

### ISSUE THREAD

**Issue by InsertNameHere413** [DV8FromTheWorld/JDA#1432]
**Feature Request**
Add a feature / function that allows the bot to stop doing whatever it is currently doing in order to do something else.

**Example Use-Case**
If the bot is in an infinite loop by accident and the user wants to stop it without shutting it down, the user could simply type in a command to get the bot to stop.
If the bot is currently doing something such as deleting past messages or adding reactions to a message and a user asks it to do something else the bot or user can stop that task in order to do something else.
**A specific example for a use-case:** A bot has to add 20 reactions to a message. Whatever reaction a user chooses will load a specific message. Loading reactions takes time. If the user clicks on a reaction before all have loaded in, this error is presented:
```[ForkJoinPool.commonPool-worker-3] 
ERROR RestAction - RestAction queue returned failure:    
[ErrorResponseException] 
10008: Unknown Message net.dv8tion.jda.api.exceptions.ContextException
```
If all reactions are loaded in properly, though, this error is not given. 
If this feature existed, this error will no longer happen.

**Comment by RedDaedalus** [comment]
[JDA#shutdownNow](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#shutdownNow()) exists.

**Comment by ArchdukeLiamus** [comment]
As does RestAction#setCheck

**Comment by InsertNameHere413** [comment]
> [JDA#shutdownNow](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#shutdownNow()) exists.

ShutdownNow() turns off the bot though, and no other requests can be given cause the bot will turn off. I just want the bot to stop whatever it's doing so it can be given something else to do instead.

> As does RestAction#setCheck

setCheck appears the work the same as trying to break the loop of a message, and gives the same error of:
```ERROR RestAction - RestAction queue returned failure:    
[ErrorResponseException] 
10008: Unknown Message net.dv8tion.jda.api.exceptions.ContextException```

**Comment by RedDaedalus** [comment]
You can shutdown then just reinitialize JDA. As for the exception, `ContextException` gives no information as to what the problem is. It's just used to indicate a location in the codebase.

**Comment by InsertNameHere413** [comment]
While experimenting with this, I have found out the method `CancelRequests()` is a thing.

**Comment by InsertNameHere413** [comment]
While experimenting, I found out that `cancelRequests()` is a thing. This one works just fine. Thanks for helping out.

**Comment by MinnDevelopment** [comment]
You can also cancel individual requests by calling `cancel(true)` on the future returned by `RestAction#submit`
