### ISSUE TITLE
Can't connect to JDA.

### ISSUE THREAD

**Issue by Cripacx** [DV8FromTheWorld/JDA#1434]
Since a few days, my Bot doesn't connect to Discord. 
`@SuppressWarnings("deprecation")
			JDA jda = new JDABuilder(token)
					.addEventListeners(new DiscordBot())
					.build();			
			DiscordBot.jda = jda;			
			System.out.println("Debug1");
			jda.awaitReady();
			System.out.println("Debug2");`

Debug2 doen't print anymore.
`public void onEvent(GenericEvent event) {
		if (event instanceof ReadyEvent) {
			System.out.println("Bot is online.");
		}
	}`

And the event in the main class also doesn't trigger anymore.

Congrats,
Cripacx

**Comment by duncte123** [comment]
![image](https://user-images.githubusercontent.com/8843386/97812368-201c0c00-1c81-11eb-83f7-18cf08dfc12b.png)

**Comment by MinnDevelopment** [comment]
#1337

**Comment by DManstrator** [comment]
@Cripacx For the record, you shouldn't disable deprecation warnings just because they are annoying. In this case: Without ignoring it, you would have seen that you have to use intents because that method / constructor is deprecated so people start using intents.
