### ISSUE TITLE
Reveived audio is silent

### ISSUE THREAD

**Issue by dangeol** [DV8FromTheWorld/JDA#1439]
Received audio provided by CombinedAudio object seems to be always silent since about a week. Have there been changes in the Discord API? I recently upgraded to the latest JDA version to fix another issue, and something might have gone wrong. That is why I am not sure whether the problem is really coming from JDA / Discord.

[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Example Code
[https://gitlab.com/sirimangalo/voice-recorder](https://gitlab.com/sirimangalo/voice-recorder)

**Comment by MinnDevelopment** [comment]
Try enabling member cache for voice members. This is done by default in `createDefault` as seen and explained in our [example](https://github.com/DV8FromTheWorld/JDA/blob/master/src/examples/java/AudioEchoExample.java). You can do this manually with `setMemberCachePolicy(MemberCachePolicy.VOICE)` on your `JDABuilder` instance.

For the future, please use the bug report template.

See also #904

**Comment by dangeol** [comment]
Thanks a lot @MinnDevelopment , following the code in your [example](https://github.com/DV8FromTheWorld/JDA/blob/docs/development/src/examples/java/AudioEchoExample.java) did the trick!
