### ISSUE TITLE
How do I add SLF4J implementation?

### ISSUE THREAD

**Issue by nkgcp** [DV8FromTheWorld/JDA#1441]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
I'm using gradle and I want to use logger in my code,
but I don't know what to do. I want to use log4j2.
What code should I write in build.gradle and getLogger function?

**Comment by MinnDevelopment** [comment]
https://github.com/DV8FromTheWorld/JDA/wiki/Logging-Setup
