### ISSUE TITLE
[Suggestion] Edit Emote Roles

### ISSUE THREAD

**Issue by MaximilianMitterrutzner** [DV8FromTheWorld/JDA#1451]
## General Troubleshooting
- [ ] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [ ] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request
I would like to request an option to edit the whitelist of Emotes. Currently the whitelist can be queried by calling Emote#getRoles() but it is not possible to edit these roles [like it is with DiscordPy's Emoji#edit()](https://discordpy.readthedocs.io/en/latest/api.html#emoji).

### Example Use-Case
A use case would be to restrict usage of certain emotes to the user with the most coins / top rank on a leaderboard / moderators on a server.

**Comment by MinnDevelopment** [comment]
What about [EmoteManager#setRoles](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/managers/EmoteManager.html#setRoles(java.util.Set))?

**Comment by MaximilianMitterrutzner** [comment]
Seems like I just wasn't able to find this feature, thank you very much!
