### ISSUE TITLE
Throw the MessageUpdateEvent/GuildMessageUpdateEvent when a message is being crossposted

### ISSUE THREAD

**Issue by beatzzz** [DV8FromTheWorld/JDA#1453]
## Feature Request

Throw the MessageUpdateEvent/GuildMessageUpdateEvent when a message is being crossposted

### Example Use-Case

Bots can only edit crossposted messages 3 times every hour. If an event would be thrown when a message gets crossposted, you could stop the message from auto-updating. An example would be a giveaway bot that updates its message every X seconds/minutes.

**Comment by Andre601** [comment]
#1337

**Comment by MinnDevelopment** [comment]
You can use [RawGatewayEvent](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/RawGatewayEvent.html) for this. We can't fire an event since discord doesn't give us enough information to fire one.

**Comment by LikeLakers2** [comment]
@MinnDevelopment The [Message Flags](https://discord.com/developers/docs/resources/channel#message-object-message-flags) has a `CROSSPOSTED` flag for detecting when a message has been crossposted. Does Discord not throw out a Message Update event when this flag gets set?

**Comment by MinnDevelopment** [comment]
Even if it did, that event would only tell you the update state of the message, not what has changed. So an event could only provide an updated message instance, we can't make an event that only triggers for crossposts.
