### ISSUE TITLE
Pings from replies are not included in getMentionedUsers

### ISSUE THREAD

**Issue by octylFractal** [DV8FromTheWorld/JDA#1454]
## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

The new reply feature in Discord has the capability to mention users, however JDA does not return these users in the `getMentionedUsers()` method on `net.dv8tion.jda.api.entities.Message`, because it re-parses the mentions from the text, rather than trusting the `mentions` array from Discord.

### Expected Behavior

Users mentioned via replies (or any other way that results in an inclusion in the raw `mentions` array) should be included in `getMentionedUsers()`.

### Code Example or Reproduction Steps

Attach a listener with the following method:
```java
    @Override
    public void onGuildMessageReceived(GuildMessageReceivedEvent event) {
        System.err.println(event.getMessage().getMentionedUsers());
    }
```
Then reply to your own message in a guild that the bot is also in, and behold the empty list.

### Code for JDABuilder or DefaultShardManagerBuilder Used
N/A, I have debugged and the mentions _are_ in the `ReceivedMessage#mentionedUsers` TLongSet, they're just not available to the external code in any way (i.e. no API exists to read this set).

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment]
This is fixed on latest.

**Comment by octylFractal** [comment]
Would that be 4.2.0_219? Or a development release?

**Comment by MinnDevelopment** [comment]
Latest: ![latest](https://camo.githubusercontent.com/34aa97f93d95bb04ee259506e7aabcbd76629fd07d0d34c6cca2c38d84b18e79/68747470733a2f2f6170692e62696e747261792e636f6d2f7061636b616765732f64763866726f6d746865776f726c642f6d6176656e2f4a44412f696d616765732f646f776e6c6f61642e737667)

**Comment by octylFractal** [comment]
Indeed, I apologize for wasting your time with this. I reviewed the `development` branch but clearly didn't catch the fix for this.
