### ISSUE TITLE
sendMessage not actually sending any messages

### ISSUE THREAD

**Issue by EvanGrimes** [DV8FromTheWorld/JDA#1456]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
When i use the sendMessage method, it sends no message, whether it be text or if its an embed, it just does nothing. The bot has all the other info i gave it, like it having a custom "playing game" message and it says its online, it just doesn't send a message.

## Example Code
Main.java
    package com.GLE.Bot;

    import net.dv8tion.jda.api.OnlineStatus;
    import net.dv8tion.jda.api.entities.Activity;
    import net.dv8tion.jda.api.JDA;
    import net.dv8tion.jda.api.JDABuilder;

    import javax.security.auth.login.LoginException;

    public class Main {

        public static JDA jda;
        public static String prefix = "$";

        public static void main(String[] args) throws LoginException {
            JDA jda = JDABuilder.createDefault("My Bot Token").build();
            jda.getPresence().setStatus(OnlineStatus.ONLINE);
            jda.getPresence().setActivity(Activity.playing("Yeetus Deletus"));
           jda.getPresence().setActivity(Activity.listening("commands"));
           jda.addEventListener(new Commands());
        }
    }

Commands.java
        package com.GLE.Bot;

    import net.dv8tion.jda.api.EmbedBuilder;
    import net.dv8tion.jda.api.events.message.guild.GuildMessageReceivedEvent;
    import net.dv8tion.jda.api.hooks.ListenerAdapter;

    public class Commands extends ListenerAdapter {
        public void onGuildMessageReceived(GuildMessageReceivedEvent event) {
            String[] args = event.getMessage().getContentRaw().split(" ");

            if (args[0].equalsIgnoreCase(Main.prefix + "info")) {
                EmbedBuilder info = new EmbedBuilder();
                info.setTitle("It worked.... not");
                info.setDescription("oh no");
                info.addField("Creator", "Mistake #1", false);
                info.setColor(0xf26500);

                event.getChannel().sendTyping().complete();
                event.getChannel().sendMessage(info.build()).queue();
                info.clear();
            }
        }
    }

**Comment by RedstonecraftHD** [comment]
Why are you using Info#Clear()? Try to remove that line.

**Comment by RedstonecraftHD** [comment]
And you should use JDA#addEventListeners() not JDA#addEventListener()

**Comment by DManstrator** [comment]
@RedstonecraftHD JDA#addEventListeners doesn't exist. And you should use JDABuilder#addEventListener to make sure events are fired from the start.

@EvanGrimes There could actually be multiple reasons, read the [info section](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#my-event-listener-code-is-not-executed) from the Troubleshooting wiki entry and check for every item.

**Comment by MinnDevelopment** [comment]
I copied your code and it works just fine:

![image](https://user-images.githubusercontent.com/18090140/99905465-283ff800-2cd1-11eb-8bf0-259b2aae34e6.png)

**Comment by MinnDevelopment** [comment]
This seems to be an issue in your setup. JDA is working as expected, I suggest you start using a debugger and make sure your bot has access and permissions to respond. For further questions you can join our [discord server](https://discord.gg/0hMr4ce0tIl3SLv5)
