### ISSUE TITLE
Get count of reaction

### ISSUE THREAD

**Issue by nkgcp** [DV8FromTheWorld/JDA#1458]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
My code:
``` kotlin
override fun onGuildMessageReactionAdd(event: GuildMessageReactionAddEvent) {
  val guildId = event.guild.id
  val messageId = event.messageId
  if (waiting[guildId] == messageId) {
    when (event.reactionEmote.asCodepoints) {
      "U+2705" -> { // check mark
        commandProcessers[guildId]!!.game.ready(event.reaction.count)
      }
      "U+274C" -> { // X mark
        commandProcessers[guildId]!!.game.dmRole(event.member)
        event.reaction.removeReaction()
      }
    }
  }
}
```
I want to get the count of the check mark reaction,
but as written in javadoc, ```IllegalStateException``` is occurred
on ```commandProcessers[guildId]!!.game.ready(event.reaction.count)```.
How can I get the count of reaction?

**Comment by DManstrator** [comment]
You have either to retrieve the message again and then 
- get the reactions, filter for the reaction your want to check the call and call getCount on that
- retrieve the reaction users of that message with the reaction you want, queue it and check the list of the users you get back

That event should provide you directly the method to retrieve the message again.

Or just cache the reactions yourself with the Add and Remove Event so you don't need to make any request at all.

**Comment by nkgcp** [comment]
Thanks. Have a nice day :D
