### ISSUE TITLE
GatewayIntent#fromEvents method not registering reaction add intents from MessageReactionAddEvent

### ISSUE THREAD

**Issue by qbosst** [DV8FromTheWorld/JDA#1466]
## Bug Report

When I use pass the MessageReactionAddEvent into the GatewayIntent#fromEvents method it does not return the DIRECT_MESSAGE_REACTIONS and GUILD_MESSAGE_REACTIONS intents. Instead the GUILD_MESSAGES and DIRECT_MESSAGES intents are returned.

### Expected Behaviour

the DIRECT_MESSAGE_REACTIONS and GUILD_MESSAGE_REACTIONS intents should be returned 

### Code Example or Reproduction Steps

![image](https://user-images.githubusercontent.com/60557521/101280243-f1351080-37bf-11eb-9e66-229b3cb4892a.png)

### Code for JDABuilder or DefaultShardManagerBuilder Used

N/A

### Exception or Error

N/A

### Possible Fix

Before this line in the GatewayIntent#fromEvents method, add a check to see if the event is a GenericMessageReactionEvent, if so add the DIRECT_MESSAGE_REACTIONS and GUILD_MESSAGE_REACTIONS intents to the list

![image](https://user-images.githubusercontent.com/60557521/101280283-2e999e00-37c0-11eb-9a02-4f5a368c6458.png)

**Comment by Andre601** [comment]
Did you try it with the Guild specific GuildReactionAddEvent? Perhaps it has to be a guild-specific event instead of a general one to have the GUILD_* events registered?

**Comment by qbosst** [comment]
> Did you try it with the Guild specific GuildReactionAddEvent? Perhaps it has to be a guild-specific event instead of a general one to have the GUILD_* events registered?

Yeah, when I use GuildReactionAddEvent it returns GUILD_MESSAGE_REACTIONS however I want to listen to both reactions from DMs or the guild

**Comment by caneleex** [comment]
> 
> 
> > Did you try it with the Guild specific GuildReactionAddEvent? Perhaps it has to be a guild-specific event instead of a general one to have the GUILD_* events registered?
> 
> Yeah, when I use GuildReactionAddEvent it returns GUILD_MESSAGE_REACTIONS however I want to listen to reactions from both DMs and guilds

obviously if you use **Guild**ReactionAddEvent it will only add **GUILD**_MESSAGE_REACTIONS lol
