### ISSUE TITLE
Sudden Complete Breakdown

### ISSUE THREAD

**Issue by Dziaod** [DV8FromTheWorld/JDA#1467]
Suddenly my bot became unresponsive. Upon further inspection, it spewed out an error in the console. On restart, it was always the same.
 My error: `[JDA MainWS-ReadThread] ERROR EntityBuilder - Received a channel for a guild that isn't a text, voice or category channel. JSON: {"permission_overwrites":[{"allow":0,"deny":2048,"deny_new":"2048","id":"675369390530756610","allow_new":"0","type":"role"},{"allow":2048,"deny":0,"deny_new":"0","id":"675372147409158144","allow_new":"2048","type":"role"}],"last_message_id":null,"rate_limit_per_user":0,"parent_id":"696753981082566696","name":"changelog","topic":null,"position":1,"id":"739028599499128862","type":5}`

I created a whole new project and created a bot that just responds in a simple message when a certain word is said. On compiling and running the bot went online, I entered the word and nothing. Not even an error. Probably cause of the "Received a channel for a guild that isn't a text, voice or category channel" part in the error.

What's up with this?

**Comment by caneleex** [comment]
What JDA version are you running? You should update to latest.

**Comment by MinnDevelopment** [comment]
#1337
