### ISSUE TITLE
Get all members from all invited server

### ISSUE THREAD

**Issue by jiseung2007** [DV8FromTheWorld/JDA#1487]
hey, I was working on a currency project and I finished everything but realized I can only get a list of members from each server stored one at a time so the database has overwritten every time a command is sent. **How can I get all members from all invited server stored at List<Member>**

I have been using this 
**List<Member> Members = event.getGuild().getMembers();**

thanks for all support!

**Comment by arynxd** [comment]
JDA#getGuilds should return all available guilds the instance can see, you can then get the users per guild from that list.
