### ISSUE TITLE
The invisible Connection Error

### ISSUE THREAD

**Issue by LPDMinecraft** [DV8FromTheWorld/JDA#1488]
## Bug Report

When I start my bot he cant find any textchannels or voicechats.

### Expected Behavior

I want to send a message in a chat, wich I, get it by the getTextChannelById Methode

### Code Example or Reproduction Steps

N/A

**Comment by caneleex** [comment]
that's probably because jda is not ready at the time you try to get the channel, either use awaitReady() after .build() or use the ReadyEvent. also, you should've filled out the template thoroughly

**Comment by LPDMinecraft** [comment]
I made 3 while loops too wait for the programm

**Comment by caneleex** [comment]
lets not spam the issue with discussion here, join the [support guild](https://discord.gg/0hMr4ce0tIk3pSjp)

**Comment by LPDMinecraft** [comment]
The consoles says it all loaded and then my other code starts

**Comment by LPDMinecraft** [comment]
My name on Discord is LPD#6591

**Comment by caneleex** [comment]
> 
> 
> join the [support guild](https://discord.gg/0hMr4ce0tIk3pSjp)

**Comment by LPDMinecraft** [comment]
I am on the discord server, where can i join the support guild?

**Comment by caneleex** [comment]
guild = "server", go to #general
