### ISSUE TITLE
WebSockets timing out

### ISSUE THREAD

**Issue by Swedz** [DV8FromTheWorld/JDA#149]
I am trying to start up my Discord bot on an Ubuntu 16.04 Server, and it cannot maintain a websocket apparently (as I've been told)

[Here](http://hastebin.com/bivefohefi.md) is the error associated with it

I am not sure if this has to do with something I am doing wrong or not...
Thanks!

**Comment by DV8FromTheWorld** [comment]
The websocket is never able to actually make a connection with Discord.

Most likely either your VPS is somehow restricting outbound connections or the VPS's IP is banned from discord.

**Comment by DV8FromTheWorld** [comment]
Requesting an update on the issue.

**Comment by DV8FromTheWorld** [comment]
No further information has been provided for this issue, and due to the exclusitivity of it I am closing the issue. Feel free to reopen if you believe this to be a JDA error, as apposed to an internet connection issue.
