### ISSUE TITLE
How do I add a role to a member?

### ISSUE THREAD

**Issue by LouieMartin** [DV8FromTheWorld/JDA#1492]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ] I have checked for similar issues.
- [ ] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

**Comment by duncte123** [comment]
Have you tried Guild#addRoleToMember?
As documented here: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html

**Comment by LouieMartin** [comment]
not yet
