### ISSUE TITLE
help? pls

### ISSUE THREAD

**Issue by emiisss** [DV8FromTheWorld/JDA#1495]
having this in my console

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-WriteThread] ERROR WebSocketClient - WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)

yeah I know its  SLF4J but when I tried to download it and I don't know how there is no download button or anything ... this isn't a BUG but I need a direct download or smth pls

here's my download page https://prnt.sc/wkpxaf

NVM IM STUPID LOL

**Comment by MinnDevelopment** [comment]
See the [Troubleshooting Guide](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#im-getting-closecode4014--disallowed-intents)
