### ISSUE TITLE
Cannot resolve symbol 'dv8tion'

### ISSUE THREAD

**Issue by filtastisch** [DV8FromTheWorld/JDA#1498]
Hello, im trying to create a Discord Bot, but i cannot acces to the JDA libary,
Here my Main.java:
```package de.filtastisch.discord;

import de.filtastisch.discord.event.*;
import de.filtastisch.discord.lavaPlayer.*;
import net.dv8tion.jda.api.entities.*;
import net.dv8tion.jda.api.*;
import javax.security.auth.login.*;

public class Main
{
    public static void main(final String[] args) throws LoginException {
        final String token = "abcdefghijklmnopqrstuvwxyz1234567890";
        final JDA builder = JDABuilder.createDefault(token).build();
        final JDABuilder jdabuilder = new JDABuilder(AccountType.BOT);
        builder.addEventListener(new Listener());
        builder.addEventListener(new AudioListener());
        jdabuilder.setToken(token);
        jdabuilder.setStatus(OnlineStatus.ONLINE);
        jdabuilder.setActivity(Activity.streaming("Beatbox teach'n'more", "https://www.twitch.tv/filtastisch"));
        jdabuilder.build();
        System.out.println("Bot gestartet!");
    }
}
```

and here my pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.filtastisch</groupId>
    <artifactId>discord</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <repositories>
        <repository>
            <id>jcenter</id>
            <name>jcenter-bintray</name>
            <url>https://jcenter.bintray.com</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>4.2.0_227</version>
            <type>pom</type>
        </dependency>
    </dependencies>
</project>
```

but at the 
```import net.dv8tion.jda.api.entities.*;```
intellij says:
"Cannot resolve symbol 'dv8tion'"

anyone knows why?

**Comment by Andre601** [comment]
Could you please follow the issue template?

**Comment by filtastisch** [comment]
> 
> 
> Could you please follow the issue template?

hab ich doch?

**Comment by Andre601** [comment]
You didn't

Your issue looks like this:
![image](https://user-images.githubusercontent.com/11576465/105088569-5ad15b80-5a9c-11eb-881c-ee5afce35a0f.png)

The Bug Report template looks like this:
![image](https://user-images.githubusercontent.com/11576465/105088629-6fadef00-5a9c-11eb-8de7-3c7c6b7b6b51.png)

Please actually use the templates provides as not doing gets your issue ignored and closed.

**Comment by arynxd** [comment]
also you use the deprecated constructors.

**Comment by filtastisch** [comment]
> 
> 
> You didn't
> 
> Your issue looks like this:
> ![image](https://user-images.githubusercontent.com/11576465/105088569-5ad15b80-5a9c-11eb-881c-ee5afce35a0f.png)
> 
> The Bug Report template looks like this:
> ![image](https://user-images.githubusercontent.com/11576465/105088629-6fadef00-5a9c-11eb-8de7-3c7c6b7b6b51.png)
> 
> Please actually use the templates provides as not doing gets your issue ignored and closed.

this is exactly what i've done

**Comment by filtastisch** [comment]
> 
> 
> also you use the deprecated constructors.

thats not my problem.....

**Comment by arynxd** [comment]
check out the FAQ / Troubleshooting pages on the wiki. should fix your issues

**Comment by Toadless** [comment]
> > also you use the deprecated constructors.
> 
> thats not my problem.....

Yes it is your problem.

**Comment by Andre601** [comment]
Please stop acting stupid. You clearly didn't follow the issue template, so why should we bother helping you at all? As you can see on my second screenshot are there checkboxes that you didn't check, titles that don't exist in your issues, missing steps to reproduce, etc.

Put it simply: You didn't follow the issue template, period.

**Comment by MinnDevelopment** [comment]
#1337
