### ISSUE TITLE
The use of compile in the README and Wiki

### ISSUE THREAD

**Issue by arynxd** [DV8FromTheWorld/JDA#1502]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
I noticed the gradle examples used in the [README](https://github.com/DV8FromTheWorld/JDA/blob/master/README.md#download), the [IntelliJ Setup](https://github.com/DV8FromTheWorld/JDA/wiki/2%29-IntelliJ-IDEA-Setup) and [Eclipse Setup](https://github.com/DV8FromTheWorld/JDA/wiki/2%29-Eclipse-Setup) all used the now deprecated **compile** build option, see the [gradle docs](https://docs.gradle.org/current/userguide/upgrading_version_5.html). This should be replaced with **implementation** or **api**. Asking as question as you cannot currently PR the wiki and i'm not sure if its set as **compile** for a reason.

## Example Code

Not relevant.

**Comment by MinnDevelopment** [comment]
This is intentional.
