### ISSUE TITLE
Nickname not changable Nullpointer Exception

### ISSUE THREAD

**Issue by SeekYML** [DV8FromTheWorld/JDA#1504]
Heres the code i am using:

```Java
jda.getGuildById("804452367855779862").getMemberById(discordid).modifyNickname(playername);
```

[Error log](https://pastebin.com/1FeugsWn)

discord id, playername works fine. Both returning the right values and getting the JDA / Guild and Member also works fine since the other functions right before that work just fine.

**Comment by arynxd** [comment]
getMemberById only searches the cache, use retrieve instead or enable chunking

**Comment by arynxd** [comment]
also you need to queue the modify, its a restaction

**Comment by MinnDevelopment** [comment]
#1337
