### ISSUE TITLE
How can I run JDA methods on a JDABuilder?

### ISSUE THREAD

**Issue by SpaceByteDev** [DV8FromTheWorld/JDA#1508]
My last issue was closed. My problem is, I need to get the presence of a JDABuilder. I've tried adding a cast. I've tried everything, in my last issue, it wasn't clear what I was supposed to do. All I was told is "and then afterwards you can set it with JDA#getPresence" I don't have a jda variable. Do I have to setup a new JDA with the same bot in order to do stuff? I remember a couple months ago using a JDA, not a JDABuilder, but I don't have that code. I really wish i did.

**Comment by MinnDevelopment** [comment]
Since you don't seem to know how to use issues you can join our discord server here: https://discord.gg/0hMr4ce0tIl3SLv5
