### ISSUE TITLE
Error while trying to get a message by id

### ISSUE THREAD

**Issue by Paradocxie** [DV8FromTheWorld/JDA#1518]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting
I try to get a message by id, for checking if the message is my message. And I always get a NullPointerExeption.

## Example Code

```java


if (Objects.equals(channel.getHistory().getMessageById(msgId).toString(), HelpCommand.getEmbed(category).build().toString())) {                 
}
```

**Comment by RedDaedalus** [comment]
You cannot get a message from the channel's history before fetching history. If you need to get a single message, use [MessageChannel#retrieveMessageById](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/MessageChannel.html#retrieveMessageById(long)).

**Comment by Paradocxie** [comment]
Now I have that and nothing happen. 

```java
if (Objects.equals(event.getChannel().retrieveMessageById(msgId).toString(), HelpCommand.getEmbed(category).build().toString())) {
```

**Comment by arynxd** [comment]
retrieveMessageById is a RestAction, consider reading up on them.

**Comment by Andre601** [comment]
retrieveMessageById is a [RestAction](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction).

Please start to learn the JDA basics.

**Comment by Paradocxie** [comment]
I fixed it thx
