### ISSUE TITLE
closing connection after 522 http error

### ISSUE THREAD

**Issue by kimireichardt** [DV8FromTheWorld/JDA#1520]
Whenever the Discord API has problems I get this error:
```
[JDA AudioWS-ConnectThread (guildId: PLACEHOLDER)] WARN net.dv8tion.jda.internal.audio.AudioWebSocket - Failed to establish websocket connection to wss://us-east919.discord.media:443/?v=4: NOT_SWITCHING_PROTOCOLS - The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 522 Origin Connection Time-out
Closing connection and attempting to reconnect.
```

The bot then always loses the connection to all voice channels and doesn't reconnect.
Can I somehow determine when the Discord API has disruptions and then reconnect all the bots?

**Comment by Andre601** [comment]
Without actual information can nobody help you out.

Please follow the issue template by providing the requested information.

**Comment by MinnDevelopment** [comment]
JDA does reconnect when these errors happen. This was likely just a temporary outage that prevented it from reconnecting.
