### ISSUE TITLE
No messages coming through ListenerAdapter axcept private messages

### ISSUE THREAD

**Issue by jakebreen** [DV8FromTheWorld/JDA#1525]
I'm using version 3.8.3_464

The only message events I can get are private messages, there are no messages being received from any of the channels of the single discord server I am in. The code:

Setup JDA instance.

````
val jda = JDABuilder(AccountType.CLIENT)
        .setToken(token)
        .addEventListener(MessageListener())
        .build()

    jda.awaitReady()


Attempt to listen to any type of message... onReady does not trigger either.

```
class MessageListener: ListenerAdapter() {

    override fun onReady(event: ReadyEvent?) {
        super.onReady(event)
        println("onReady event=$event")
    }

    override fun onGenericMessage(event: GenericMessageEvent?) {
        super.onGenericMessage(event)
        println("onGenericMessage event=$event")
    }

    override fun onGenericEvent(event: Event?) {
        super.onGenericEvent(event)
        println("onGenericEvent event=$event")
    }

    override fun onGuildMessageReceived(event: GuildMessageReceivedEvent?) {
        println("onGuildMessageReceived event=$event")
    }

    override fun onMessageReceived(event: MessageReceivedEvent) {
        println("onMessageReceived event=$event")
    }

}

the only logs i get are at startup:

> onGenericEvent event=StatusUpdate(INITIALIZING->INITIALIZED)
> onGenericEvent event=net.dv8tion.jda.core.events.http.HttpRequestEvent@dacdfc5
> onGenericEvent event=StatusUpdate(INITIALIZED->LOGGING_IN)
> onGenericEvent event=net.dv8tion.jda.core.events.http.HttpRequestEvent@18c4fb2
> onGenericEvent event=StatusUpdate(LOGGING_IN->CONNECTING_TO_WEBSOCKET)
> onGenericEvent event=StatusUpdate(CONNECTING_TO_WEBSOCKET->IDENTIFYING_SESSION)
> onGenericEvent event=StatusUpdate(IDENTIFYING_SESSION->AWAITING_LOGIN_CONFIRMATION)
> onGenericEvent event=StatusUpdate(AWAITING_LOGIN_CONFIRMATION->LOADING_SUBSYSTEMS)

**Comment by RedDaedalus** [comment]
JDA3 has been deprecated for over a year, you need to update to the latest version.

**Comment by jakebreen** [comment]
I'm aware of that however the latest version will not support client accounts.

**Comment by RedDaedalus** [comment]
There is none, discord made breaking changes and you'll get bugs like the one you're experiencing. Just don't self bot.

**Comment by Andre601** [comment]
> I'm aware of that however the latest version will not support client accounts.

For obvious reasons.
Automated client accounts are not allowed by the Discord Developer ToS and JDA has removed support since they no longer work anyway.

Also, please read the readme the next time as it clearly states JDAs current position about automated clients:
> ## UserBots and SelfBots
> Discord is currently prohibiting creation and usage of automated client accounts (AccountType.CLIENT). We have officially dropped support for client login as of version 4.2.0! Note that JDA is not a good tool to build a custom discord client as it loads all servers/guilds on startup unlike a client which does this via lazy loading instead. If you need a bot, use a bot account from the [Application Dashboard](https://discord.com/developers/applications).
> 
> [Read More](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-)
