### ISSUE TITLE
Translation Support?

### ISSUE THREAD

**Issue by suchorski** [DV8FromTheWorld/JDA#1526]
Is there any way to translate the bot? For eg the help?

**Comment by RedDaedalus** [comment]
JDA does not provide any abstraction for messaging beyond sending a simple string. You need to code localization yourself as it is outside the cope of JDA.

**Comment by Andre601** [comment]
You also didn't follow any issue templates.
Please use them as they exist for a reason.

**Comment by MinnDevelopment** [comment]
This has nothing to do with JDA.
