### ISSUE TITLE
Audio sometimes doesn't play

### ISSUE THREAD

**Issue by dylanpdx** [DV8FromTheWorld/JDA#154]
I noticed an issue where audio doesn't play at times, usually when it's the first time calling
player.play()
if I do player.stop(), load my file again, and then do player.play() again, audio plays fine for the rest of the player's usage.

If you need any more info, please let me know

**Comment by DV8FromTheWorld** [comment]
Assuming you're using the built in "Player" system. These classes: Player, URLPlayer, and FilePlayer are being removed in 3.x.

Consider an alternative like https://github.com/DV8FromTheWorld/JDA-Player

That being said, If you could hastebin the code dealing with the creation and playing of the player, I'd be able to help you more.

**Comment by MinnDevelopment** [comment]
It might be possible that you are not using the [latest JDA version](http://home.dv8tion.net:8080/job/JDA/lastSuccessfulBuild/).
In a previous version the sending thread was not setup properly, however this was fixed.

If you are not on the latest version please update, check if it is fixed and report back.
In case it does indeed not fix your issue upload your code to [hastebin](http://hastebin.com) or consider switching to [JDA-Player](https://github.com/DV8FromTheWorld/JDA-Player)

**Comment by dylanpdx** [comment]
Oh, my bad. Seems I was using build 353 and not the latest. Switching to build 375 fixed the issue. Sorry for the confusion
