### ISSUE TITLE
Jcenter repo returns 403 forbidden

### ISSUE THREAD

**Issue by NathanKassab** [DV8FromTheWorld/JDA#1555]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [X] I have checked for similar issues.
- [ ] I have updated to the [latest JDA version][download]
- [X] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
Jcenter repo returns the HTTP 403 error when you go to it. I checked the wayback machine and it seems to have been this way for quite a while
## Example Code

NaN

**Comment by Andre601** [comment]
How do you actually access it?
Which url are you using?

**Comment by MinnDevelopment** [comment]
Why are you reporting this here instead of telling jfrog?

**Comment by NathanKassab** [comment]
> How do you actually access it?
> Which url are you using?

The one to add to the pom.xml file
https://jcenter.bintray.com

> Why are you reporting this here instead of telling jfrog?

I have no clue how to contact them and like I said the repo seems to have been down for a bit, they should change repos to the central repo or some other one

**Comment by MinnDevelopment** [comment]
Duplicate #1538
