### ISSUE TITLE
Timeout Method

### ISSUE THREAD

**Issue by Swedz** [DV8FromTheWorld/JDA#157]
I am trying to fix a weird issue that is causing me to not be able to stay connected and/or start a connection to the Discord API.

Is there a method to set the timeout of the bot when it is first connecting?

**Comment by DV8FromTheWorld** [comment]
In terms of timeout, no, none is currently provided for the Main WebSocket. What error are you having?

**Comment by DV8FromTheWorld** [comment]
Is this related to #149 ? It appears to be. Please Dont open additional issues for the same problem.

**Comment by Swedz** [comment]
No, this is not a duplicate, setting the timeout connection would be a workaround for that issue I was having.

**Comment by DV8FromTheWorld** [comment]
https://github.com/TakahikoKawasaki/nv-websocket-client/issues/64

**Comment by DV8FromTheWorld** [comment]
As an answer has been provided and there has been no change on this I am closing it. Feel free to reopen if you have additional issue.

**Comment by Swedz** [comment]
I'm not looking for that. I'm simply just looking for a #timeout(int) in JDA.
So we can set our own time for the connection to time out.

**Comment by TakahikoKawasaki** [comment]
I'm the author of [nv-websocket-client](https://github.com/TakahikoKawasaki/nv-websocket-client) which is used in the implementation of JDA.

<code>[WebSocket](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html)</code> class and <code>[WebSocketFactory](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketFactory.html)</code> class in nv-websocket-client provide methods to set a timeout value used for connection establishment. The following is an excerpt from <code>[README.md](https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/README.md)</code>.

---
There are two ways to set a timeout value for socket connection. The first way is to call `setConnectionTimeout(int timeout)` method of `WebSocketFactory`.

```java
// Create a WebSocket factory and set 5000 milliseconds as a timeout
// value for socket connection.
WebSocketFactory factory = new WebSocketFactory().setConnectionTimeout(5000);

// Create a WebSocket. The timeout value set above is used.
WebSocket ws = factory.createSocket("ws://localhost/endpoint");
```

The other way is to give a timeout value to a `createSocket` method.

```java
// Create a WebSocket factory. The timeout value remains 0.
WebSocketFactory factory = new WebSocketFactory();

// Create a WebSocket with a socket connection timeout value.
WebSocket ws = factory.createSocket("ws://localhost/endpoint", 5000);
```

The timeout value is passed to `connect(SocketAddress, int)` method of `java.net.Socket`.

---

It sounds that @Swedz requests that JDA provide an interface to accept a timeout value and pass it to nv-websocket-client. For example, `connect()` method of [WebSocketClient.java](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java) can be improved.

**Comment by DV8FromTheWorld** [comment]
@TakahikoKawasaki Now that I'm diving into the code I notice that `0` is consider as "no timeout", or infinite timeout. Currently, JDA allows WebsocketFactory to use the default timeout which is `0`. The issue was originally open in relation to #149 due to the fact that on attempting to connect, the WS would get `Connection Reset: Timeout` or something similar. 

Providing a timeout for the Websocket wouldn't actually fix the problem that @Swedz was having due to the fact that we were already using an infinite timeout yet still hitting a problem with reaching a timeout.

**Comment by TakahikoKawasaki** [comment]
In the Java layer, timeout should never happen when 0 is specified. However, it seems that in the real world, underlying layers such as the network stack of operating system may raise "timeout" even when an upper layer requests "no timeout". The length of such implicit timeout depends on each platform, but basically, it's too long for interactive applications. By specifying an explicit non-zero value as timeout, for example 5 seconds, interactive applications can improve user experience. So, it is meaningful to provide an interface to specify timeout.

**Comment by DV8FromTheWorld** [comment]
Yes, I still plan to provide such a setting, specifically through the `JDABuilder`, however it was more of a question of "I wonder why this is even an issue". I read through some of the closed issues on the NV Websocket github and saw the multitude of issues related to timeout, many of them harking back to implementation details at the JVM C level.

Thank you for your responses.

**Comment by DV8FromTheWorld** [comment]
This is **finally** in JDA as of 637247619b3a64a845f2ac0a1d0f6b8c1b333612 / `3.0.BETA2_150`
