### ISSUE TITLE
Cannot chain upsertPermissionOverride()

### ISSUE THREAD

**Issue by Giuliopime** [DV8FromTheWorld/JDA#1589]
## Bug Report

It's not possible to chain `upsertPermissionOverride()` methods, atm you have to queue() each request.

### Expected Behavior
Being able to do chain them and queue them all at the end.
When doing `channel.manager.queue()` it should in my opinion also check for the various PermissionOverride managers and update permissions if those managers have updated perms.

### Code Example or Reproduction Steps
```kotlin
members.forEach {
  if (stuff...) {
    println("Denying " + it.id)
    ctx.vc.upsertPermissionOverride(it).deny(Permission.VOICE_CONNECT)
  }
}

ctx.vc.manager.queue()

// Console
Denying 741070186592993292
Denying 700648820417232928

// VC permissions not updated for those members
// While if I queue each upserPermissionOverride() it does update them
```

### Code for JDABuilder or DefaultShardManagerBuilder Used
```kotlin
shardsManager = DefaultShardManagerBuilder
                .create(
                    GatewayIntent.DIRECT_MESSAGES,
                    GatewayIntent.GUILD_PRESENCES,
                    GatewayIntent.GUILD_MESSAGES,
                    GatewayIntent.GUILD_MESSAGE_REACTIONS,
                    GatewayIntent.GUILD_VOICE_STATES
                )
                .setToken(Settings.Discord.token)
                .setActivity(Activity.watching(Settings.Discord.status))
                .setStatus(OnlineStatus.ONLINE)
                .enableCache(CacheFlag.VOICE_STATE, CacheFlag.MEMBER_OVERRIDES)
                .disableCache(CacheFlag.EMOTE, CacheFlag.ACTIVITY, CacheFlag.CLIENT_STATUS)
                .setMemberCachePolicy(MemberCachePolicy.VOICE)
                .injectKTX()
                .build()
```

### Exception or Error
N/A

**Comment by MinnDevelopment** [comment]
This is not a bug. You're just not using the channel manager correctly. Use [ChannelManager#putPermissionOverride](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/managers/ChannelManager.html#putPermissionOverride(net.dv8tion.jda.api.entities.IPermissionHolder,long,long)) instead.
