### ISSUE TITLE
How to differentiate between a disconnect and move?

### ISSUE THREAD

**Issue by 247-coder** [DV8FromTheWorld/JDA#1596]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

I am trying to write a music bot, but I am unable to differentiate between someone disconnecting the bot and someone moving the bot. For both events, the connection status changes to DISCONNECTED_KICKED_FROM_CHANNEL. How do I check if it will reconnect to another channel or if it was kicked?

**Comment by Andre601** [comment]
Please follow the issue template

**Comment by DManstrator** [comment]
You can use the [`GuildVoiceMoveEvent`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/guild/voice/GuildVoiceMoveEvent.html) for that. It also mentions how a move is differentiated from a leave.

**Comment by 247-coder** [comment]
> You can use the [`GuildVoiceMoveEvent`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/guild/voice/GuildVoiceMoveEvent.html) for that. It also mentions how a move is differentiated from a leave.

Okay, thanks!
