### ISSUE TITLE
Bot can attempt to make private channel for itself

### ISSUE THREAD

**Issue by Dunciboy** [DV8FromTheWorld/JDA#160]
![image](https://cloud.githubusercontent.com/assets/10881109/19877363/df35050c-9fde-11e6-97d1-166bc39d5420.png)

user = the current jda instance bot that is being used. See the memory object reference is being SelfInfoImpl = the bot itself.

The bot should not be allowed to attempt and a create a private channel for itself as this is not allowed by discord.

**Comment by DV8FromTheWorld** [comment]
This has been addressed.
