### ISSUE TITLE
Local Image at Embed Message

### ISSUE THREAD

**Issue by DomiWe** [DV8FromTheWorld/JDA#1601]
How can i add an local Image at Embed Builder ? The Image have to be in the Embed Message and not bevore the Embed Message.

**Comment by RedDaedalus** [comment]
there's an issue format for a reason, and there's an example on the documentation.

**Comment by MinnDevelopment** [comment]
The documentation for each image setter includes an example of how to reference attachments. These attachments can be provided with `MessageChannel#sendFile`.

Closing due to #1337
