### ISSUE TITLE
Add License Information to Maven

### ISSUE THREAD

**Issue by rarcher** [DV8FromTheWorld/JDA#1627]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

JDA presently does not return any license information when queried with dependency license collection plugins such as [com.github.hierynomus.license](https://github.com/hierynomus/license-gradle-plugin) or the [License Maven Plugin](http://www.mojohaus.org/license-maven-plugin/).  It would be helpful if the necessary metadata were added to its Maven repository.

### Example Use-Case

```
downloadLicenses
{
    reportByDependency true
    includeProjectDependencies true
    dependencyConfiguration 'compileClasspath'
    licenses 'net.dv8tion:JDA:4.2.1_253': license('Apache License, Version 2.0', 'https://www.apache.org/licenses/LICENSE-2.0.txt')    // this line should not be necessary
}
```

**Comment by MinnDevelopment** [comment]
This is now available in **5.0.0-alpha.1** https://github.com/DV8FromTheWorld/JDA/blob/54871dee319ddafbbf617156411b95c856df552a/build.gradle.kts#L356-L362

https://search.maven.org/artifact/net.dv8tion/JDA/5.0.0-alpha.1/jar
