### ISSUE TITLE
Error when handle a private call

### ISSUE THREAD

**Issue by leomelki** [DV8FromTheWorld/JDA#165]
With my own Discord app, when i launch a private call, it says error : 

 Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["guild_id"] not found.
	VOICE_STATE_UPDATE -> {"self_deaf":false,"user_id":"189701620606673921","deaf":false,"session_id":"122732r4a68blq253159b477c1p61b1","mute":false,"suppress":false,"self_mute":false,"channel_id":null}

Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["embeds"] not found.
	MESSAGE_UPDATE -> {"call":{"ended_timestamp":"2016-11-09T20:20:25.371089+00:00","participants":["189701620606673921"]},"id":"341012509319336417","channel_id":"17369222125631656"}

Thank you ! (It's using JDAClient but the bug is in a JDA class)

PS : i modified the ids.

**Comment by DV8FromTheWorld** [comment]
JDAClient is a deprecated project. Please use JDA 3.x

**Comment by leomelki** [comment]
Ok, thank you but how can i login to an account with the email and password? Without a server (for oauth)

**Comment by MinnDevelopment** [comment]
Discord told us not to allow users to login using email and password credentials for it is not intended for custom clients to use it.
We will discuss if that should be possible in JDA but currently, you need to use your login token which you can get through the client console.

**Comment by leomelki** [comment]
Ok, thank you, i found how to login with user credentials. Ps : I will try to make private call work. If i success, i will send you the files ;)

**Comment by Frederikam** [comment]
@leomelki you might want to read https://github.com/hammerandchisel/discord-api-docs/issues/69#issuecomment-223886862

I highly recommend using a token instead of your email and password.

**Comment by leomelki** [comment]
I am doing a Minecraft Discord client interface so i have to use password and email :/. I will try to do all i can to avoid accounts getting banned.
