### ISSUE TITLE
Create a function that puts the number of users in a certain server id or all servers combined of a server bot into a into basically a int required function that gathers the number of users in a server or a total number of servers

### ISSUE THREAD

**Issue by MasterScary** [DV8FromTheWorld/JDA#1666]
just think this may be a cool easy feature

**Comment by Andre601** [comment]
Please ask in the [JDA Discord](https://discord.gg/jda) next time, as we could've answered this question fairly easy.

In general, there are more than enough ways to get specific values such as total amount of members or from specific guilds.

Here are two examples I quickly made.
```java
JDA jda = JDABuilder.createDefault("S3cretT0k3n")
    .build();

// get all users in total:
long totalUsers = jda.getUserCache().size();

// get from a specific server
long guildUsers = jda.getGuildCache().stream()
    .filter(guild -> guild.getIdLong() == 1234567890L)
    .map(Guild::getMembers)
    .count();
```

Also, follow the issue template next time please :)

**Comment by TopiSenpai** [comment]
no worries we already did 🙃
