### ISSUE TITLE
Split canReceiveCombined() in two functions

### ISSUE THREAD

**Issue by BaybaraEvgeny** [DV8FromTheWorld/JDA#1679]
- [ ✅] I have checked for similar issues.
- [ ✅] I have updated to the [latest JDA version][download].
- [✅ ] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

Function AudioReceiveHandler::canReceiveCombined() is called every 20 ms, but if the first call returns false, then CombinedExecutor never will be set up. 
I want to have receive combined voice feature but I don't want to receive every single packet. I want to decide if I will receive next packet or not, just like AudioSendHandler::canProvide() do every 20 ms. Also I want to maximize performance.
This function has two meanings(setting up CombinedExecutor and receiving next packet), which is wrong.
### Example Use-Case
I suggest splitting this function in two: SetCombinedExecutor() and canReceiveCombined().

**Comment by DV8FromTheWorld** [comment]
PR was rejected. See PR for details.
