### ISSUE TITLE
IllegalStateException: Could not acquire lock in reasonable timeframe

### ISSUE THREAD

**Issue by nxtByte** [DV8FromTheWorld/JDA#1696]
Hey,

in the last few days I am getting the error below and the bot stops playing music (integration with LavaPlayer, but that doesn't seem to be the problem). I have a command for the bot to connect/disconnect from a voice channel and after the error occured, it wouldn't even disconnect from the VC. If I manually disconnect the bot, it doesn't join again.

![image](https://user-images.githubusercontent.com/66949244/123766591-1d80bd80-d8c7-11eb-939d-2623f9719b48.png)

**Comment by nxtByte** [comment]
I was just shutting down the bot, when another error occured, that also involves an IllegalStateException. 
![image](https://user-images.githubusercontent.com/66949244/123767768-068e9b00-d8c8-11eb-80ac-232cadc2b5a2.png)

**Comment by MinnDevelopment** [comment]
Without a thread dump we can't help you. You need to provide the thread stacks when this issue occurs.
