### ISSUE TITLE
Cannot add file to message while using ephemeral

### ISSUE THREAD

**Issue by Speedy11CZ** [DV8FromTheWorld/JDA#1707]
**Description**
While using ephemeral, adding file to message isn't possible.

**Steps to Reproduce**
```
            event.getHook().setEphemeral(true);
            File file = new File("image.png");
            event.getHook()
                    .sendFile(file, "image.png")
                    .addEmbeds(new EmbedBuilder()
                            .setTitle("Title")
                            .setImage("attachment://image.png")
                            .build())
                    .queue();
```

**Expected Behavior**
A embed message with image from attachment.

**Current Behavior**
A embed message without image from message.

**Screenshots/Videos**
`event.getHook().setEphemeral(false);`

![image](https://user-images.githubusercontent.com/26800520/124359675-4a660500-dc26-11eb-9098-4e4b8ddd8b7f.png)

`event.getHook().setEphemeral(true);`

![image](https://user-images.githubusercontent.com/26800520/124359710-649fe300-dc26-11eb-872f-2c21f6dd6e77.png)

**Comment by TopiSenpai** [comment]
that's a limitation on discords end

**Comment by MinnDevelopment** [comment]
The [documentation for setEphemeral](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/interactions/InteractionHook.html#setEphemeral(boolean)) clearly states:

> Ephemeral messages have some limitations and will be removed once the user restarts their client.
Limitations: 
>  - Cannot contain any files/attachments

**Comment by DV8FromTheWorld** [comment]
What actions are we expecting to come from this issue?
If there's nothing we can do here, should we close this?

Can we throw an error if the RestAction attempts to finalizeData and it has a file and is set to be `ephemeral`?
I'm not sure we can determine this easily because at least the initial reply message's ephemeralness is based on the ack's ephemeralness

**Comment by Tais993** [comment]
> If there's nothing we can do here, should we close this?

Discord is gonna add this in the future, so you could keep this issue for in the future.

**Comment by ygimenez** [comment]
Discord added support for files in ephemerals today, now we gotta just wait for integration.

**Comment by TopiSenpai** [comment]
they should work now
rest of new changes are here https://github.com/DV8FromTheWorld/JDA/pull/1826

**Comment by ygimenez** [comment]
That was fast
