### ISSUE TITLE
GuildMessageEmbedEvent is not triggering

### ISSUE THREAD

**Issue by Luuk-VH** [DV8FromTheWorld/JDA#1712]
## Bug Report

Atm i have a event in my class thats called: GuildMessageEmbedEvent. Its not triggering, i already asked other people if its working for them in the newest version of JDA but its not.

### Expected Behavior

I should get the embed thats triggering the event.

**Comment by MCOfficer** [comment]
Really can't tell without your code. Chances are that this is a problem with your code. See for example /JDA/wiki/19)-Troubleshooting#my-event-listener-code-is-not-executed

Support questions should go to the discord server rather than the bugtracker. You get much faster responses there, too: https://discord.gg/0hMr4ce0tIk3pSjp

**Comment by Tais993** [comment]
[My code](https://hastebin.de/ekolususeq.java)

Tried to replicate it, 

```java
                        event.getChannel().sendMessage("Received embeds!").queue();
```

Doesn't run, using `4.3.0_293`
The raw gateway event can be found [here](https://hastebin.de/sexukeyoco.json).
The code that *should* run the event can be found below
The raw gateway event includes has an author and a type `"type" : 0,` and ` "author" : {...}`
So assuming I'm not stupid, that's why it never runs it.

```java
        //TODO: Rewrite this entire handler
        if (content.hasKey("author"))
        {
            if (content.hasKey("type"))
            {
                MessageType type = MessageType.fromId(content.getInt("type"));
                if (!type.isSystem())
                    return handleMessage(content);
                WebSocketClient.LOG.debug("JDA received a message update for an unexpected message type. Type: {} JSON: {}", type, content);
                return null;
            }
            else if (!content.isNull("embeds"))
            {
                //Received update with no "type" field which means its an update for a rich embed message
                handleMessageEmbed(content);
                return null;
            }
        }
        else if (!content.isNull("embeds"))
            return handleMessageEmbed(content);
        return null;
        ```

**Comment by DManstrator** [comment]
> [My code](https://hastebin.de/ekolususeq.java)

I know that's not the full token but you should still regenerate it for safety.

**Comment by Tais993** [comment]
> > [My code](https://hastebin.de/ekolususeq.java)
> 
> I know that's not the full token but you should still regenerate it for safety.

It's the full token and it has been invalidated by Cane (ty Cane)

**Comment by DManstrator** [comment]
It looked so short, that's why I thought it was only a part, at least it's invalidated now. :D 

```java
handleMessageEmbed(content);
return null;
```
That looks a bit odd since the return value is used below.

**Comment by Tais993** [comment]
[The MessageUpdateHandler class relating to the code I send](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java)

Is the only place where a GuildMessageEmbedEvent gets created. So I'm assuming this event *can* only run after a message gets edited.
So I tested this theory

```java
event.getChannel().editMessageEmbedsById(
        861614445901905940L,
        new EmbedBuilder()
                .setDescription("Oo - hm")
                .build()
).queue();
```

It still doesn't run and it looks like the same issue
See the raw gateway event [here](https://hastebin.de/oqerokosaf.json)

**Comment by DManstrator** [comment]
> [The MessageUpdateHandler class relating to the code I send](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java)

Pro tip: It's better to show / link a file at a current state, not from a branch since this link will be updated when time passes. And it's also good to select the lines you're talking about so it's easier to find it in big files.

[Example](https://github.com/DV8FromTheWorld/JDA/blob/0ab5896d7f893487210003a682485b5b462bccf4/src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java#L51-L71)

**Comment by Luuk-VH** [comment]
> > [The MessageUpdateHandler class relating to the code I send](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java)
> 
> Pro tip: It's better to show / link a file at a current state, not from a branch since this link will be updated when time passes. And it's also good to select the lines you're talking about so it's easier to find it in big files.
> 
> [Example](https://github.com/DV8FromTheWorld/JDA/blob/0ab5896d7f893487210003a682485b5b462bccf4/src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java#L51-L71)

Do i have to show it again because @Tais993 did already...

**Comment by DManstrator** [comment]
> Do i have to show it again because @Tais993 did already...

No, it was only a comment to Tijs.

**Comment by MinnDevelopment** [comment]
This event is specifically for embeds that are loaded *after* the message was received. Specifically, this applies to link embeds which still need to be unfurled by the discord embed handlers and will then send a delayed MESSAGE_UPDATE event to insert those embeds into the message later. That is the only case, where this event will fire.

**Comment by Tais993** [comment]
Hm, doesn't say that in the docs, makes it confusing.
I'll PR that

**Comment by Luuk-VH** [comment]
> This event is specifically for embeds that are loaded _after_ the message was received. Specifically, this applies to link embeds which still need to be unfurled by the discord embed handlers and will then send a delayed MESSAGE_UPDATE event to insert those embeds into the message later. That is the only case, where this event will fire.

So what event do you prefer?

**Comment by MinnDevelopment** [comment]
> So what event do you prefer?

Use both message received and embed event.

```java
public void onMessageReceived(MessageReceivedEvent event) {
  if (!event.getMessage().getEmbeds().isEmpty()) {
    // Someone posted a message with embeds, hoooray!!
  }
}

public void onMessageEmbed(MessageEmbedEvent event) {
  // An embed took longer to render but we still received it here
}
```

**Comment by Luuk-VH** [comment]
> 
> 
> > So what event do you prefer?
> 
> Use both message received and embed event.
> 
> ```java
> public void onMessageReceived(MessageReceivedEvent event) {
>   if (!event.getMessage().getEmbeds().isEmpty()) {
>     // Someone posted a message with embeds, hoooray!!
>   }
> }
> 
> public void onMessageEmbed(MessageEmbedEvent event) {
>   // An embed took longer to render but we still received it here
> }
> ```

I tested the MessageEmbedEvent (Only see's embeds form (example) a youtube link.
And i cant use the onMessageReceivedEvent because i am using this code:

```
        if (event.getChannel().getId().equals(channelStaff)) {
            String embedId = event.getMessageId();
            event.getMessageEmbeds().forEach(messageEmbed -> {
                embedMessageInfo.put(embedId, messageEmbed);

            });


        }
```

**Comment by MinnDevelopment** [comment]
I'm sorry, but I don't understand why you can't use this event:

```java
public void onMessageReceived(MessageReceivedEvent event) {
  if (event.getChannel().getId().equals(channelStaff)) {
    event.getMessage().getEmbeds().forEach(messageEmbed -> {
      embedMessageInfo.put(event.getMessageId(), messageEmbed);
    });
  }
}

**Comment by Luuk-VH** [comment]
Oh nvm, yeah i tried that one to but i already see what mistake i made. A usual mistake xD  thanks!

**Comment by Tais993** [comment]
Docs have been added, see #1756 (didn't correctly mention this issue, my mistake)

**Comment by MinnDevelopment** [comment]
> Docs have been added

Ah, I forgot, thanks for the reminder. Closing as resolved.
