### ISSUE TITLE
Broaden up serialisation efforts

### ISSUE THREAD

**Issue by ghandhikus** [DV8FromTheWorld/JDA#1713]
## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

MessageEmbed does not accept DataObject. Neither constructor or anything related like EmbedBuilder have it. Even though it has working toData function, there is no way to retrieve the object on other side without manually bridging it up. Sending an embed message on another machine and then sending it to a shard creates ugly code on receiving side.

### Example Use-Case

`new MessageEmbed(dataObject)`

instead of 

`new MessageEmbed(obj.getString("url"), obj.getString("title"), obj............`

**Comment by ghandhikus** [comment]
https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java#L126

**Comment by DManstrator** [comment]
You could cast `JDA` to `JDAImpl`, get the entity builder and create a MessageEmbed from a DataObject like that.

Note that those are JDA internals and it could break at any point, use it witch caution.

**Comment by ghandhikus** [comment]
I really wonder what's the point in hiding it instead of giving it a proper implementation inside the objects themselves.

**Comment by Xirado** [comment]
As @DManstrator already mentioned: https://github.com/DV8FromTheWorld/JDA/blob/3cfc750f4016ed3be20a35efbf414b6ca1c43790/src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java#L1392

**Comment by Sanduhr32** [comment]
> 
> I really wonder what's the point in hiding it instead of giving it a proper implementation inside the objects themselves.

It's not intended for general public use. It's located in the "`internal`" classpath / package, for allowing breaking changes to be received by anything in there, you are not really supposed to use them. (Unless you have to, but **you are on your own there!**)

**Comment by ghandhikus** [comment]
>It's not intended for general public use.

I was talking about serialization. There is no way to deserialze already serialized objects. Even though most of entities have option to be serialized they don't have a way to deserialize them without entity manager, or like in case of Button, hiding away again in `ButtonImpl`. There should be an interface in JDA that provides that feature without needing to rely on `EntityBuilder`. Something sort of `JDA.getEntityDeserializer()`

**Comment by MinnDevelopment** [comment]
The problem with offering these kinds of deserialization interfaces would be that you have to account for possible breaking changes. Just recently, we switched the single embed field `message.embed` to `message.embeds` to support multi-embed messages for bots. We do not want to support backwards compatibility for the underlying JSON structures used by the discord api. By only providing this in internal implementations, we also make it clear that these can break when changes are made.

**Comment by ghandhikus** [comment]
Could really go with a note to every implementation of `SerializableData` to point at general direction where you should look to deserialize the data then. At least someone who reads the source code without knowing the project can figure it out. As I'm sure most of people don't know that you can cast `JDA` to `JDAImpl` to get some extra features. Comment is necessary so it will be figured out.

**Comment by DV8FromTheWorld** [comment]
Going to close this as we do not currently have any intention of expanding the serialization surface area to include JSON -> Entity except by the EntityBuilder which is currently semi-private.
As @MinnDevelopment mentioned, we don't want to publicly document the JSON -> Entity serialization because we don't want to be supporting old serialization formats when Discord changes something.

Developers are welcome to use the EntityBuilder for this purpose if needed but need to recognize that as the EntityBuilder is not part of the public API it can have breaking changes at any time.
