### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by lilmayu** [DV8FromTheWorld/JDA#1720]
https://github.com/DV8FromTheWorld/JDA/blob/382f9c8fa7d6e2ba485d06812f8c31d23eaa3d09/src/main/java/net/dv8tion/jda/api/JDA.java#L2383

Generally asking.

**Comment by DManstrator** [comment]
![because](https://cdn.discordapp.com/attachments/106126169627181056/231117241892995072/unknown.png)


To be serious: It just an easter egg, is in JDA since at least 2016. Was called `installAuxiliaryCable` back then afaik.

**Comment by DV8FromTheWorld** [comment]
I see nothing wrong here. It's part of the overall subsystem for installing the Auxiliary Cable for trivial Audio Transfer via a platform's Audio Auxiliary Port.

For some background, the invention of JDA's Auxiliary Audio Passthrough is actually built on previous advancements and derivatives of the Auxiliary port technology originally pioneered by Rockwell Automation. You can learn more about some of their technology [here](https://www.youtube.com/watch?v=RXJKdh1KZ0w)
