### ISSUE TITLE
GuildMessageUpdateEvent - how do i get the message before it is updated

### ISSUE THREAD

**Issue by Slimey2003** [DV8FromTheWorld/JDA#1723]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

**Comment by Xirado** [comment]
You need to cache it yourself

**Comment by MinnDevelopment** [comment]
To quote the [Troubleshooting Guide](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#i-cant-get-the-previous-message-content-from-deleteupdate):

> When discord emits a message_delete or message_update they only provide the new content of the message. Since JDA does not keep a cache of messages it is unable to provide the previous content. Instead you will have to track content of messages yourself.
