### ISSUE TITLE
[JDA Gateway-Worker 1] WARN WebSocketClient - Missed 2 heartbeats! Trying to reconnect...

### ISSUE THREAD

**Issue by Yellowstrawberrys** [DV8FromTheWorld/JDA#1734]
When I start the bot, then in log "[JDA Gateway-Worker 1] WARN WebSocketClient - Missed 2 heartbeats! Trying to reconnect..." this message comes out but my internet is not bad at all(30mbps / 10mbps) and I googled it how to fix it but all answer was internet is bad; please help me :( 
I restarted too.

I'm using raspberry pi 4b 8Gb for hosting bot
and Germany internet

**Comment by MinnDevelopment** [comment]
Converting to discussion, since you didn't fill out any of the issue templates. See #1337
