### ISSUE TITLE
Add support for new NUMBER slash command option type

### ISSUE THREAD

**Issue by nikammerlaan** [DV8FromTheWorld/JDA#1744]
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

Add support for the new NUMBER option type for slash commands.

### Example Use-Case

`/example input:1.5`

**Comment by MinnDevelopment** [comment]
This is supported as of [4.3.0_310](https://ci.dv8tion.net/job/JDA/310/)
