### ISSUE TITLE
Select Menus

### ISSUE THREAD

**Issue by ZyranDev** [DV8FromTheWorld/JDA#1763]
Hi, I would like to suggest that the possibility of adding menus to messages be added

https://discord.com/developers/docs/interactions/message-components#select-menus

**Comment by DManstrator** [comment]
The issue template tells you to update the latest version of JDA. JDA is already capable to sending [`SelectionMenu`s](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.html). Please do what the issue template asks before opening the issue next time.
