### ISSUE TITLE
Allow MessageBuilder to be built without content or an embed to allow for standalone Action Rows

### ISSUE THREAD

**Issue by GenixZero** [DV8FromTheWorld/JDA#1772]
Allow MessageBuilder to be built without content or an embed to allow for standalone Action Rows

**Comment by DV8FromTheWorld** [comment]
[Discord requires that on of `content`, `embeds, `files`, or `sticker_ids` be provided on every message](https://discord.com/developers/docs/resources/channel#create-message-jsonform-params).
