### ISSUE TITLE
Bot Button (This interaction failed)

### ISSUE THREAD

**Issue by NuggetRP** [DV8FromTheWorld/JDA#1791]
Well i've setup the buttons as the Wiki said, and im getting this error "This interaction failed"

My code:
@Override
public void onButtonClick(ButtonClickEvent e) {
	   System.out.println("Clicked Button " + e.getComponentId());
}

Adding the button with:
.setActionRow(Button.primary("test", "Test Button").withId("test").asEnabled(), Button.secondary("test2", "Test Button 2").asDisabled())

And yes, i've implemented ListenerAdapter x)
Anyone know why this is happening?

**Comment by MinnDevelopment** [comment]
See the [Troubleshooting Guide](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#this-interaction-failed--unknown-interaction):

> This means you didn't acknowledge or reply to an interaction in time. You only have 3 seconds to reply or acknowledge. You have to use event.deferReply().queue(), event.deferEdit().queue(), event.editMessage(...).queue(), or event.reply(...).queue(). (If you don't queue() it won't do it)
Make sure your event listener code is executed.

**Comment by NuggetRP** [comment]
Gero.jda.getGuildById("879498868419616849").getTextChannelById("879786707468292176").editMessageById("879786740943044608", embed.build())
			.setActionRow(Button.primary("test", "Test Button").withId("test").asEnabled(), Button.secondary("test2", "Test Button 2").asDisabled())
			.queue();
			
Thats the message im editing with a button

**Comment by Tais993** [comment]
Read Minn's message

> This means you didn't acknowledge or reply to an interaction in time. You only have 3 seconds to reply or acknowledge. You have to use event.deferReply().queue(), event.deferEdit().queue(), event.editMessage(...).queue(), or event.reply(...).queue(). (If you don't queue() it won't do it)
Make sure your event listener code is executed.
