### ISSUE TITLE
onGuildMemberJoin Event not working

### ISSUE THREAD

**Issue by Yavar007** [DV8FromTheWorld/JDA#1796]
HI,

when i invite users to my servers the onGuildMemberJoin event doesn't call, i mean i get nothing even when i put breakpoint on it, 
like nothing happened

anyone know what is the problem?

**Comment by Tais993** [comment]
[Next time, don't ignore the template.](https://github.com/DV8FromTheWorld/JDA/issues/1337)
Either copy paste the bug-report template or close this one and create a new one.

Most likely you didn't read the docs, nor did you look at the Github wiki

[my-event-listener-code-is-not-executed](https://github.com/DV8FromTheWorld/JDA/wiki/19)-Troubleshooting#my-event-listener-code-is-not-executed)
[GuildMemberJoinEvent]https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/guild/member/GuildMemberJoinEvent.html)

After making sure you read both of those, follow the template when creating a bug report.
