### ISSUE TITLE
Support Subcommands & OptionData on one CommandData object

### ISSUE THREAD

**Issue by hwdotexe** [DV8FromTheWorld/JDA#1802]
- [x] I have checked for similar issues.
- [x] I have updated to the latest version (4.3.0_314)
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request
When using SubCommands, update CommandData to support a call with no SubCommand, or with OptionData on the base command.

### Example Use-Case
```java
CommandData commandData = new CommandData(my_name, my_description);
SubcommandData subCommandData = new SubcommandData(sub_name, sub_description);

// Calling "/example subCommand" will issue Behavior A.
commandData.addSubcommands(subCommandData);

// Calling "/example" or "/example optional:text" will issue Behavior B
commandData.addOption(OptionType.STRING, "optional", "an optional parameter", false);
```

I am writing a bot that has commands with an amount of complexity. I've simplified an example below to demonstrate the feature I feel is missing.

___

#### 🟢 Scenario
My command, `/example`, sends a message in chat which a server member had previously configured with the bot. To do this, they used a SubCommand: `/example create my_example`

Now, a different server member wants to run `/example my_example` to retrieve the message that was stored.

#### ⚠️ The Problem
Given the current command system, the scenario is not possible. SubCommands and OptionData are mutually-exclusive on the same CommandData object.

#### 💡 Workarounds
I would need to (1) build in a separate SubCommand like `/example retrieve my_example` in order to accomplish this, or I could (2) make `create` an optional OptionData instead, and adjust behavior later.

However, the issues I've encountered are:
1. Option 1 adds unnecessary complexity & verbosity, something that can be solved in a simpler way.
2. Option 2 breaks Single Responsibility: the purpose of this OptionData would be used as a fake SubCommand AND as a parameter for `my_example`, depending on how it was called.

#### 🙏 Why this feature would be welcome
I accept that a SubCommand is the better workaround, and I am comfortable doing so. However, I like this alternative approach for a few reasons:
1. This scenario could be possible, and the pattern is seen elsewhere (for example, certain Windows and Linux command-line functions).
2. It provides more flexibility with command syntax, and allows the user to issue another sub-command without the extra text in the call.
3. My server members are familiar with an old syntax (pre-slash command era) that operated this way

The full Example command tree could look like this:
`/example create <my_example> [optional parameters]`
`/example delete <my_example>`
`/example [saved message]`
`/example` (for help or default behavior purposes)

#### 👋 Final thoughts
If this is a Discord API limitation, I am more than willing to make this request on their end as well. In the event that they add support for this functionality, I would love to see it incorporated into JDA.

Thanks!

**Comment by MinnDevelopment** [comment]
This is not possible due to API limitations by discord: https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups

> Using subcommands or subcommand groups will make your base command unusable. You can't send the base /permissions command as a valid command if you also have /permissions add | remove as subcommands or subcommand groups

**Comment by CanIGetaPR** [comment]
> Now, a different server member wants to run /example my_example to retrieve the message that was stored.

@hwdotexe they should run `/example get my_example` to retrieve the message that was stored. That entails adding a `get` sub command.

**Comment by d4niz** [comment]
Can u make a subcommand in JDA v2023 pls!!
