### ISSUE TITLE
Extend interfaces that contain RestAction close() from AutoCloseable

### ISSUE THREAD

**Issue by VxDxK** [DV8FromTheWorld/JDA#1804]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request
Now close() method in interface such as [PrivateChannel](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/api/entities/PrivateChannel.java) return RestAction. What about rename method to **RestAction\<Void> closeNative()** and add default realization for AutoCloseable.close()
For example:

    RestAction<Void> closeNative();
    
    default void close(){
	    closeNative().queue();
    }

**Comment by MinnDevelopment** [comment]
You don't need to close private channels, and promoting this through an AutoClosable implementation would be counter-productive since it would imply incorrect usage of the interface.
