### ISSUE TITLE
JDA 3.0: No way to play audio to VoiceChannel?

### ISSUE THREAD

**Issue by meowingtwurtle** [DV8FromTheWorld/JDA#182]
I am working on co-developing a Discord bot which needs to be able to play audio to a voice channel.

We are working on updating to JDA 3.0, but we have found that AudioManager has been removed, so we don't know how to play audio. Is there any other way which we could do this?

Thank you for your time,
MeowingTwurtle

**Comment by DV8FromTheWorld** [comment]
I am actually currently in the process of rewriting audio for 3.0. It will be along shortly.

**Comment by meowingtwurtle** [comment]
Okay, thanks for the info!
