### ISSUE TITLE
Limit AuditLog results

### ISSUE THREAD

**Issue by NicklasMatzulla** [DV8FromTheWorld/JDA#1828]
## Question
I would like to find out the user who invited the bot. I have done this so far. The only problem is that when I retrieve the AuditLog for it, I then get all the entries that were created in each case. So my question is, how do I get the last 10-25 AuditLog entries without having to print them all out.

## Code
```
    public static User getBotInviter(Guild guild) {
        JDA jda = guild.getJDA();
        for (AuditLogEntry auditLogEntry : guild.retrieveAuditLogs()) {
            if (auditLogEntry.getType().equals(ActionType.BOT_ADD)) {
                User victim = jda.getUserById(auditLogEntry.getTargetIdLong());
                if (victim == jda.getSelfUser()) {
                    return auditLogEntry.getUser();
                }
            }
        }
        return null;
    }
```

**Comment by MinnDevelopment** [comment]
I would recommend using a callback instead to avoid long blocking operations:

```java
public static void getBotInviter(Guild guild, Consumer<? super User> callback) {
  long selfUser = guild.getJDA().getSelfUser().getIdLong();
  guild.retrieveAuditLogs()
    .type(ActionType.BOT_ADD) // limit by action type
    .limit(25) // get most recent 25
    .queue(list -> {
      list.stream()
        .filter(log -> log.getTargetIdLong() == selfUser) // filter by self user
        .map(AuditLogEntry::getUser) // get responsible user
        .findFirst() // find the first user that matches
        .ifPresent(callback::accept); // run callback
    });
}
```

In the caller this would work like this:

```java
getBotInviter(guild, user -> {
  // code here
});
```

See also:

- [AuditLogPaginationAction#type](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.html#type(net.dv8tion.jda.api.audit.ActionType))
- [PaginationAction#limit](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.html#limit(int))
- [Comparing two objects in Java](https://stackoverflow.com/a/14053876/10630900)

**Comment by NicklasMatzulla** [comment]
> I would recommend using a callback instead to avoid long blocking operations:
> 
> ```java
> public static void getBotInviter(Guild guild, Consumer<? super User> callback) {
>   long selfUser = guild.getJDA().getSelfUser().getIdLong();
>   guild.retrieveAuditLogs()
>     .type(ActionType.BOT_ADD) // limit by action type
>     .limit(25) // get most recent 25
>     .queue(list -> {
>       list.stream()
>         .filter(log -> log.getTargetIdLong() == selfUser) // filter by self user
>         .map(AuditLogEntry::getUser) // get responsible user
>         .findFirst() // find the first user that matches
>         .ifPresent(callback::accept); // run callback
>     });
> }
> ```
> 
> In the caller this would work like this:
> 
> ```java
> getBotInviter(guild, user -> {
>   // code here
> });
> ```
> 
> See also:
> 
> * [AuditLogPaginationAction#type](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.html#type(net.dv8tion.jda.api.audit.ActionType))
> * [PaginationAction#limit](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.html#limit(int))
> * [Comparing two objects in Java](https://stackoverflow.com/a/14053876/10630900)

thanks :)
