### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CrazyFish159** [DV8FromTheWorld/JDA#1840]
Hey!
i have an error whan i send msg on my server
the error

https://paste.gg/p/anonymous/831e4faec9cc460f99fdadd7cf1cd69c

and i didnt add any debug or something.

**Comment by freya022** [comment]
[Same issue as last time](https://github.com/DV8FromTheWorld/JDA/issues/1780#issuecomment-899777339)

**Comment by CrazyFish159** [comment]
nononono the bot can send msg 
![image](https://user-images.githubusercontent.com/77003234/134245152-96b0d327-dc1e-447b-87e2-f9faa4bc7b88.png)

**Comment by freya022** [comment]
What i meant is the solution is the same, it's a bukkit issue, not JDA

**Comment by Andre601** [comment]
I won't repeat myself so I link to my previous response:
https://github.com/DV8FromTheWorld/JDA/issues/1780#issuecomment-899783240

**Comment by DV8FromTheWorld** [comment]
#1337
