### ISSUE TITLE
Add Missing Channel Types

### ISSUE THREAD

**Issue by CanIGetaPR** [DV8FromTheWorld/JDA#1856]
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

JDA is missing the news, and thread channel types.

[Discord Documentation](https://discord.com/developers/docs/resources/channel#channel-object-channel-types)
[ChannelType.java ](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/api/entities/ChannelType.java)

- [ ] Add GUILD_NEWS channel type
- [ ] Add GUILD_NEWS_THREAD channel type
- [ ] Add GUILD_PUBLIC_THREAD channel type
- [ ] Add GUILD_PRIVATE_THREAD channel type

**Comment by TopiSenpai** [comment]
those channel types will be added with jda5 which includes thread support

**Comment by Xirado** [comment]
Also, News channels do exist in JDA, they're just a variant of a `TextChannel` at the moment

**Comment by CanIGetaPR** [comment]
Oh right. Im used to GitLab where the "cards" in projects are actual issues, so I didn't see it was getting worked on.

**Comment by CanIGetaPR** [comment]
@MinnDevelopment I suggest the feature request template has a checkbox for checking the [Projects](https://github.com/DV8FromTheWorld/JDA/projects) to see if the feature is already planned.
