### ISSUE TITLE
Add Support for Scheduled Events

### ISSUE THREAD

**Issue by Hok-2323** [DV8FromTheWorld/JDA#1862]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

Discord has added its own integrated [event thing](https://support.discord.com/hc/en-us/articles/4409494125719-Scheduled-Events). Implement the 'Event' Feature from Discord.

### Example Use-Case

Example code or use cases can't be mentioned here as wouldn't know how to integrate Bots with it.

**Comment by TopiSenpai** [comment]
jda does not 
besides that they are working on the bot api for events
see: https://github.com/discord/discord-api-docs/pull/3586

the current api is not final and subject to change

**Comment by itsmefox** [comment]
discord/discord-api-docs#3586 got merged.

**Comment by Yashar256** [comment]
I'm almost done writing the necessary interfaces/documentation for this, I'll try to see if I can create a draft PR in a bit if anyone would like to help implement it.

**Comment by MinnDevelopment** [comment]
This is supported as of [5.0.0-alpha.22](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.22)
