### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by jonjon1322** [DV8FromTheWorld/JDA#1884]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
i was following the outdated [discord bot creator](https://medium.com/discord-bots/making-a-basic-discord-bot-with-java-834949008c2b) and it outputs with the following lines 

i was following the outdated [discord bot creator](https://medium.com/discord-bots/making-a-basic-discord-bot-with-java-834949008c2b)
error: package net.dv8tion.jda.core does not exist
import net.dv8tion.jda.core.AccountType;
im trying to figure out why this is happening

## Example Code

```
import net.dv8tion.jda.core.AccountType;
import net.dv8tion.jda.core.JDABuilder;

import javax.security.auth.login.LoginException;

public class main extends ListenerAdapter {
    public static void main(String[] args) throws LoginException {
        JDABuilder builder =
        new JDAuilder(AccountType.BOT);
        String token = "ODk1Nzc3NjU1NDkwNzczMDQz.YV9f8w.V_AM3tVQUR4zdAt_0O_IO93FjKk";
        builder.setToken(token);
        builder.addEventListener(new Main());
        builder.buildAsync();
    }

    @Override
    public void onMessageReceived(MessageReceivedEvent event) {
        System.out.println("We received a message from " +
                event.getAuthor().getName() + ": " +
                event.getMessage().getContentDisplay()
        );
        if (event.getMessage().getContentRaw().equals("!ping")) {
            event.getChannel().sendMessage("Pong").queue();
        }
    }
}

```
File: [my-jda-bot2.zip](https://github.com/DV8FromTheWorld/JDA/files/7494030/my-jda-bot2.zip)

**Comment by V-Play-Games** [comment]
1. You shouldn't be using the deprecated Constructor, use the static `createDefault(..
)` or `createLight(...)` methods instead
2. Please don't post your token publicly like this, since the token is basically the login credential of your bot

**Comment by jonjon1322** [comment]
> 1. You shouldn't be using the deprecated Constructor, use the static `createDefault(...)` or `createLight(...)` methods instead
> 2. Please don't post your token publicly like this, since the token is basically the login credential of your bot and anyone would be able to log in your bot and do anything with it.
>    Since you have posted it here, please go and regenerate your token on the discord developers portal
Ok yeah I forgot about that as soon as I saw your reply I regenerated it

**Comment by MinnDevelopment** [comment]
The package for JDA was changed to `net.dv8tion.jda.api` in 4.0

**Comment by Andre601** [comment]
This page could be an interesting read for you: [0) Migrating to V4](https://github.com/DV8FromTheWorld/JDA/wiki/0%29-Migrating-to-V4)

**Comment by jonjon1322** [comment]
so that fixed it but now i went back because it keeps showing this error
```
_D:\my-jda-bot2\src\main\java\main.java:8:_ error: constructor JDABuilder in class net.dv8tion.jda.api.JDABuilder cannot be applied to given types;
        JDABuilder builder = new JDABuilder(AccountType.BOT);
                             ^
  required: java.lang.String,int
  found: net.dv8tion.jda.api.AccountType
  reason: actual and formal argument lists differ in length
```

**Comment by Andre601** [comment]
It was mentioned before: The Constructor is **deprecated**

**Comment by DManstrator** [comment]
This constructor was **removed** and the last existing one is private.*
