### ISSUE TITLE
Why is OPUS framesize hardcoded to 20ms?

### ISSUE THREAD

**Issue by tripulse** [DV8FromTheWorld/JDA#1890]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

`AudioSendHandler::provide20MsAudio`, as the method name suggests, requests for a 20ms (in-total) OPUS packet and the `DefaultSendSystem` [works on that hardcoded convention][1]. The question is, why can't we send packets of varying duration? WebRTC allows 2.5ms to 60ms and Discord (or any VoIP service) is built up on it.

There is no way either to implement a custom `IAudioSendSystem` without doing the encryption and RTP encapsulation manually, which is cumbersome. 

It is a problem for me because I am concerned with generation loss re-transcoding of a lossy codec because the packet provider already provides OPUS packets. To re-packetize, if can't then buffer and re-encode at times will complicate the process, does Discord place this restriction?

Also the provider uses *direct bytebuffers* but JDA requires a *non-direct one*, that ultimately eliminates the performance benefit *bytebuffers* are intended for.

## Example Code

https://github.com/DV8FromTheWorld/JDA/blob/a35789442ba022c81ce9b5f62d5b6b9968e3895d/src/main/java/net/dv8tion/jda/api/audio/factory/DefaultSendSystem.java#L102-L106

What is so special about send delay being less than 60ms? What does it mean?

[1]: https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/api/audio/factory/DefaultSendSystem.java#L89

**Comment by tripulse** [comment]
In the documentation of Discord (I'm not aware if anything assumed or hidden or not), however, they do not mention this frame-size limit, only that 48kHz, 2ch audio. Though due to OPUS can change it's bandwidth and number of channels at any moment the decoder is capable of resampling.

**Comment by DV8FromTheWorld** [comment]
This code was written a long long time ago, however, my understanding then and now is that discord _expects_ 20 millisecond frames of Opus.
I just tested this in the client via the audio debug menu and, indeed, discord is still sending 20 milliseconds frames from the client itself.

**Comment by DV8FromTheWorld** [comment]
Have you tested whether or not discord can/will accept a frame size that is different than 20 milliseconds?

**Comment by tripulse** [comment]
> This code was written a long long time ago, however, my understanding then and now is that discord _expects_ 20 millisecond frames of Opus. I just tested this in the client via the audio debug menu and, indeed, discord is still sending 20 milliseconds frames from the client itself.

Well that's because it's a default of an OPUS encoder. It [recommends to use 20ms](https://datatracker.ietf.org/doc/html/rfc6716#section-2.1.4) in the specification.

> Have you tested whether or not discord can/will accept a frame size that is different than 20 milliseconds?

If we presume that Discord uses the standard path (which it should), it should accept. WebRTC [supports frame-sizes upto 60ms](https://datatracker.ietf.org/doc/html/rfc7587#section-4.2), with some manageable limitations. JDA could force one frame/packet limitation and leave user to [repacketize it](https://www.opus-codec.org/docs/opus_api-1.3.1/group__opus__repacketizer.html). However, I haven't tested yet because of the difficulties I've already mentioned.

I have seen a C++ library for Discord that [supports what I want](https://dpp.dev/classdpp_1_1discord__voice__client.html#a57dd66bc916543ce9ac2f809a7ba5251). Their [example](https://dpp.dev/oggopus.html) does obey not this restriction.

```cc
                        int samples = opus_packet_get_samples_per_frame(op.packet, 48000);
 
                        v->voiceclient->send_audio_opus(op.packet, op.bytes, samples / 48);
```

Obviously, they can't be wrong in their examples. Maintaining this 20ms limit is impossible unless re-encoded or implied to provide 20ms frames.

### Possible Fix
Carry deduced duration (with [`opus_packet_get_samples_per_frame`](https://github.com/discord-java/opus-java/blob/a3d10a03d57a4f94ddc3d12dfaebe083d211cd67/api/src/main/java/tomp2p/opuswrapper/Opus.java#L214), also validates whether if its an OPUS packet for better debugging maybe?) with `IPacketProvider` and vary send delays in a `DefaultSendSystem`.
