### ISSUE TITLE
Implementation of getModerator() for GuildVoiceEvents

### ISSUE THREAD

**Issue by Andre-4949** [DV8FromTheWorld/JDA#1895]
## Feature Request
The feature is related to some ideas I made for my Bot which couldn't be fullfilled by neither JDA nor my code (which was a miserable attempt to get the moderator and only worked 40% of the time).

### Example Use-Case
- Logging which moderator muted/deafened/disconnected a member to prevent the moderator of abusing his rights

### Describe the solution you'd like
An event.getModerator(), which returns the moderator which caused the event for the following events:
- GuildVoiceLeaveEvent
- GuildVoiceMoveEvent
- GuildVoiceGuildMuteEvent
- GuildVoiceGuildDeafenEvent

(If the moderator wasn't the reason for some of these events, setting the value to null would be an option)

### Describe alternatives you've considered
As an alternative of getting the moderator I considered using the AuditLog which worked more or less 40% of the time

### Additions
- The Getter doesn't need to be named "getModerator()", I am just very bad at naming stuff, that's why i picked the most obvious name i could think of

**Comment by freya022** [comment]
Discord does not provide such information is voice events, JDA tries to wrap the Discord API as close as it can, while not providing too high level functions, as you also said, using audit logs is rather unreliable, so there is no way JDA can do it better

Unless Discord recently made a change in the API to include this info, which I am not aware of, I don't see how this feature could get added
