### ISSUE TITLE
Unknown Error Response Types

### ISSUE THREAD

**Issue by MinnDevelopment** [DV8FromTheWorld/JDA#191]
The [ErrorResponse](https://github.com/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/core/requests/ErrorResponse.java) enum is missing responses.
ErrorResponse is missing the following types:
- [x] 10014: "Unknown Emoji"
- [x] 50019: "A message can only be pinned to the channel it was sent in"

__Note__: If you encounter other unknown responses please leave a comment.

**Comment by MinnDevelopment** [comment]
Code 0 is a fallback that is commonly used for status 500 (Server Error).
We should implement a possible way to use that instead of just doing `UNKNOWN_ERROR` whenever we encounter it.

**Comment by DV8FromTheWorld** [comment]
@MinnDevelopment I know you've done research and work on the Requester/Ratelimit system the past few weeks, have you addressed this? (the code 0 issue)

**Comment by MinnDevelopment** [comment]
I have yet to find a good implementation to replace the message in the response with the one provided by discord.
I will update this issue once I find a good solution.

**Comment by DV8FromTheWorld** [comment]
Considering the lack of movement on this subject, should we close this issue as it has been a non-issue thus far?

**Comment by MinnDevelopment** [comment]
I agree, new error responses can be added dynamically. We don't need this issue anymore.
