### ISSUE TITLE
Missing setters in WebhookMessageAction

### ISSUE THREAD

**Issue by Psyvern** [DV8FromTheWorld/JDA#1929]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download]
- [X] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
Some time ago, the `WebhookMessageAction` class used to have the methods `setUsername` and `setAvatarUrl`. Now they are commented out. Why is this?

## Example Code
```
channel.getWebhook(...)
    .setUsername("example")
    .setAvatarUrl("https://example.com")
```

**Comment by MinnDevelopment** [comment]
Sending webhook messages is not currently supported by JDA. These interfaces are only used for interaction webhooks which do not support these options. You can use https://github.com/MinnDevelopment/discord-webhooks as an alternative.

**Comment by Psyvern** [comment]
Ok, thank you!
