### ISSUE TITLE
This message event did not happen in a guild on MessageReceivedEvent

### ISSUE THREAD

**Issue by OMAR-3OOV** [DV8FromTheWorld/JDA#1939]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

 I just get an error when I use `event#getGuild()` in `MessageReceivedEvent`, idk if this is a bug or something just needs to ask how to fix it, also It doesn't affect my code just throw an error ( Just to know I use 5.0.0 version of jda )

## Example Code

 event.getTextChannel().sendMessage("This message from " + event.getGuild().getName() + " guild!").queue();

**Comment by MinnDevelopment** [comment]
Please re-open this issue with the bug report template. Also specify your full exception and the exact version, including classifier, of JDA.
