### ISSUE TITLE
Joining a new Guild with a client account causes invalid member cache

### ISSUE THREAD

**Issue by MinnDevelopment** [DV8FromTheWorld/JDA#194]
When we join a new guild with a client account JDA will not sync the members properly leading to issues with the member cache.
The GUILD_CREATE payload only contains the self-member.

**Comment by DV8FromTheWorld** [comment]
After reviewing the code... we do GUILD_SYNC. It is in https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java#L267

**Comment by DV8FromTheWorld** [comment]
What evidence is there that this is a problem? Only possible problem I could for see would be if the GUILD_SYNC and GUILD_MEMBER_CHUNKS came out of order.

**Comment by DV8FromTheWorld** [comment]
Bumping this as I would like some additional information.

**Comment by Dunciboy** [comment]
Joined a new guild today. Bot disconnected and resumed session (might have been a coincidence). Bot still MessageReceivedEvents events from other guilds, but the bot did not receive MessageReceivedEvents for the new guild. I don't listen on any other events.

**Comment by DV8FromTheWorld** [comment]
Does this problem still exist?

**Comment by RYArrowsmith** [comment]
Attempted to join a guild whilst running JDA 3.0.BETA2_148. It's all good for me.

**Comment by MinnDevelopment** [comment]
This seems to be a no-issue. Feel free to continue adding information but this is currently undetected.
