### ISSUE TITLE
CPU Leak in botRateLimiter

### ISSUE THREAD

**Issue by TheEpTic** [DV8FromTheWorld/JDA#195]
Yesterday, I put my JDA 3.0 version of ErisBot live for around 40 minutes. I did this to catch any errors pre-launch.

During the test I noticed my CPU was maxed out for no reason. I loaded up VisualVM and found `com.neovisionaries.ws.client.WebSocketInputStream.readBytes()` completely chewing on the CPU.

I did some further testing to then find `net.dv8tion.jda.core.requests.ratelimit.botRateLimiter$Bucket.run()` was also be doing the same (not in production, just testing)

In testing, I created a for loop and queued 50 messages which is what caused the ratelimiter to eat the cpu.
It was eating around 20% of my overall CPU (i7-6700k) which shouldn't even be possible for queuing 50 messages.

Here are some screenshots:
http://i.imgur.com/VOXLLB7.png - Overall CPU usage
http://i.imgur.com/4IJmwX4.png - Messages from the queue
http://i.imgur.com/1KYIzim.png - The top CPU usages
http://i.imgur.com/eWIISOe.png - JVM CPU Usage (Spikes are when the messages were sent)
http://i.imgur.com/knr4K1F.png - Thread spike when flooding the channel (Can't replicate, unsure what the cause of this was)

I would also like to note that I did the same test on another JDA bot, which is designed completely different due to it's private use. I received the exact same results.

**Comment by TheEpTic** [comment]
More info:

Memory seems to fluctuate too. http://i.imgur.com/48MR3d9.png

**Comment by DV8FromTheWorld** [comment]
What tools did you use to gather and generate this information?

**Comment by TheEpTic** [comment]
https://visualvm.github.io/

**Comment by Almighty-Alpaca** [comment]
of which a copy is shipped together with the jdk btw

**Comment by Fabricio20** [comment]
Apparently we can confirm this issue, just did some tests by sending the cpu usage out of the bot instance and it maxed 99% cpu in less than 10 minutes. (JDA was using 990% and the audio processing node 8.7%).

![unknown 1](https://cloud.githubusercontent.com/assets/7545720/21071058/f0b1a3ba-be7b-11e6-86e7-9309613b2b9f.png)
![unknown](https://cloud.githubusercontent.com/assets/7545720/21071059/f0ba9358-be7b-11e6-93c6-444ab8a680ee.png)

**Comment by DV8FromTheWorld** [comment]
I believe this is fixed as of cdd5c609f289e33ef16dc6b5ff6d4fe4d68782c6

**Comment by TheEpTic** [comment]
Can confirmed it's fixed. Good job!
