### ISSUE TITLE
More Interfaces in JDA

### ISSUE THREAD

**Issue by PlayerSchark** [DV8FromTheWorld/JDA#1954]
- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

More interfaces for similar Methods eg. the Slash Command System has the same return values in Guild and JDA. The methods are exactly same named. In the whole JDA more interfaces would be better for .

### Example Use-Case

Use case is better polymorphism in applications using this api. e.g If you want to register a Slash command you need a reflections or another code construction to execute the same method in different types. And it does nearly the same. So a interface like ISlashCommandCreation with methods `upsertCommand`, `updateCommands`, `editCommandById`, `deleteCommandById`, `retrieveCommandById` and `retrieveCommands` in it would be good.

**Comment by freya022** [comment]
These method you mentioned returns the same objects, i'd say it's not really useful to break OOP (and the how JDA classes are made) just to make a slash command interface

For example I have a nullable Guild, which would determine if the application commands would go in a Guild or in the global context: `var updateAction = guild == null ? jda.updateCommands() : guild.updateCommands()`

Quite simple imo, I have not felt a need for a unified interface in that sector

**Comment by MinnDevelopment** [comment]
All the command endpoints are different between these two interfaces and can change in different ways in the future. Making a shared interface for this would quickly become unmaintainable if guild commands would allow different configuration than global commands.

I don't think you need reflection or any special logic to handle this either, if you implement your abstraction to accept the `RestAction` types or a factory, you don't need to worry about what type the command came from. Even if you implemented it by calling the methods on either Guild or JDA, you can simply use `instanceof` and cast to the right interface.

The argument for "similar method names should be abstracted" doesn't make much sense when you have a hundred different method configurations, and you would end up with interfaces like `IGetName`, `IGetUser`, `IGetChannel`, etc. which have a single method.

Do you have a more specific use-case? Example use-cases are something we ask for in the issue template for feature requests, I'm not sure why you removed that section of the template.

**Comment by PlayerSchark** [comment]
MessageActions for example `WebhookMessageUpdateAction` and `MessageAction` have both same named methods 

sure you can do sth like this:
```
	private RestAction<?> addActionButtons(RestAction<Message> action) {
		List<ActionRow> rows = this.getActionRows();
		return action instanceof MessageAction messageAction
						? messageAction.setActionRows(rows )
						: action instanceof WebhookMessageUpdateAction<?> messageUpdateAction
						? messageUpdateAction.setActionRows(rows)
						: null;
	}
```

but sth this would keep javas type safety and make it more readable:
```
	private RestAction<MessageActionable> addButtons(RestAction<MessageActionable> action) {
		List<ActionRow> rows = this.getActionRows();
		return action.setActionRows(rows);
	}
```

**Comment by freya022** [comment]
It is part of JDA 5 to work on this problem, see this image: 
![image](https://user-images.githubusercontent.com/41875020/146584214-d75d5810-f1e7-4ae3-b3b5-55331fa761d6.png)
and the convo: https://canary.discord.com/channels/125227483518861312/869965829024915466/870462812651134995

**Comment by MinnDevelopment** [comment]
You can already do this with the `MessageBuilder`:

```java
public void addButtons(MessageBuilder builder) {
  builder.setActionRows(this.getActionRows());
}
```

And the same applies to commands with `CommandData`.

**Comment by PlayerSchark** [comment]
can you give me a link to that point in changelog? O.o

**Comment by DV8FromTheWorld** [comment]
We are going to bridge the gap for the various ways to deal with messages. However, we're not looking to add interfaces for every possible intersection of features. There is a point where it is too much. Intersection interfaces are only useful if people are going to use them enough to justify the reduction in clarity and increase in maintenance cost.

If you have specific usecases where you'd like to see an intersection interface added, feel free to open another issue with a specific usecase written out.
