### ISSUE TITLE
Errors on some RestActions

### ISSUE THREAD

**Issue by Bowser65** [DV8FromTheWorld/JDA#196]
When i'm using .queue() on some rest actions, I have this error: http://pastebin.com/azYzV7Fn

I have this error when i'm using Reactions, on every RestActions
But on others RestActions (sending messages, ...) I don't have this error

**Comment by MinnDevelopment** [comment]
I request an update on this.
Does this still occur on the latest dev build?
If yes, please give the new full output for it since we added more information to the log output.

**Comment by MinnDevelopment** [comment]
I'm closing this because the additional info was not provided for 11 days, if you can give more information please re-open this issue and add it.

On a side note, does this still happen on the latest dev builds?
