### ISSUE TITLE
Guild Welcome Screen Modification

### ISSUE THREAD

**Issue by Aseeef** [DV8FromTheWorld/JDA#1987]
## General Troubleshooting
  
- [X] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

## Feature Request

I am requesting API support for modifying the guild welcome screen as documented here:
https://discord.com/developers/docs/resources/guild#modify-guild-welcome-screen

### Example Use-Case

I personally wanted to use this for a discord "clone" / "backup" bot.

The API may go something like this for retrieving welcome screen info:
boolean b = guild.getWelcomeScreen().getEnabled();
List<WelcomeChannel> wc = guild.getWelcomeScreen().getWelcomeChannels();
String desc = guild.getWelcomeScreen().getDescription();

And for updating, maybe something like:
guild.getWelcomeScreen().updateEnabled(boolean);
guild.getWelcomeScreen().updateWelcomeChannels(List<WelcomeChannel>);
guild.getWelcomeScreen().updateDescription(String);

WelcomeChannel might be a subclass TextChannel adding the addition parameter's of their structure as specified in the discord API: https://discord.com/developers/docs/resources/guild#welcome-screen-object-welcome-screen-channel-structure

**Comment by MinnDevelopment** [comment]
Support for this has been added in [5.0.0-beta.2](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-beta.2)
