### ISSUE TITLE
GuildMemberJoin thing is broken

### ISSUE THREAD

**Issue by adrian-rostin** [DV8FromTheWorld/JDA#1988]
## General Troubleshooting
  
- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

The GuildMemberJoin Event is not called after a new member joins. Any other event (e.g. the MessageReceiveEvent) are called.

After a member joins the guild the bot is running on, the event should be called, but is doesnt.

### Code Example or Reproduction Steps

```java
@Override
    public void onGuildMemberJoin(@NotNull GuildMemberJoinEvent event) {
        System.out.println("MEMBER JOINED");
    }


    @Override
    public void onMessageReceived(@NotNull MessageReceivedEvent event) {
        System.out.println("MESSAGE RECEIVED");
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder Used

```java
JDABuilder jdaBuilder = JDABuilder.createDefault(this.botToken);

        jdaBuilder.disableCache(CacheFlag.ACTIVITY);
        jdaBuilder.setChunkingFilter(ChunkingFilter.NONE);
        jdaBuilder.disableIntents(
          GatewayIntent.GUILD_WEBHOOKS,
          GatewayIntent.GUILD_PRESENCES,
          GatewayIntent.DIRECT_MESSAGE_TYPING,
          GatewayIntent.GUILD_MESSAGE_TYPING
        );

        jdaBuilder.setActivity(Activity.playing(this.activity));
```

### Exception or Error

N/A

**Comment by DManstrator** [comment]
Please read the [Troubleshooting section of the wiki](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#my-event-listener-code-is-not-executed), it might tell you why it doesn't work.

**Comment by MinnDevelopment** [comment]
You need to enable the `GatewayIntent.GUILD_MEMBERS` for this event, as explicitly said in the [documentation](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/guild/member/GuildMemberJoinEvent.html).
