### ISSUE TITLE
JDA instances unable to login when using a Droplet (Digital Ocean)

### ISSUE THREAD

**Issue by NextdoorPsycho** [DV8FromTheWorld/JDA#1990]
## General Troubleshooting

  
- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
Id like to preface this with the following: I'm relatively new to droplets and dockized instances but this is one of those issues I've been having that I have not run across before.

When making a bot project, Compiling, and sending lose on a Server, Computer, and so on everything is fine. But as soon as you toss it onto a droplet the bot cant validate the token at all
-> My actual project that I was running into the issue with: https://github.com/VolmitSoftware/Abyssalith
-> A Dummy Project that you can download and try for yourself to replicate the issue: https://github.com/VolmitSoftware/Dummy
If I'm doing anything Wrong, let me know but I'm just not sure.

### Expected Behavior

The bot should Login when on a droplet VM

### Code for JDABuilder or DefaultShardManagerBuilder Used

```
        final JDA jda;
        jda = JDABuilder.createDefault("ODc1OTczMTYxODkwNTA4ODMw.YRdTlA.dSCPnRB8pbEA4M-d4sHNDHzCg1w")
                .addEventListeners(new MyListener())
                .build();
```

### Exception or Error

No error, just unable to validate the token, Threads are just parked waiting for the rest-action from a token

**Comment by NextdoorPsycho** [comment]
Deems like its related to this
https://github.com/DV8FromTheWorld/JDA/issues/1858

**Comment by V-Play-Games** [comment]
Please try to hide your token next time, posting it publicly like this isn't a good idea
For now, go regenerate the token

**Comment by Andre601** [comment]
> Please try to hide your token next time, posting it publicly like this isn't a good idea For now, go regenerate the token

Pretty sure Discord already regenerated it since GitHub reports any sights of a token to them.

**Comment by NextdoorPsycho** [comment]
It's not a real token. I said that in the git readme

**Comment by NextdoorPsycho** [comment]
It's not a real token, I said that in the description in the readme

**Comment by Tais993** [comment]
PR's don't have a readme, so we couldn't know based off your PR alone

**Comment by NextdoorPsycho** [comment]
I didn't attach the token anywhere other than in the project that I linked. That brings your to the main page with a read me. Y'all gotta do this lol. The issue was closed
