### ISSUE TITLE
Introduce Event#getRawData

### ISSUE THREAD

**Issue by DV8FromTheWorld** [DV8FromTheWorld/JDA#2008]
We can add a getter on events to access the passthrough event data in a `DataObject`. This should be off by default and configurable on the JDABuilder. Something akin to `JDABuilder#setEventPassthrough(true)`.

Some events do not have any data to pass through, in which case we can either throw an exception or return null.

**Comment by MinnDevelopment** [comment]
This is out with 5.0.0-alpha.14
