### ISSUE TITLE
[Question] How to create instant invite?

### ISSUE THREAD

**Issue by xXAndrew28Xx** [DV8FromTheWorld/JDA#202]
How to I create an invite for a Guild in JDA-3? I remember I could via InviteUtil in JDA-2. I see http://home.dv8tion.net:8080/job/JDA/98/javadoc/net/dv8tion/jda/core/requests/Route.Invites.html

**Comment by MinnDevelopment** [comment]
This is currently on the planned section of 3.x
Invite support will be added within the next weeks.

We are putting our best men on it!

**Comment by xXAndrew28Xx** [comment]
Thanks, I'll just try to see if I can do it directly via Websockets for now and Pull Request if needed.

**Comment by MinnDevelopment** [comment]
This has been added with #223 
`Channel#createInvite(): InviteAction`
