### ISSUE TITLE
putMemberPermissionOverride overrides a Members permssion, but removes every other members permission overrides too

### ISSUE THREAD

**Issue by Spuckwaffel** [DV8FromTheWorld/JDA#2030]
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

Looking at the docs it says 

> Adds an override for the specified member with the provided permission sets as allowed and denied permissions. If the member already had an override on this channel it will be replaced instead.

But what i figured out was that whevener i use this method, it will override the permissions for the specifid member, but all the other members who have a permission override get removed. 
Here a example:
I want to make a override for a member when a text channel got created:
`
...
event.getChannel().getManager().putMemberPermissionOverride(event.getGuild().getMemberById("xxxxxxx").getIdLong(), Collections.singleton(Permission.MESSAGE_READ), Collections.singleton(Permission.MESSAGE_WRITE)).queueAfter(4, TimeUnit.SECONDS);
`
Below we see the log when i try to override the permissions for a specifid member.
![Screenshot 2022-02-20 130548](https://user-images.githubusercontent.com/68144475/154841599-48f0ef1b-7186-4e27-a21c-af334946e76b.png)
It does make a override for the speicified member, but removes all other overrides.

**Comment by Andre601** [comment]
Try out [`upsertPermissionOverride(IPermissionHolder)`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/GuildChannel.html#upsertPermissionOverride(net.dv8tion.jda.api.entities.IPermissionHolder))
I think that one will work.

**Comment by Andre601** [comment]
> `... event.getChannel().getManager().putMemberPermissionOverride(event.getGuild().getMemberById("xxxxxxx").getIdLong(), Collections.singleton(Permission.MESSAGE_READ), Collections.singleton(Permission.MESSAGE_WRITE)).queueAfter(4, TimeUnit.SECONDS);`

On another note, using `getMemberById` only to then get the ID as long is a waste of time here. You could just use [`MiscUtil.parseSnowflake(String)`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/MiscUtil.html#parseSnowflake(java.lang.String)) to get ID as a `long` returned. This may require you to do some checks first to guarantee that the String isn't null and won't throw a NumberFormatException in the process.

**Comment by DManstrator** [comment]
> On another note, using `getMemberById` only to then get the ID as long is a waste of time here. You could just use [`MiscUtil.parseSnowflake(String)`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/MiscUtil.html#parseSnowflake(java.lang.String)) to get ID as a `long` returned.

Or you could simply make that id a long if it's hardcoded anyways. Most events also give you the id of a User / Member as a long. Thus you should never need to use `MiscUtil.parseSnowflake(String)`.

**Comment by MinnDevelopment** [comment]
Can you please fill out the full issue template? We have all those section for a reason.

**Comment by MinnDevelopment** [comment]
Closing with reasoning from #1337
