### ISSUE TITLE
Can't accept friend requests

### ISSUE THREAD

**Issue by v0idst4r** [DV8FromTheWorld/JDA#204]
`@Override
	public void onFriendRequestReceived(FriendRequestReceivedEvent event) {
		new Thread(() -> {
			try {
				System.out.println("Threaded.");
				Thread.sleep(1000);
				event.getFriendRequest().accept().queue();
				System.out.println("Accepted.");
			} catch (Exception e) {
			}
		}).start();
	}`
What am I doing wrong? I see "Accepted." in the logs but my discord still thinks I have the request

**Comment by DV8FromTheWorld** [comment]
Well, if you printed anything in the exception catch you'd see that you are receiving a `NullPointerException` when you call `.queue()` on `.accept()`'s RestAction.

I haven't implemented the `accept()` and `ignore()` RestActions yet, so until i do, you unfortunately cannot accept friend requests with JDA.

**Comment by v0idst4r** [comment]
I saw that but I thought it was my code but ok I'll wait, thanks.

**Comment by DV8FromTheWorld** [comment]
I'll be visiting and completing the Client-only parts of JDA after I've released 3.0 out of beta.

**Comment by xXAndrew28Xx** [comment]
Any update @DV8FromTheWorld

**Comment by jagrosh** [comment]
Friend requests can only be accepted via the normal Discord client.

**Comment by xXAndrew28Xx** [comment]
Oh, that's too bad.

**Comment by MinnDevelopment** [comment]
Client features will remain low-priority until further notice in favor of quality assessment of the core features.
It is to be determined which client features will be available in JDA due to issues with account deverification on some api features.
