### ISSUE TITLE
Question on the possibility of implementing a work-around to get the nickname of leaving members

### ISSUE THREAD

**Issue by Andre-4949** [DV8FromTheWorld/JDA#2046]
## General Troubleshooting
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
Is it possible to implement the code that is used below to get the nickname of a Member which triggered the Guild MemberRemove Event? The current implementation doesn't work most of the time* but the work-around does.

If it is possible please let me know so I can write a feature request :)

*sometimes it does but i don't know why
## Example Code
   
    @Override
    public void onGuildMemberRemove(GuildMemberRemoveEvent event) {
        //given a User named "Test" left the guild and had the nickname "testtt"

        //works
        logger.info(event.getMember().toString().split("\\(")[0].split(":")[1]); // -> "testtt"

        // doesn't work
        logger.info(event.getMember().getNickname()); // -> null
    }

**Comment by MinnDevelopment** [comment]
I think you might be looking for [Member#getEffectiveName](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Member.html#getEffectiveName())
