### ISSUE TITLE
setVanityCode not working

### ISSUE THREAD

**Issue by humza1400** [DV8FromTheWorld/JDA#2059]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

So, the method `GuildManager#setVanityCode` is supposed to update the vanity of the guild but it isn't yet it's returning a success response as it successfully did it. I made sure to double check the bot had permissions and server had enough boosts to support the vanity url. I also tried restarting my client as well as checking audit logs. When I ran the actual PATCH request in Postman it did successfully end up changing the vanity.

### Expected Behavior

I expect the vanity code of the guild to be updated.

### Code Example or Reproduction Steps

it is to be noted that I made sure the bot wasn't rate limited and I didn't let this run in an infinite loop. Also "success" was being printed out to the console after this piece of code was ran.
```java
    @Override
    public void onGuildUpdateVanityCode(@Nonnull GuildUpdateVanityCodeEvent event) {
      event.getGuild().getManager().setVanityCode(event.getOldVanityCode()).queue(success -> System.out.println("success"), failure -> System.out.println("failure"));
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder Used
```java
jda = JDABuilder.create(Config.get("TOKEN"), GatewayIntent.getIntents(GatewayIntent.ALL_INTENTS)).setRawEventsEnabled(true).addEventListeners(listener).build().awaitReady();
```

### Exception or Error
N/A

**Comment by MinnDevelopment** [comment]
Solved by #1933
