### ISSUE TITLE
JavaDoc Roadmap

### ISSUE THREAD

**Issue by MinnDevelopment** [DV8FromTheWorld/JDA#206]
The JDA 3.x JavaDoc pass will require massive changes to classes and methods.
In this issue, I will try to break down the steps for the overall formatting of JDA.
In the JavaDoc pass, we want not only to add JavaDoc to all functionalities and document behaviour but also want to find a consistent formatting and style within JDA.

1. Create a general JavaDoc template.
2. Create a class structure guide (where to put what class part, subdivide methods...)
3. Require argument checks, both documented in JavaDoc and informed about in exception messages
4. Write a contribution wiki and PR merge requirements (what does a PR need to bring to be merged)
5. Ensure formatting consistency in JDA!

If someone wants to give input or wants to contribute to the completion of this roadmap this issue is the place to comment!

I will personally consult all of the input given on this issue and will hold a discussion about comments that I think have a valid reason to be consulted within our team/discord guild.

**Note**: JavaDoc will soon be required for every Pull-Request merge.

**Edit: JavaDoc is now a requirement for Pull-Request merge!**

**Comment by DV8FromTheWorld** [comment]
@MinnDevelopment put the current in-progress format that we talked about here please.

**Comment by MinnDevelopment** [comment]
This is the current work-in-progress JavaDoc template we internally have discussed.
It tries to format JavaDoc in a consistent way while being readable and short.
You can find it in this [gist](https://gist.github.com/MinnDevelopment/c8276d979770355ab5f4aad8a8b6a86f) which will be updated accordingly.

Once this is approved I will update the issue and add it to the contribution guide.

**Comment by MinnDevelopment** [comment]
As an additional note to the JavaDoc template, the only __required__ parts are `description`, `@param`, `@throws` and `@return`. All other mentioned tags are optional!

**Comment by DV8FromTheWorld** [comment]
I believe this should now be moved to a Wiki page and the issue closed. Thoughts?

**Comment by MinnDevelopment** [comment]
Once I've created a wiki page to replace this issue I will close this roadmap and link to the wiki page.
In the meantime anyone can still comment here so I can see more input if someone wants to give their opinion for me to consider.

**Comment by MinnDevelopment** [comment]
I have started work on [6) JDA Structure Guide](https://github.com/DV8FromTheWorld/JDA/wiki/6%29-JDA-Structure-Guide) which is now replacing this issue.
