### ISSUE TITLE
Random Json Errors popping up

### ISSUE THREAD

**Issue by Kaydax** [DV8FromTheWorld/JDA#207]
`[14:10:28] [Warning] [JDASocket]: Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["url"] not found.
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"155149108183695360","avatar":"5aeb68c29b56b3d92eddb6f46df5051c","username":"Dyno","discriminator":"3861"},"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"","tts":false,"mentions":[],"id":"256860141197066240","embeds":[{"color":1146534,"footer":{"text":"ID: 203176343616094209"},"author":{"icon_url":"https://cdn.discordapp.com/avatars/203176343616094209/5a18e9a8a7b8c7af251f438de379a744.jpg","name":"Lord Tourettes#4139","proxy_icon_url":"https://images-ext-1.discordapp.net/.eJwFwVsSwiAMBdC9sAACJCXQ3Vyh9TFqGaD-OO7dc77m7E-zmtucbaxEpb5tvY9y9IrWbDlehA8m-qDg2Gtk4eijyxJcpgU-bRkJeklFsYfF78KpbqwZKmIf7Wp-f0kZHjQ.nGwQ9M3IO7KVDBKxPuXc7-0mSN0"},"description":"**<@!203176343616094209> was given the `Visual` role**","type":"rich","timestamp":"2016-12-09T19:10:29.757000+00:00"}],"channel_id":"256784001044447232","timestamp":"2016-12-09T19:10:29.892000+00:00"}
[14:10:28] [Warning] [JDASocket]: Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["url"] not found.`

I keep getting this error in my console and I do not know why. This wasn't happening before but it just started to happen last week. I'm using JDA 2.3.0_379

**Comment by DinosParkour** [comment]
JDA 2.X is heavily outdated, please use 3.X.
(We no longer provide support for broken 2.x builds)

**Comment by MinnDevelopment** [comment]
Errors for JDA 2 will no longer be addressed.
Please move over to JDA 3. There is a working audio version available on the audio branch if you don't need audio you can use the development build instead.
