### ISSUE TITLE
Please upload to maven central

### ISSUE THREAD

**Issue by jjYBdx4IL** [DV8FromTheWorld/JDA#208]
The latest artifact at maven central is missing dependencies and seems to be rather old.

**Comment by meowingtwurtle** [comment]
DV8 has switched to Bintray JCenter over Maven Central.

**Comment by jjYBdx4IL** [comment]
never heard of that. there seems to be no native tooling support for that repo. guess I'll have to package stuff for maven central myself then.

**Comment by MinnDevelopment** [comment]
JDA builds are uploaded to http://jcenter.bintray.com
You can find the whole maven info. in any of the recent [releases](https://github.com/DV8FromTheWorld/JDA/releases).

**Comment by DV8FromTheWorld** [comment]
@jjYBdx4IL No native tooling? What do you mean?

**Comment by jjYBdx4IL** [comment]
I'm not going to clutter my dependencies with repository statements, That's very bad practice. If you want people to use JDA, upload it to central.

**Comment by DV8FromTheWorld** [comment]
"Very bad practice". Righto. Your opinion is noted.

**Comment by jjYBdx4IL** [comment]
That's not *my* opinion. And it's not an opinion either. It's just a fact that you don't want to base your projects on random, uncontrollable externals. And if everyone does this, you'll have as many external dependencies as packages. But nvm, I'll do the maven deployment myself then.

**Comment by DV8FromTheWorld** [comment]
JCenter/Bintray is *not* a random, uncontrollable external.
