### ISSUE TITLE
CPU Leak in AudioWebSocket

### ISSUE THREAD

**Issue by TheEpTic** [DV8FromTheWorld/JDA#209]
After successfully setting Lavaplayer on JDA 3.x-AUDIO, I found my CPU usage was stuck around 10% usage after the bot connected. Further testing also found it to stick around after the bot had closed to connection.

I digged in to this with VisualVM and found the thread `pool8-thread1`. I brought it to the guys on Discord and sedmelluq managed to pin it down to https://github.com/DV8FromTheWorld/JDA/blob/a97afac2c0bad4320998caad4f90d5465af62b89/src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java#L93

https://s.eptic.me/92af4fcc512.png - `pool8-thread` starting with other audio threads.
http://i.imgur.com/sjcRhvQ.png - Thread CPU Time
http://i.imgur.com/Q8xyo0Q.png - JVM CPU Usage

http://i.imgur.com/biKjZnH.png - sedmelluq's solution

**Comment by MinnDevelopment** [comment]
In addition:
`KEEP_ALIVE_POOLS.putIfAbsent(api, new ScheduledThreadPoolExecutor(0));`
vs
`KEEP_ALIVE_POOLS.computeIfAbsent(api, jda -> new ScheduledThreadPoolExecutor(1));`

The second statement will instead only create a new thread pool if there is not already one in the map.
The first statement will always create a new pool and only __put__ it in the map if not already in the map.

**Comment by DV8FromTheWorld** [comment]
Should be fixed as of  b6de2f9
