### ISSUE TITLE
getGuildsByName

### ISSUE THREAD

**Issue by Dqmino** [DV8FromTheWorld/JDA#2094]
How do I get a Guild that a JDA Bot (AccountType.CLIENT) is in?
I tried getGuildsByName(guildName, true);
but that returns an empty list.
Im sure the spelling is correct by the way.
And I know that you dont support versions under 4.2.0 (Where you dropped support for AccountType.CLIENT) But please help me with this.

**Comment by MinnDevelopment** [comment]
AccountType.CLIENT is no longer supported *because* it no longer works. We can not, and will not, help with something that is broken and will never be fixed.
