### ISSUE TITLE
ERROR RestAction - RestAction queue returned failure: [ErrorResponseException] 50035: Invalid Form Body

### ISSUE THREAD

**Issue by Zemux1613** [DV8FromTheWorld/JDA#2100]
## General Troubleshooting

- [  ] I have checked for similar issues.
- [  ] I have updated to the [latest JDA version][download].
- [  ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behavior

Get same option as string or as member variable. I test if member is null than its a string and otherwise.

### Code Example or Reproduction Steps

``new OptionData(OptionType.UNKNOWN, "target", "the target user").setRequired(true)``

### Code for JDABuilder or DefaultShardManagerBuilder Used

N/A

### Exception or Error

[ForkJoinPool.commonPool-worker-2] ERROR RestAction - RestAction queue returned failure: [ErrorResponseException] 50035: Invalid Form Body
18.options[0].type
        - BASE_TYPE_CHOICES: Value must be one of (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11).
net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)

**Comment by Andre601** [comment]
This is not a JDA issue. You are using the `UNKNOWN` OptionType, which [as the javadoc mention](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/interactions/commands/OptionType.html#UNKNOWN) is a "placeholder for future option types"

Please use a valid OptionType such as `STRING` or `NUMBER`.

**Comment by MinnDevelopment** [comment]
A better exception for this is provided in [5.0.0-alpha.11](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.11)
