### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by MRDen3000YT** [DV8FromTheWorld/JDA#2103]
Hello! Can I send message from client? Is there any docs for that?

**Comment by MinnDevelopment** [comment]
Refer to the [README](https://github.com/DV8FromTheWorld/JDA#userbots-and-selfbots):

> Discord is currently prohibiting creation and usage of automated client accounts (AccountType.CLIENT). We have officially dropped support for client login as of version 4.2.0! Note that JDA is not a good tool to build a custom discord client as it loads all servers/guilds on startup unlike a client which does this via lazy loading instead. If you need a bot, use a bot account from the [Application Dashboard](https://discord.com/developers/applications).
> 
> [Read More](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-)
