### ISSUE TITLE
JDA 3 RoleManager setColor()

### ISSUE THREAD

**Issue by HeyZeer0** [DV8FromTheWorld/JDA#211]
When you set a role color in .queue() after execution the thread not closes!

http://prntscr.com/diftch
http://prntscr.com/diftfo

JDA 3.0_BETA_105

**Comment by Eufranio** [comment]
Also having this issue, running JDA 3.0_BETA_103. The thread won't close after set the role color.

**Comment by HeyZeer0** [comment]
Ok, i'm trying to make a rainbow tag:
 - r_a variable represents the role.
```
for(Role a : Main.jda.getGuildById("163106828274761728").getRoles()) {
            if(a.getName().equalsIgnoreCase("Admin")) {
                r_a = a;
                break;
            }
 }
```
 - Changing the tag color: 
```
r_a.getManager().setColor(getColor()).queue();
```
- Get color method:
```
    public static Color getColor() {

        if(atual == 0) {
            atual++;
            return Color.BLUE;
        }
        else if(atual == 1) {
            atual++;
            return Color.CYAN;
        }
        else if(atual == 2) {
            atual++;
            return Color.GREEN;
        }
        else if(atual == 3) {
            atual++;
            return Color.MAGENTA;
        }
        else if(atual == 4) {
            atual++;
            return Color.ORANGE;
        }
        else if(atual == 5) {
            atual++;
            return Color.PINK;
        }
        else if(atual == 6) {
            atual++;
            return Color.RED;
        }
        else if(atual == 7) {
            atual = 0;
            return Color.YELLOW;
        }
        return Color.YELLOW;
    }
```
- The color is from java.awt.Color

Every time wich the tag color is changed one thread is started and not finalized.

**Comment by jagrosh** [comment]
Are you making sure that the previous color has been set, and a Role update received, before trying to set the color again?

**Comment by DV8FromTheWorld** [comment]
Forgive me here, but what thread do you think is not being closed?

**Comment by HeyZeer0** [comment]
Every time when you set a role color a new thread is opened and after execution it not closes.

**Comment by TheEpTic** [comment]
@HeyZeer0 You really should look in to switch cases 👀 

As for the thread not closing. Could you provide some solid evidence such as pictures from VisualVM showing the thread being opened and not closed?

**Comment by HeyZeer0** [comment]
Thanks @TheEpTic after using the VisualVM i indentified the error and fixed it, the issue can be closed.
