### ISSUE TITLE
Interact with the voice channel's new text chat

### ISSUE THREAD

**Issue by HagarJNode** [DV8FromTheWorld/JDA#2118]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

It could be very nice to be able to interact with the users in the text chat which is a new feature in Discord. I tried to send some slash commands, but only got class cast exceptions as it says the voice channel isn't a message channel - which is very true.

**Comment by HagarJNode** [comment]
Oh... found the feature/text-in-voice branch - so I'll close this request

**Comment by vico93** [comment]
Any prediction of when this feature will be merged to master?
