### ISSUE TITLE
Add support for text input forms

### ISSUE THREAD

**Issue by DevJoey** [DV8FromTheWorld/JDA#2119]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Discord has released the ability to create text imput forms. It would be nice if JDA will implement that.

**Comment by MinnDevelopment** [comment]
This is already supported since [5.0.0-alpha.11](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.11)

**Comment by DonManfred** [comment]
Isn´t that the implementation of Modals added in Alpha11?

![modals](https://user-images.githubusercontent.com/1331645/166148113-58b6efd1-3e1b-4558-8fc6-34f63eb9615f.png)
