### ISSUE TITLE
More Types of Inputs for "Modals"

### ISSUE THREAD

**Issue by NegativeDev** [DV8FromTheWorld/JDA#2122]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

JDA should have more types of inputs for "Modals". 

I can assume not all of these, if any of these, are actually supported by Discord's API, but if or when they do, I would hope some of these would be added in the future! These may seem to ridiculous to be even considered by discord but oh well, an idea's an idea

## NumberInput
This would only allow numbers. Pretty self explanatory

## SelectBoxInput
This would present a list of boxes of texts, similar to how SelectMenu looks

## FileAttachInput
The ability to attach files, with proper security measures in place would be quite nice for different uses, such as uploading images for a User Report, or a Bug Report, or other things.

## UserSelectInput
Similar to how SelectBotInput would potentially work, but instead of text it would return a list of all users in the discord or users which meet a certain condition

This would be useful for a few cases, such as role assigning bots, report bots, etc

### Example Use-Case

```java
        // Regular Text Inputs
        TextInput suggestion = TextInput.create("suggestion", "Suggestion", TextInputStyle.PARAGRAPH)
                .setPlaceholder("I would like to suggest...").build();

        // Number-only Text Inputs                                               min   max
        NumberInput numberInput = NumberInput.create("numberInput", "Number Input", 0, 100)
                .setPlaceholder("Enter a number between 0 and 100").build();

        // Select Box
        SelectBoxInput selectBoxInput = SelectBoxInput.create("selectBoxInput", "Select Box Input")
                // Can they select multiple options?
                // False by default
                .allowMultiple(true)
                // All the options
                .setOptions("Option 1", "Option 2", "Option 3").build();

        FileAttachmentInput fileAttachmentInput = FileAttachmentInput.create("fileAttachmentInput", "File Attachment Input")
                // What will the text say? Typically, its "Upload a file"
                .setPlaceholder("Upload a file")
                // What filetypes are allowed to be uploaded?
                // All by default
                // Supported filetypes:
                // PNG
                // JPG
                // GIF
                // MP4
                // MP3
                // WAV
                // CUSTOM
                .setFileTypes(FileType.PNG, FileType.MP4, FileType.CUSTOM)
                // How many files can they upload?
                .setLimit(5).build();

        UserSelectInput userSelectInput = UserSelectInput.create("userSelectInput", "User Select Input")
                // Filter the users by default? Only allow users to show up under a condition
                .filter(user -> {
                    // Filer the users you want to show up
                    return user.getName().contains("bob"); // bob
                })
                // Should a little textbox show up to be able to filter by name or id?
                // False by default
                .allowSearch(true).build();
```

**Comment by TopiSenpai** [comment]
Discord does currently not support any other type than `TextInput` see here https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal

**Comment by MinnDevelopment** [comment]
JDA can only support what discord supports. For product feature requests, you can reach out at https://github.com/discord/discord-api-docs/discussions/new?category=api-feature-requests-ideas
