### ISSUE TITLE
When one embed field value is set null it results in an errror

### ISSUE THREAD

**Issue by RealYusufIsmail** [DV8FromTheWorld/JDA#2132]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Not to give an error as both values are marked as Nullable.

This can be shown here
<img width="270" alt="Screenshot 2022-05-16 at 18 17 58" src="https://user-images.githubusercontent.com/67903886/168647856-a648e8c6-9f12-42ca-bbe6-6cb59f96efcb.png">

### Code Example for Reproduction Steps

```java
EmbedBuilder builder = new EmbedBuilder()
                       .addField("one", null)
                       .build();
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
Someone else code
```

### Exception or Error

```yesyes
java.lang.IlligalArgumentException: Both name and value must be set!
```

**Comment by RealYusufIsmail** [comment]
If this error is valid can I make a pr on it.

**Comment by Tais993** [comment]
Both name & value have to be set, or neither

There's no name OR value possible, pretty sure this is intentional

**Comment by RealYusufIsmail** [comment]
Then why are they Nullable

**Comment by RealYusufIsmail** [comment]
If you want have Nullable just have addfield() and addfield(NotNull name, Notnull value)

**Comment by RealYusufIsmail** [comment]
so this problem does not occour.

**Comment by Tais993** [comment]
Read what I said.

Either **BOTH** the name AND value are set

OR

The name and value are NOT set

You CANNOT have the name OR value

**Comment by MinnDevelopment** [comment]
Since this confusion has come up multiple times now, I think we can just make them non-null only. The case of having both null doesn't really do anything in the first place.

**Comment by RealYusufIsmail** [comment]
ok, can i be assigned for this.
