### ISSUE TITLE
[Question] How to edit a Topic for a TextChannel

### ISSUE THREAD

**Issue by stuntguy3000** [DV8FromTheWorld/JDA#214]
As per title, have I missed something?

Thanks.

**Comment by Almighty-Alpaca** [comment]
What do you mean with "exit a topic" ?

**Comment by MinnDevelopment** [comment]
I request an update on this. What do you mean, @stuntguy3000?

**Comment by MinnDevelopment** [comment]
Insufficient information provided.

**Comment by stuntguy3000** [comment]
Apologizes for missing your notification. The correct question is how to **edit** a text channel's topic.

I couldn't find a way to do this in the API.

**Comment by Almighty-Alpaca** [comment]
`TextChannel#getManager() `

**Comment by stuntguy3000** [comment]
Thank you, that solves the issue.
