### ISSUE TITLE
NoClassDefFoundError 

### ISSUE THREAD

**Issue by Gregor7008** [DV8FromTheWorld/JDA#2153]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

on
`JDABuilder.build().awaitReady()`
instanciate the Bot and continue

### Code Example for Reproduction Steps

```java
public Bot(String token) {
  JDABuilder builder = JDABuilder.createDefault(token);
JDA jda = builder.build().awaitReady();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
//See above
```

### Exception or Error

```yesyes
java.lang.NoClassDefFoundError: org/apache/commons/collections4/map/CaseInsensitiveMap
```

**Comment by Gregor7008** [comment]
A little bit more information: Im using 5.0.0-alpha.12. Before I was using alpha.11 and it was working fine. Furthermore, when clicking on the lines of the Error shown to me in EclipseIDE (i.e. JDABuilder.java:1741) it tells me the Javadoc linked it incorrectly. It looks like an error on my end though I couldn't find anything after hour long research.

**Comment by Gregor7008** [comment]
Magically works again, the error seemes to be on my end therefore. I'm going to keep looking, but you keep up the great work!

**Comment by DV8FromTheCode** [comment]
@Gregor7008 Were you able to find out what you did to get it working? I am running into the same thing.

**Comment by Gregor7008** [comment]
@DV8FromTheCode To be honest,I can't even remember in which context this happened. Like sure I updated from v11 to v12, but nothing further than that. But as of the error I would guess that I just tried restarting Eclipse, upgrading to the newest Java version and updating the Maven project with all of its dependencies...
