### ISSUE TITLE
Add to GenericMessageReactionEvent

### ISSUE THREAD

**Issue by supersand24** [DV8FromTheWorld/JDA#2157]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

GenericMessageReactionEvent needs getMessage(), currently event.getMessageId() and event.getMessageIdLong() exitsts.

### Example Use-Case

```java
@Override
public void onGenericMessageReaction(@NotNull GenericMessageReactionEvent event) {
  // What would be nice
  event.getMessage();

  // What it currently is
  event.getThreadChannel().getHistory().getMessageById(event.getMessageId());
}
```

**Comment by Xirado** [comment]
Discord does not provide the whole message object in those types of events.
