### ISSUE TITLE
Timeout Reason

### ISSUE THREAD

**Issue by DxsSucuk** [DV8FromTheWorld/JDA#2175]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

JDA should add the ability of adding a reason to timeouts.

### Example Use-Case

```java
member.timeoutFor("Bad Word", duration)

This could be used for better Audit-Logging, and keeping track of why a Bot would have timeout a Guild Memeber.
```

**Comment by MinnDevelopment** [comment]
You can use [reason(...)](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.html#reason%28java.lang.String%29):

```java
member.timeoutFor(duration).reason("bad word").queue();
```
