### ISSUE TITLE
queue spamming message

### ISSUE THREAD

**Issue by Porama6400** [DV8FromTheWorld/JDA#218]
I use lastest build (109)

This code spamming message
`event.getTextChannel().sendMessage("MESSAGE").queue();`

**Comment by DV8FromTheWorld** [comment]
Not an error. Most likely you are responding to your own messages..

**Comment by Porama6400** [comment]
Oops , look like it's true

**Comment by Porama6400** [comment]
How can I check if that message is message that bot send?

**Comment by Porama6400** [comment]
Oh , found it
