### ISSUE TITLE
add guild create in event

### ISSUE THREAD

**Issue by robalmeister** [DV8FromTheWorld/JDA#2214]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Hello, I want to create events in guilds in jda (the channel is selected and ss is shown at the top: https://squadguide.net/wp-content/uploads/2022/01/1643047214_663_So-erstellen-Sie-Events- auf-Discord-und-nehmen-daran-teil.png) maybe api discord is missing or I'm looking for it wrong. Regards

**Comment by OcelusPRO** [comment]
The only use case of your request is when the bot itself creates a server, it doesn't seem to me that discord sends an event when this happens (outside the GuildJoinEvent)

If you need guild creation, you can, during the guildJoinEvent, check if the bot is the owner of the server (which would indicate that the newly joined server is the one you just created)

**Comment by MinnDevelopment** [comment]
There is an open pull request for this: #2047

**Comment by robalmeister** [comment]
but I can't see the latest version

**Comment by DonManfred** [comment]
It isn´t released in the Alpha as of now.
We have to wait for #2047 to be included in JDA.
