### ISSUE TITLE
Add Category#createNewsChannel

### ISSUE THREAD

**Issue by freya022** [DV8FromTheWorld/JDA#2216]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

JDA should have a `createNewsChannel` method in `Category`, similar to `Category#createTextChannel`

### Example Use-Case

```java
category.createNewsChannel("announcements").queue();
```

**Comment by MinnDevelopment** [comment]
Handled by #2184

**Comment by MinnDevelopment** [comment]
Available in [5.0.0-alpha.19](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.20)
