### ISSUE TITLE
Message components cloning bug

### ISSUE THREAD

**Issue by Xlkki** [DV8FromTheWorld/JDA#2234]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I have a message generated using <b>MessageCreateBuilder</b> with components. They should be disabled depending on a number of conditions, but in order to keep these components unchanged in the original message, I create a copy of it using the <code>MessageCreateBuilder.from(original)</code> method. I get a builder with a duplicate of the original message, which I can modify for my needs, but the components of this builder and the original message are linked, and if I change them in the copy using the <code>LayoutComponent.updateComponent(copy.getComponents(), someId, newComponent)</code> method, it will also change in the original message.

I showed an example of this in the screenshot. 
![image](https://user-images.githubusercontent.com/91030266/187877224-08e6114c-99b6-4373-80ab-31beb4f35774.png)

I created a message with a button and sent it. Then I created a copy of this message, replaced the button with its disabled copy, and sent it. After all that, I sent the original message again, but it also replaced the button with a disabled copy

### Code Example for Reproduction Steps

```java
public void someMethod(JDA jda, TextChannel channel) {
        Button originalButton = Button.of(ButtonStyle.SECONDARY, "some-button", "Test");
        MessageCreateData original = new MessageCreateBuilder()
                .setContent("Original message")
                .setActionRow(originalButton)
                .build();

        channel.sendMessage(original).queue();

        MessageCreateData copy = MessageCreateBuilder.from(original).setContent("Copied message").build();
        LayoutComponent.updateComponent(copy.getComponents(), "some-button", originalButton.asDisabled());

        channel.sendMessage(copy).queue();        
        channel.sendMessage(original).queue();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault("some-token");
```

**Comment by MinnDevelopment** [comment]
Fixed in [5.0.0-beta.1](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-beta.1)
