### ISSUE TITLE
AFK Event 

### ISSUE THREAD

**Issue by michel929** [DV8FromTheWorld/JDA#2257]
### General Troubleshooting

- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.
- [X] I have checked for similar issues on the Issue-tracker.

### Feature Request

The event is executed when a user changes to the AFK status, but this does not mean the absent status, but the status when you are moved to the AFK channel.

### Example Use-Case

```java
public class PlayerAFk extends ListenerAdapter {
 public void PlayerAFKEvent(PlayerIsAFK event){
    Member m = event.getMember();
 }
}
```

**Comment by DenuxPlays** [comment]
Is this really neccessary?
I mean you can just check on the guildVoiceJoinEvent if the channel the member joined is the afk channel of the guild.
I think that would work why need an extra event for it?

**Comment by MinnDevelopment** [comment]
I agree, this can already be achieved by a simple `if (channel.equals(guild.getAfkChannel()))`
