### ISSUE TITLE
[Help Wanted] Private Messages

### ISSUE THREAD

**Issue by CalebBassham** [DV8FromTheWorld/JDA#227]
I was wondering if there is a way you can do something like this where only one person can see it but it does not go to their dm and says *Only you can see this.*

![imgur](http://i.imgur.com/ADRbSCr.png) 

---

Also I have tried to send direct messages but I always have an error because a private channel is not open. Is this not how you would open a private channel.

```
if(!e.getAuthor().hasPrivateChannel())
            e.getAuthor().openPrivateChannel().queue();
e.getAuthor().getPrivateChannel().sendMessage("Test").queue();
```

Note: `e ` is a `MessageRecievedEvent`

**Comment by DinosParkour** [comment]
Since you queue() the RestAction, it gets executed asynchronously.
You should move the message sending logic in the success callback instead.

Also, to answer your original question, no, you cannot send "messages" like Clyde.

**Comment by CalebBassham** [comment]
Thanks

**Comment by CalebBassham** [comment]
@DinosParkour I have tried to do that but I must have done something wrong. Is this incorrect?

```
if (!e.getAuthor().hasPrivateChannel())
            e.getAuthor().openPrivateChannel().queue(
                    success -> {
                        e.getAuthor().getPrivateChannel().sendMessage(sb.toString()).queue();
                        e.getChannel().sendMessage(e.getAuthor().getAsMention() + "Check your direct messages.").queue();
                    }
            );
```

**Comment by CalebBassham** [comment]
Never mind I got it working. Sorry!
