### ISSUE TITLE
ChannelCreateEvent fires twice for forum posts under certain circumstances

### ISSUE THREAD

**Issue by tonTeufel** [DV8FromTheWorld/JDA#2275]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

JDA should not execute onChannelCreate again when use it to send a message to a new forum post.
JDA executes onChannelCreate as expected (aka once per new channel created) if I remove the code inside the if clause that sends a message to the new forum post.

### Code Example for Reproduction Steps

```java
@Override
public void onChannelCreate(ChannelCreateEvent event) {
        try {
            if (event.getChannel().asThreadChannel().getParentChannel().asForumChannel()
                    .getIdLong() == suggestionForumID) {
                event.getChannel().asThreadChannel().sendMessage(MessageCreateData
                        .fromEmbeds(new EmbedBuilder().setTitle("Poll⠀⠀⠀⠀").setColor(10181046).build()))
                        .queue((message) -> {
                            message.addReaction(Emoji.fromUnicode("👍")).queue();
                            message.addReaction(Emoji.fromUnicode("👎")).queue();
                        });

            }
        } catch (IllegalStateException e) {
        }
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder.createDefault(passwords.getString("DiscordBotToken"), GatewayIntent.GUILD_BANS, GatewayIntent.GUILD_EMOJIS_AND_STICKERS, GatewayIntent.GUILD_MESSAGE_REACTIONS)
                        .disableCache(CacheFlag.VOICE_STATE)
                .addEventListeners(new SuggestionsPoll(config.getLong("SuggestionsForum")))
                .build().awaitReady();
```

### Exception or Error

```yesyes
N/A
```

**Comment by MinnDevelopment** [comment]
This should already be resolved by #2254 which is going to be in the next release.
