### ISSUE TITLE
Add support for the new select menu types

### ISSUE THREAD

**Issue by seailz** [DV8FromTheWorld/JDA#2280]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Discord have just released new select menu types, role select, user select, channel select, & mentionable select. These would be wonderful additions to JDA.

### Example Use-Case

```java
UserSelectMenu userSelect = …;
RoleSelectMenu roleSelect = …;
MentionableSelectMenu mentionableSelect = …;
ChannelSelectMenu channelSelect = …;
```

**Comment by seailz** [comment]
I will probably open a PR for this shortly.

**Comment by Eronary** [comment]
![image](https://user-images.githubusercontent.com/63160741/196030309-0466b654-5315-4c2f-87d8-3799a568554a.png)
Even without processing the event, I get this error when the user selects the user
