### ISSUE TITLE
Empty MessageEditBuilder#setActionRow() causes problems - #complete()/#queue() is never completed

### ISSUE THREAD

**Issue by lilmayu** [DV8FromTheWorld/JDA#2298]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I am using version v5.0.0-alpha.21

JDA should update the message without any components (essentially removing them) and not deadlock.

There is also more weird behavior described in the code example. I'll attach the 3 videos mentioned here.

Video 1
https://user-images.githubusercontent.com/52459400/197400468-d9c7cb6a-dde7-44b2-9482-8ff6c73c0938.mp4

Video 2
https://user-images.githubusercontent.com/52459400/197400528-1cdf1038-5bb3-4e30-9520-addffc6fff16.mp4

Video 3
https://user-images.githubusercontent.com/52459400/197400548-0b81655b-bd64-4e24-8f28-6b2105774248.mp4

### Code Example for Reproduction Steps

```java
@Override
public void onSelectMenuInteraction(SelectMenuInteractionEvent event) {
    SelectMenu selectMenu = event.getSelectMenu();

    // Responds to only select menus with ID "test"
    if (selectMenu.getId().equals("test")) {
        event.deferEdit().queue(hook -> { // Acknowledges just fine (hence the 3 dots goes away in videos)
            MessageEditBuilder builder = new MessageEditBuilder();

            builder.setContent("This message should **not** have any action components.");
            builder.setActionRow(); // Empty -> Causes #queue()/#complete() to never finish (Video 1)
            // If I comment out the #setActionRow(), #queue() is returned but the components on original message are present (Video 2)
            // Also, if there's #complete() on the #editOriginal() even with commented out #setActionRow(), it never finishes as well. (Video 3, basically the same as Video 1)
            // If there are components passed into the #setActionRow(), everything works as intended

            hook.editOriginal(builder.build()).queue(); // Or #complete()
        });

        return;
    }

    // Responds to any other select menus
    event.deferReply(true).queue(hook -> {
        MessageEditBuilder builder = new MessageEditBuilder();

        builder.setContent("Replied to SelectMenu event. This message will have another SelectMenu.");
        builder.setActionRow(SelectMenu.create("test").addOption("Label", "value").build());

        hook.editOriginal(builder.build()).queue();
    });
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
var builder = DefaultShardManagerBuilder.createLight("token")
                                        .setShardsTotal(10)
                                        .addEventListeners(new SelectMenuListener());
```

### Exception or Error

```yesyes
N/A - And this may be also a bug, there are no exceptions thrown.
```

**Comment by lilmayu** [comment]
Also, from my testing, `interactionHook.editOriginalComponents().complete();` (or `#queue()`) also deadlocks.

**Comment by MinnDevelopment** [comment]
It isn't a deadlock, it throws an exception because an empty action row is not allowed. You are likely looking for `setComponents` instead.

I recommend fixing your logging setup to properly show errors when JDA catches and logs them. Using complete() in a RestAction callback is also not allowed and throws an exception, again something JDA also logs.
