### ISSUE TITLE
Documentation outdated, how do you send audio

### ISSUE THREAD

**Issue by stuntguy3000** [DV8FromTheWorld/JDA#230]
![image](https://cloud.githubusercontent.com/assets/1522389/21758074/cbe6cae6-d687-11e6-829b-101b74299cc0.png)

So it appears that URLPlayer is nonexistant. Can the docs be updated, and what is the _new_ method of doing this?

**Comment by MinnDevelopment** [comment]
The documentation has not been finished for the current JDA version.
It is a work in progress on the `javadoc` branch (see #206 )

For players in JDA:
We removed the `URLPlayer` and `FilePlayer` after they have been deprecated for a long time in favor of [JDA-Player](https://github.com/DV8FromTheWorld/JDA-Player). However this has been deprecated in favor of [LavaPlayer](https://github.com/sedmelluq/lavaplayer) which you can now use for your audio player needs.

For a JDA demo in `LavaPlayer` see this [package](https://github.com/sedmelluq/lavaplayer/tree/master/demo-jda)

**Comment by stuntguy3000** [comment]
Looks like a good API, cheers mate.
