### ISSUE TITLE
`application_id` support for received webhook messages?

### ISSUE THREAD

**Issue by KJP12** [DV8FromTheWorld/JDA#2311]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

For received messages emitted by webhooks, the ability to retrieve the `application_id` for telling which bot sent the message without looking up webhooks.

This would be useful in cases where you're wanting to use another bot's API, such as [PluralKit's](https://pluralkit.me/api/), and want to limit API requests to only deletions after a webhook by the bot emits a message within the channel.

This can also be helpful for cases where you need to lookup the bot where possible without having appropriate permissions to look up the webhook directly.

It's notable that very old bots have a split on application vs. 'user' ID, so, a user lookup cannot be guaranteed. Applications can also create a webhook without having a user attached, which may also lead to another failed user lookup. This isn't really significant if all you need is the ID to compare with, but it should be noted for implementing.

### Example Use-Case

```java
class Example {
    public void onReceiveMessage(Message msg) {
        if (isModLogEnabled(msg.getGuild())) {
            msgCache.put(msg.getIdLong(), msg);
            // Assuming that Application ID is already implemented:
            if (msg.isWebhookMessage() && msg.getApplicationIdLong() == 466378653216014359L) {
                pkCache.put(m.getGuildChannel().getIdLong(), m.getIdLong());
            }
        }
    }

    public void onDeleteMessage(long id) {
        var msg = msgCache.get(id);
        if(id >= timeFilter() && pkCache.get(msg.getChannel().getIdLong()) >= timeFilter()) {
             // Query PK's API & log accordingly or not log at all.
        } else {
             // Standard logging.
        }
    }
}
```

**Comment by MinnDevelopment** [comment]
This is available in [5.0.0-beta.1](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-beta.1)
