### ISSUE TITLE
`GuildSticker.retrieveOwner().complete()` is returns null

### ISSUE THREAD

**Issue by book000** [DV8FromTheWorld/JDA#2315]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I wanted to listen for `GuildStickerAddedEvent` and get the owner of the created Sticker.

Executing `GuildStickerAddedEvent.getSticker().retrieveOwner().complete()` returns `null`.
This null is not expected as long as it is obtained by retrieveOwner.
The same is true when using `useCache(false)`.

It will not be `null` if the owner is obtained from a `GuildSticker` obtained with `Guild.retrieveSticker()`.

- The bot has been given administrative privileges.
- Using JDA [5.0.0-alpha.22](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.22)

### Code Example for Reproduction Steps

```java
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.events.sticker.GuildStickerAddedEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public class StickerListener extends ListenerAdapter {
    @Override
    public void onGuildStickerAdded(@NotNull GuildStickerAddedEvent event) {
        System.out.println("onGuildStickerAdded() called");
        System.out.println("| getSticker().getName(): " + event.getSticker().getName());
        System.out.println("| getSticker().getId(): " + event.getSticker().getId());
        System.out.println("| getSticker().getOwner(): " + getHumanReadableTag(event.getSticker().getOwner()));
        System.out.println("| getSticker().retrieveOwner(): " + getHumanReadableTag(event.getSticker().retrieveOwner().complete()));
        System.out.println("| getSticker().retrieveOwner() [useCache(false)]: " + getHumanReadableTag(event.getSticker().retrieveOwner().useCache(false).complete()));
        /*
        onGuildStickerAdded() called
        | getSticker().getName(): test
        | getSticker().getId(): 1035618675757166692
        | getSticker().getOwner(): null
        | getSticker().retrieveOwner(): null
        | getSticker().retrieveOwner() [useCache(false)]: null
         */

        GuildSticker sticker = event.getGuild().retrieveSticker(StickerSnowflake.fromId(event.getSticker().getId())).complete();
        System.out.println("| getGuild().retrieveSticker().getOwner(): " + getHumanReadableTag(sticker.getOwner()));
        /*
        | getGuild().retrieveSticker().getOwner(): tomachi#0310
         */
    }

    public String getHumanReadableTag(@Nullable User user) {
        if (user == null) {
            return "null";
        }
        return user.getAsTag();
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
String token = "XXXXXXXXXXXXXXXXXXX";

JDABuilder.createDefault(token)
        .enableIntents(GatewayIntent.GUILD_EMOJIS_AND_STICKERS)
        .setAutoReconnect(true)
        .setBulkDeleteSplittingEnabled(false)
        .setContextEnabled(false)
        .addEventListeners(new StickerListener())
        .build()
        .awaitReady();
```

### Exception or Error

`GuildStickerAddedEvent.getSticker().retrieveOwner().complete()` is expected to return information about the user who created the Sticker, but actually returns `null`.

**Comment by MinnDevelopment** [comment]
Looks like this is a discord bug, the API doesn't seem to return user information for [the get sticker endpoint](https://discord.com/developers/docs/resources/sticker#get-guild-sticker). You can use [Guild#retrieveStickers](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/Guild.html#retrieveStickers()) instead.

Strangely enough, this works fine for [Get Emoji](https://discord.com/developers/docs/resources/emoji#get-guild-emoji).

If this is not fixed by discord, we will likely have to remove the method.

**Comment by book000** [comment]
Thanks for the quick reply.

I understand that the problem is on the Discord side. I will use `Guild#retrieveStickers` for now.

**Comment by MinnDevelopment** [comment]
Nevermind, this is actually an issue with JDA since we use the wrong endpoint. I'll follow up with a fix in a PR in a moment.
