### ISSUE TITLE
RuleScreen Accept Event

### ISSUE THREAD

**Issue by michel929** [DV8FromTheWorld/JDA#2331]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

A new event that is triggered when a user clicks accept on the rule screen...

### Example Use-Case

```java
@Override
public void onMemberAcceptRules(AcceptRulesEvent event){
    Member m = event.getMember();
    
}
```

**Comment by MinnDevelopment** [comment]
This already exists via the [GuildMemberUpdatePendingEvent](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdatePendingEvent.html).
