### ISSUE TITLE
java.lang.ClassNotFoundException: net.dv8tion.jda.api.hooks.ListenerAdapter

### ISSUE THREAD

**Issue by nahlebalnik** [DV8FromTheWorld/JDA#2354]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

should work

### Code Example for Reproduction Steps

```java
i dont know
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
client = JDABuilder.createDefault(token)
                .addEventListeners(this)
                .enableIntents(GatewayIntent.MESSAGE_CONTENT)
                .build();
```

### Exception or Error

```yesyes
java.lang.ClassNotFoundException: net.dv8tion.jda.api.hooks.ListenerAdapter
```

**Comment by Xirado** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of the [discord server](https://discord.gg/jda).
