### ISSUE TITLE
MarkdownSanitizer escaping incorrectly

### ISSUE THREAD

**Issue by realSurfy** [DV8FromTheWorld/JDA#2358]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

This text is supposed to be escaped from:
```
. 
    > TEST
``` 
to:
```
. 
    \> TEST
``` 

However, this does not happen.

As shown:
![image](https://user-images.githubusercontent.com/39742246/209409059-a0e93057-8b21-4d68-9c72-ae7b732f5da4.png)

Debug:
![image](https://user-images.githubusercontent.com/39742246/209409106-f29b5abb-bfcb-4c5f-bdfe-510ed00d0d5c.png)

### Code Example for Reproduction Steps

```java
String escapedText = MarkdownSanitizer.escape(". \n    > TEST");
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
Irrelevant
```

**Comment by MinnDevelopment** [comment]
Fixed in 5.0.0-beta.10
