### ISSUE TITLE
Restart JDA instance via method call

### ISSUE THREAD

**Issue by Proviant** [DV8FromTheWorld/JDA#2361]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

There is currently no way to restart an instance of one's JDA in Java itself. One has to resort to exitting the whole program, before the app can start up once again.

I saw that there was a branch open for the restart, but it hasn't been touched in a while. This feature would benefit in the sense that restarting the JDA instance in Java itself wouldn't stop other f. ex. ScheduledExecutorServices from shutting down and also would serve as a helping method for debugging, when the bot f. ex. loses connection to the server.

I, for example, would love to have a restart, so I can debug some rare errors that occur, once my bot loses connection and somehow screws up my ScheduledExecutorServices from no longer continuing on.

### Example Use-Case

```java
@Override
public void onMessageReceived(MessageReceivedEvent event)
{
    if (event.getMessage().getContentRaw().equalsIgnoreCase("restart")) {
        // A restart request could be an asynchronous call
        event.getJDA().restart().queue();
    }
}
```

**Comment by MinnDevelopment** [comment]
You can restart by using `JDA#shutdown` followed by just building a new instance. For example:

```java
public JDA start() {
  return JDABuilder.createDefault(...)
     .setGatewayPool(gwPool)
     .setRateLimitPool(restPool)
     .build();
}

public JDA restart(JDA jda) {
  jda.shutdown();
  return start();
}
```

By using the setters for pools, they will not be shutdown. You do not have to shut down the entire JVM for this at all.

If you want to debug connection issues, I recommend actually specifically disconnecting the parts you are interested in. This can be done by casting to `JDAImpl` and then manually disconnecting the websocket client, a restart method would not do this isolated restart. A full restart would also result in cache invalidation, which is likely not what you want.

For example, restarting with session resume:

```java
((JDAImpl) jda).getClient().close(1006);
```

Alternatively, if you really do want to full reconnect and invalidate cache:

```java
((JDAImpl) jda).getClient().close(1000);
```

**Comment by Proviant** [comment]
Oh, that should do it! Thank you very much =) The cache invalidation is indeed not wanted, so your solution fits perfectly into what I was looking for. For me this issue is resolved. ^^
