### ISSUE TITLE
UserUpdateTag ...

### ISSUE THREAD

**Issue by michel929** [DV8FromTheWorld/JDA#2365]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

An event that is executed when the user changes their tag. The tag means everything after the #. I know there is the GenericUserEvent but it is executed with every little thing yk...

### Example Use-Case

```java
public void onUserUpdateTag(UpdateUserTag event) {
}
```

**Comment by Andre601** [comment]
Tag is actually the full `username#1234`, not just the 4-digit number. That one is the discriminator.

And such an event already exists: [`UserUpdateDiscriminatorEvent`](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateDiscriminatorEvent.java)

**Comment by michel929** [comment]
Ohh ok thx sorry mb
