### ISSUE TITLE
More Modal ActionRow Components... something like a simple text

### ISSUE THREAD

**Issue by michel929** [DV8FromTheWorld/JDA#2368]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

So with more components I don't mean for example DropDown but simply text that is displayed and you can edit the buttons of the modal... That you can for example call a modal, read the text and then accept or reject with a button.

### Example Use-Case

```java
SimplyText text = SimplyText.create("<id>", "<text>").build();

Modal modal = Modal.create("<id>", "<title>")
              .addActionRows(ActionRow.of(text))
              .setModalButtons(Button.danger("<id>", "Reject")Button.success("<id>", "Accept"))
              .build();
```

**Comment by Andre601** [comment]
JDA can't just add own custom components.
It is handled and offered by Discord and therefore not customizable.

**Comment by michel929** [comment]
Hm ok i understand ... :(
