### ISSUE TITLE
Error when enabling JDA bot

### ISSUE THREAD

**Issue by AvalancheYT** [DV8FromTheWorld/JDA#238]
I am having an issue when I am enabling it.
http://pastebin.com/StinMeff
Version: 3.0.BETA_108

**Comment by DinosParkour** [comment]
First of all, you're using quite an outdated version so please update to latest dev build.

Also, something must've gone wrong while building the jarfile (exporting/gradle/..) so you should look into that and make sure you include all dependencies as needed.

**Comment by DV8FromTheWorld** [comment]
Update to a version of JDA in BETA2. Additionally, like Dinos said, you seem to be missing files. Seems like you haven't bundled JDA inside your plugin, thus it can't find JDA's files.

**Comment by AvalancheYT** [comment]
I am using BETA2, I forgot to add 2 to my version before posting this. I will try recompiling it.

**Comment by MinnDevelopment** [comment]
As this hasn't been updated for more than 2 weeks I will close this for now.
In case this is still an issue you can re-open with more information and steps of reproduction.

**Comment by AvalancheYT** [comment]
I forgot to mention that the older version of JDA was working and I started to update it, it keeps telling me this error
