### ISSUE TITLE
Additional SlashCommand support

### ISSUE THREAD

**Issue by RockinChaos** [DV8FromTheWorld/JDA#2383]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

I have been playing around with the new #setNSFW(bool) option for slash commands and it works great, however, it would be amazing if either this option could support or if you could add a different option to support Private channels. This way NSFW commands would work in Explicit channels and direct messages only. Bonus points if there could be a way to respect the Safe Direct Messaging filter for the user but I am unsure if this is available through Discord's API.

There are some benefits from making commands only work in direct messages so something like #setPrivate(bool) may be the better option here.

### Example Use-Case

```java
// Examples;
Commands.slash("nsfw", "Something nsfw").setNSFW(true); //- Works only in explicit guild channels.
Commands.slash("private", "Something private").setPrivate(true); //- Works only in direct messages.

//Or make it so both are supported.
Commands.slash("nsfw", "Something nsfw").setNSFW(true); //- Works in both explicit channels and direct messages.
```

**Comment by freya022** [comment]
JDA cannot implement features that Discord does not provide

DM-only commands do not exist in Discord

**Comment by RockinChaos** [comment]
> JDA cannot implement features that Discord does not provide
> 
> DM-only commands do not exist in Discord

Correct but explicit through DM's does exist according to Discord.

Apparently, I missed it, there is simply a toggle I missed to enable the commands in DM's `User Settings > Privacy > Server Privacy Defaults > Allow access to age-restricted commands from apps in Direct Messages`
