### ISSUE TITLE
Add role to user

### ISSUE THREAD

**Issue by ItsMas** [DV8FromTheWorld/JDA#239]
I can't find anywhere how I would add a Role to a User/Member.

I saw somewhere there was a GuildManager#addRoleToUser method however this method does not seem to exist.

Any help would be appreciated.

**Comment by DinosParkour** [comment]
http://ci.dv8tion.net/job/JDA/lastCompletedBuild/javadoc/net/dv8tion/jda/core/managers/GuildController.html

**Comment by MinnDevelopment** [comment]
You can manage the roles of a Member in JDA 3.x using the `GuildController`.
Back in older JDA versions you were able to use the `GuildManager#addRoleToUser` method, however with JDA 3 we moved these to the `GuildController`.

**Comment by ItsMas** [comment]
Thanks!
