### ISSUE TITLE
Add a way to get the original message in a reply

### ISSUE THREAD

**Issue by diamkil** [DV8FromTheWorld/JDA#2395]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Currently you can get a message with the type "INLINE_REPLY" however there is no way to get the message to which it is replying to. I'm making a ticket system that archives the channel when it gets closed and I can't get the original message to display replies properly

### Example Use-Case

```java
public Message getOriginalMessage(Message message) {
  if (message.getType().equals(MessageType.INLINE_REPLY)) {
    return message.getReplyTo(); //dunno how it could be named
  else {
    return null;
  }
}
```

**Comment by MinnDevelopment** [comment]
This exists via [Message#getMessageReference](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/Message.html#getMessageReference()). You sometimes get lucky and can use [MessageReference#getMessage](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/MessageReference.html#getMessage()) directly, but other times you have to use [MessageReference#resolve](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/MessageReference.html#resolve()) instead.
