### ISSUE TITLE
Message#getMentions().getMembersBag() doesn't include reply-mentions

### ISSUE THREAD

**Issue by Andre601** [DV8FromTheWorld/JDA#2408]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

`Messages#getMentions().getMembersBag()` should include the replied user of the message if it tags them.

Instead is the Bag not containing the user from any tagged reply.

Output with below code example:
![grafik](https://user-images.githubusercontent.com/11576465/220352053-c58cde7d-4fec-42ea-9183-3a061067bf63.png)

Tested with JDA 5.0.0-beta.4

### Code Example for Reproduction Steps

```java
@Override
public void onMessageReceived(MessageReceivedEvent event) {
    if(!message.isFromGuild() || event.getAuthor().isBot())
        return;

    Bag<Member> membersBag = event.getMessage().getMentions().getMembersBag();
    List<Member> membersList = event.getMessage.getMentions().getMembers();
    
    StringJoiner bagJoiner = new StringJoiner(", ");
    StringJoiner listJoiner = new StringJoiner(", ");

    for(Member member : membersBag) {
        bagJoiner.add(member.getAsMention());
    }
    
    for(Member member : membersList) {
        listJoiner.add(member.getAsMention());
    }
    
    TextChannel tc = event.getMessage().getChannel().asTextChannel();
    
    tc.sendMessage("Mentioned Members (Bag): " + bagJoiner).queue();
    tc.sendMessage("Mentioned Members (List): " + listJoiner).queue();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
ShardManager shardManager = DefaultShardManager.createDefault("S3cr3t.T0k3n")
    .disableIntents(GatewayIntent.GUILD_VOICE_STATES)
    .enableIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntents.GUILD_MESSAGES, GatewayIntents.MESSAGE_CONTENT)
    .disableCache(CacheFlag.VOICE_STATE)
    .addEventListeners(new CommandListener(this)) // Class with the MessageReceivedEvent
    .build();
```

**Comment by MinnDevelopment** [comment]
Completed in [5.0.0-beta.6](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-beta.6)
