### ISSUE TITLE
Add reactions to messages.

### ISSUE THREAD

**Issue by P42C41** [DV8FromTheWorld/JDA#241]
Hello,

i'm currently working on a Selfbot and i try to add reactions to messages with it.

what i tried so far:

> event.getChannel().getHistory().retrievePast(5).queue(success -> {
					List<Message> list = success.stream().filter(m -> !event.getMessage().equals(m))
							.collect(Collectors.toList());
					list.forEach(m -> {
						m.addReaction(event.getGuild().getEmoteById("249244327572668416"));
					});
					tempReply("Spamming reactions...", event);
				});

event = MessageReceivedEvent but it don't add any reaction to the past 5 messages (The Emote ID is valid on the server i tried it)

**Comment by DinosParkour** [comment]
[addReaction is a Rest Action](http://home.dv8tion.net:8080/job/JDA/lastCompletedBuild/javadoc/net/dv8tion/jda/core/entities/Message.html#addReaction-net.dv8tion.jda.core.entities.Emote-), so you should treat it like you do with message sending etc (queue(), compete(), submit())

**Comment by P42C41** [comment]
Thanks!

**Comment by P42C41** [comment]
@DinosParkour Another question, how do i get the emote id's of the normal emojis ? Like for example :regional_indicator_j:

**Comment by DinosParkour** [comment]
@p42c41 use an external library to get the Unicode char from the emojis name (re: emoji vs emote: emoji is Unicode, emote is discord/jda object)
