### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by Spark61** [DV8FromTheWorld/JDA#2423]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

I would like to request a new feature that allows us to store cached member/user/guild/... on external providers like Redis. Currently, these caches are stored in memory, which can be a challenge for larger servers or applications with a high number of users and data.

**Comment by MinnDevelopment** [comment]
We currently have no plans to rewrite the internal cache components.
