### ISSUE TITLE
ID may not be null but isnt

### ISSUE THREAD

**Issue by CrackedJustin0** [DV8FromTheWorld/JDA#2426]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Should run without Error. The ID isnt null and it shows clearly on the Console Output that i get the Member susscessfully and the ID also. The Console Output is visible in the Error Pastebin

### Code Example for Reproduction Steps

```java
TextChannelManager textChannelManager = textChannel.getManager();
                        textChannelManager.putPermissionOverride(Main.guild.getRoleById("874414554006831125"), 0L,Permission.VIEW_CHANNEL.getRawValue());
                        textChannelManager.putPermissionOverride(Main.guild.retrieveMemberById(resultSet.getString("discordID")).complete(),Permission.VIEW_CHANNEL.getRawValue(), 0L);
                        textChannelManager.queue();
                        System.out.println(resultSet.getString("discordID"));
                        System.out.println(Main.guild.retrieveMemberById(resultSet.getString("discordID")).complete());
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault("TOKEN");
        builder.setActivity(Activity.playing(" auf CraftingEmpire.de"));
        builder.addEventListeners();
        builder.enableCache(VOICE_STATE);
        try {
            jda = builder.build().awaitReady();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
```

### Exception or Error

```yesyes
https://pastebin.com/RKeR0aqb
```

**Comment by MinnDevelopment** [comment]
The error says that the ID is null in line `DiscordManager.java:44`. There is nothing we can help you with, this is something you'll have to debug on your own. I can only tell you that you passed null to that method.
