### ISSUE TITLE
StringSelectionMenus in Modals

### ISSUE THREAD

**Issue by JxstColin** [DV8FromTheWorld/JDA#2433]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Hey. I guess it will be very nice, if you can add StringSelectionMenus in Modals. I very need it for my Bot, and I would love to see this feature developed soon.

**Comment by MinnDevelopment** [comment]
Duplicate of #2161
