### ISSUE TITLE
Strange behaviour when setting roles

### ISSUE THREAD

**Issue by Akio08** [DV8FromTheWorld/JDA#244]
Hello,

Today I have a really strange problem. 

```java
RoleManager rm = new RoleManager(this.getMember());
rm.remove(this.vRole);

rm = new RoleManager(this.getMember());
for(JRole r : this.getGuild().getRoles().values()){
   if(r.isMuteRole()){
      rm.add(r.getRole());
   }
}
```

My RoleManager.java

```java
public class RoleManager {

    private Member member;
    private GuildController gc;

    public RoleManager(Member member){
        this.member = member;
        this.gc = new GuildController(this.member.getGuild());
    }

    public boolean remove(Collection<Role> r){
        this.gc.removeRolesFromMember(this.member, r).queue();
        return true;
    }

    public boolean add(Collection<Role> r){
        this.gc.addRolesToMember(this.member, r).complete();
        return true;
    }

    public boolean remove(Role r){
        this.gc.removeRolesFromMember(this.member, r).queue();
        return true;
    }

    public boolean add(Role r){
        this.gc.addRolesToMember(this.member, r).complete();
        return true;
    }

}
```

When java run `rm.remove(this.vRole);` all the role is removed (all user actual roles). This is okay. But when I add **one** role (any role), the user have the roles that was removed AND the new role...

Why ?

**Comment by MinnDevelopment** [comment]
@Akio08 Are you possibly doing both remove and add in one event loop iteration, meaning in one listener call?
Like 
```java
rm.remove(this.vRole());
rm.add(someOtherRole);
```

**Comment by Akio08** [comment]
Here is how my code work

1 ) When MessageReceivedEvent is called, and if the message start with "!", then this is a command.

2 ) My command was a `!mute` (so I want to put my user in a role only)

3 ) I'm saving all role in `this.vRole`

4 ) I call `rm.remove(this.vRole)`. All the role from user are deleted.

5 ) Then , I call the `rm.add(muteRole)` to mute my user. But it adds muteRole AND this.vRole list.

So yes, this can be considered like" one listener call" I think.

**Comment by MinnDevelopment** [comment]
You should consider using `GuildController#modifyMemberRoles(Member, Role...)` instead.
It will override the roles of the specified member only leaving the roles you specify
Example: `gc.modifyMemberRoles(Member, muteRole).queue()`

**Comment by Akio08** [comment]
Hello, 

Thanks, `GuildController#modifyMemberRoles(Memer, Role...)` is working fine !
