### ISSUE TITLE
setSuppressedNotifications() does not work for deferred replies.

### ISSUE THREAD

**Issue by Gamebuster19901** [DV8FromTheWorld/JDA#2461]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Calling 
```java
iReplyCallback.deferReply().setSuppressedNotifications(true).queue(); //where iReplyCallback is a net.dv8tion.jda.api.interactions.callbacks.IReplyCallback
```

should send a deferred reply that is silent. What actually happens is that the `<bot> is thinking...` message that appears is not silent. There also does not appear to be any method to send a silent deferred reply in IReplyCallback, like you can with ephemeral replies.

![image](https://user-images.githubusercontent.com/7155747/236025419-9a3d68c9-8eb3-42e3-a424-9eba9f42ae0e.png)

### Code Example for Reproduction Steps

```java
iReplyCallback.deferReply().setSuppressedNotifications(true).queue();


//full code used is here: https://github.com/Gamebuster19901/Roll/blob/7a2112f8a1d43fb7276aa3b4640137abe40b5050/src/main/java/com/gamebuster19901/roll/bot/command/DebugCommand.java#LL16C1-L36C5
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
private static final List<GatewayIntent> GATEWAYS = Arrays.asList(new GatewayIntent[] {GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_MESSAGES, GatewayIntent.DIRECT_MESSAGES, GatewayIntent.GUILD_EMOJIS_AND_STICKERS});

//...

JDABuilder builder = JDABuilder.createDefault(secret, GATEWAYS).setMemberCachePolicy(MemberCachePolicy.ALL).setChunkingFilter(ChunkingFilter.ALL);
```

**Comment by MinnDevelopment** [comment]
Discord doesn't support this from the looks of it.

**Comment by Gamebuster19901** [comment]
Hmm, if that's the case, I'll probably just send my own `<bot> is thinking` message and just edit it later.

**Comment by MinnDevelopment** [comment]
Closing this since it is a discord issue and also not important. Deferred replies do not send desktop notifications, so suppressing them is pointless.
