### ISSUE TITLE
Cannot be loaded image from replying slash command.

### ISSUE THREAD

**Issue by RamuneRemonedo** [DV8FromTheWorld/JDA#2472]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

![image](https://github.com/DV8FromTheWorld/JDA/assets/99951138/a888efe4-3bf8-40f1-9569-5c40be6ff195)
<img width="346" alt="image" src="https://github.com/DV8FromTheWorld/JDA/assets/99951138/b02ba91f-e15a-442d-b9da-0333a9ac983f">
Bot replies image URL but it won't be loaded in discord.

However, if bot send as` event.getChannel().reply(imageUrl).queue();`, it will be loaded.

Please fix it.

### Code Example for Reproduction Steps

```java
public void onSlashCommand(SlashCommandInteractionEvent event) throws Exception {
    Response image = getRandomImage();
    String imageUrl = "https://astolfo.rocks/astolfo/" + image.id() + "." + image.fileExtension();
    event.replyEmbeds(
            new EmbedBuilder()
                    .setTitle(image.source())
                    .setImage(imageUrl)
                    .setColor(new Color(0xFCAAD9))
                    .build()
    ).queue();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
final JDABuilder builder = JDABuilder.createDefault(token);
builder.setActivity(Activity.playing("Initializing..."));
builder.setStatus(OnlineStatus.DO_NOT_DISTURB);
jda = builder.build();
try {
    jda.awaitReady();
} catch (InterruptedException e) {
    throw new RuntimeException(e);
}
```

**Comment by Xirado** [comment]
This is a Discord issue. See https://github.com/discord/discord-api-docs/issues/6171

**Comment by RamuneRemonedo** [comment]
thakns very much 🙏
