### ISSUE TITLE
Voice Channel event

### ISSUE THREAD

**Issue by ProgrammingWizzard** [DV8FromTheWorld/JDA#253]
Hi, I have a question. Is there any event, the User enters the voice channel? Perhaps it is, but I can not find :>

**Comment by ArsenArsen** [comment]
Here, [GuildVoiceJoinEvent](http://home.dv8tion.net:8080/job/JDA/lastCompletedBuild/javadoc/net/dv8tion/jda/core/events/guild/voice/GuildVoiceJoinEvent.html)
