### ISSUE TITLE
Setting my own status / presence doesn't seem to work

### ISSUE THREAD

**Issue by PotcFdk** [DV8FromTheWorld/JDA#263]
Hey,
I've tried to use JDA to set my own user's account status to `idle`, using `setIdle`, but it didn't work.
This is apparently what is sent to the server:

![screenshot](https://cloud.githubusercontent.com/assets/3160048/23088437/e1e8e252-f57c-11e6-8a02-456d5798238d.png)

I seem to be authenticated, because `deleteMessageById` correctly deletes my message.
Am I doing something wrong or is there some other kind of issue?

**Comment by DV8FromTheWorld** [comment]
I'm not quite sure why you've screenshotted JDA code. IT doesn't help us debug your problem.

That being said, I'm not sure how you're trying to see if your own account has been set to idle, but you don't get status updates for yourself. E.g: If you are logged into the client and you use JDA to log into the same account and you set game/status it will not show up in the Discord client **for you**. It will for other people using Discord.

If you want to check if your code is properly setting, use a different account to log in to view the account that your selfbot is using to verify it is working.

**Comment by ArsenArsen** [comment]
To add to the above, setIdle sets the current session to be idle. If all sessions are idle Discord will send notifications to your phone. So, `setIdle` isn't quite what you're looking for.

**Comment by PotcFdk** [comment]
@DV8FromTheWorld The screenshot was to show the message that is sent via the websocket, I thought this would have been the most helpful piece of information for spotting obvious user errors on my side.

>you don't get status updates for yourself
>it will not show up in the Discord client for you

Thanks, this was my issue. I've lost so many hours on this yesterday because I thought I could see it (both the status and the currently playing game (!)) from my own account. Gah.... Thank you.
