### ISSUE TITLE
RoleManager.setColor not working

### ISSUE THREAD

**Issue by Rabrg** [DV8FromTheWorld/JDA#269]
I've tried both

`role.getManager().setColor(color);`

and

```
role.getManagerUpdatable().getColorField().setValue(color);
role.getManagerUpdatable().update();
```

and neither are updating the role's color.

**Comment by MinnDevelopment** [comment]
Both of those operations are not finished. 
The `RoleManagerUpdatable#update()` method returns a `RestAction<Void>` instance which needs to be completed using
either `RestAction#queue(...)` or `RestAction#complete(...)`

`RoleManager#setColor` is a shortcut for the same update method.
