### ISSUE TITLE
Extremely distorted audio

### ISSUE THREAD

**Issue by JacobCZ** [DV8FromTheWorld/JDA#27]
When I try to load an audio file (MP3 or WAV) 90% of the time it plays extremely distorted... (Bit crushing, pitch way too high etc.) And it does this on virtually any file. I've tested it on multiple machines. What could be causing this?

**Comment by TheWithz** [comment]
I have had this problem in two instances, After converting between audio formats and when i accidentally had two instances of FilePlayer, playing at the same time.

**Comment by JacobCZ** [comment]
I haven’t converted those files. Also, I don’t have multiple instances, my code would not allow that.

**Comment by DV8FromTheWorld** [comment]
Can I get example files to test with? I've never encountered this problem and none of my files produce the issue

**Comment by DV8FromTheWorld** [comment]
Would really like some response to this...

**Comment by JacobCZ** [comment]
I'm sorry, I was away for a while. I'm going to find a file that didn't work (I've unfortunately already deleted most of them) and drop you a copy...

**Comment by DV8FromTheWorld** [comment]
Considering this has received no attention I am closing this issue.
Should you encounter the problem again feel free to open the issue again and provide source files for me to test with.
