### ISSUE TITLE
Question: Reaction speed

### ISSUE THREAD

**Issue by manercraft** [DV8FromTheWorld/JDA#277]
Hello, I have two bots on the same VPS.
But one of the bot add the reactions very fast, the second, very slow.

FAST (REAL TIME)
![fast](https://cloud.githubusercontent.com/assets/1338257/23629154/0d1ddc1a-02b7-11e7-8f7a-98310443cb9f.gif)

SLOW (REAL TIME)
![slow](https://cloud.githubusercontent.com/assets/1338257/23629155/0dd073b6-02b7-11e7-9442-6a2077b98727.gif)

**Comment by jagrosh** [comment]
Make sure both are running the same (latest development build) of JDA; this was changed fairly recently.

**Comment by Almighty-Alpaca** [comment]
update jda, I'm 100% sure the slower one is outdated

**Comment by manercraft** [comment]
Nop
![1](https://cloud.githubusercontent.com/assets/1338257/23629290/8ea2b4ea-02b7-11e7-91e7-7630edd1fe51.jpg)
![2](https://cloud.githubusercontent.com/assets/1338257/23629292/8f7202f4-02b7-11e7-8db5-3a6ee2a56371.jpg)

I will try to update

**Comment by jagrosh** [comment]
Oh my, you are severely out of date

**Comment by Almighty-Alpaca** [comment]
`JDA-3.0.BETA2_144` is the latest version

**Comment by manercraft** [comment]
Update patch :) Thank for the help, I'm stupid ^^

**Comment by Almighty-Alpaca** [comment]
np
