### ISSUE TITLE
sendMessage method in channel not sending message (although JDA reports no errors)

### ISSUE THREAD

**Issue by GandalfD** [DV8FromTheWorld/JDA#279]
I'm trying to use the sendMessage(String s) method in the TextChannel interface to send a text message in a channel using

`    public void sendMessage(TextChannel channel, String s) {
        channel.sendMessage(s);
    }`

Whenever I run to run this method on a random text channel, the call to channel.sendMessage sucesfully returns a RestAction object and the bot continues as normal. However, no text message is displayed in the channel. The bot has permissions and everything, but nothing pops up.

I'm not sure if this is related, but when using intellij's debug mode, I saw running the sendMessage method in the TextChannel interface gave this NPE
![image](https://cloud.githubusercontent.com/assets/8429648/23776605/3c1e943a-04fd-11e7-9e2e-321c851b7dcc.png)

Any help would be appreciated, thanks!

**Comment by NachtRaben** [comment]
add a .queue(); for non-blocking or .complete() to return the Message object.

Look into JDAs RestActions for more information.

**Comment by GandalfD** [comment]
> add a .queue(); for non-blocking or .complete() to return the Message object.

Thanks! Using .complete() worked
