### ISSUE TITLE
Muted channels not found

### ISSUE THREAD

**Issue by lucasmontec** [DV8FromTheWorld/JDA#29]
Message from the API (is this just an error log?):
I have removed the json because it contains information from my server. I don't know what response is this that you are logging for this error. If you need it in order to fix, tell me.

Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["muted_channels"] not found.
	READY -> {"user_settings":{"inline_embed_media":true,"render_embeds":true,"inline_attachment_media":true,"show_current_game":true,"theme":"dark","enable_tts_command":true,"locale":"pt-BR","convert_emoticons":true,"message_display_compact":true},"read_state": ...

**Comment by DV8FromTheWorld** [comment]
Please update to either the latest Recommended Build or to the latest Dev build.

**Comment by lucasmontec** [comment]
I'm using 1.2.2_139 just updated.

**Comment by kantenkugel** [comment]
and it happens in 1.2.2_139?

**Comment by lucasmontec** [comment]
yes. I have updated via gradle (following the readme) to this version. Just as I connect, I get this error. Looks like just a Syserr, not an exception.

**Comment by kantenkugel** [comment]
1.2.2_139 literally has that code commented out... try refreshing your project

**Comment by lucasmontec** [comment]
Fixed. i'm sorry gradle wasn't cooperating.

**Comment by kuroodo** [comment]
Hey, can you tell me what the cause of the error is?

**Comment by DV8FromTheWorld** [comment]
Update your JDA to the latest recommended version. This bug hasn't existed for atleast two master builds. Considering how often discord changes things you need to keep JDA up to date

**Comment by DV8FromTheWorld** [comment]
https://github.com/DV8FromTheWorld/JDA/releases
