### ISSUE TITLE
Image File

### ISSUE THREAD

**Issue by allanf181** [DV8FromTheWorld/JDA#290]
Icons of png guilds are returning jpg.

**Comment by DV8FromTheWorld** [comment]
This isn't an issue. `.jpg` is completely valid.

**Comment by HeyZeer0** [comment]
In case you need an image with an empty background it is not valid @DV8FromTheWorld

**Comment by DV8FromTheWorld** [comment]
Can you actually use transparency for guild icons? As far as I know you can't. Or, at least you couldn't.
Either way, the URL is valid. You're welcome to build your own URL, change the provided one, or submit a PR.

**Comment by allanf181** [comment]
Discord is using png in all guilds.
