### ISSUE TITLE
Message sends twice

### ISSUE THREAD

**Issue by DoggyCode** [DV8FromTheWorld/JDA#292]
Hey,

Whenever I use something like

```java
if (event.isFromType(ChannelType.PRIVATE)) //If this message was sent to a PrivateChannel
        {
            //The message was sent in a PrivateChannel.
            //In this example we don't directly use the privateChannel, however, be sure, there are uses for it!
            PrivateChannel privateChannel = event.getPrivateChannel();

            System.out.printf("[PRIV]<%s>: %s\n", author.getName(), msg);
            privateChannel.sendMessage("This message should only be sent once").queue();
}
```

And then I send the bot a message, it sends back mutliple times. Let me demonstrate: https://gyazo.com/3cf013f9330b9f1a4190a85ed86e46e0

Any idea why this might be happening? Using your exact example 💯

**Comment by jagrosh** [comment]
The bot gets an event for its own message.

**Comment by DoggyCode** [comment]
So, basically, to fix, check if the message is received from a bot or is there an own event to recieve message from clients only?

**Comment by jagrosh** [comment]
just compare the author to the selfuser

**Comment by DoggyCode** [comment]
Thanks!

**Comment by jagrosh** [comment]
If you need more assistance, please ask in the [#java_jda](https://discord.gg/0SBTUU1wZTUgGuC8) channel

**Comment by MinnDevelopment** [comment]
You should check whether the message author is the currently logged in account.
`event.getMessage().getAuthor().equals(event.getJDA().getSelfUser())`
It is also good practice to ignore messages from Users that are bot accounts `User#isBot()`
