### ISSUE TITLE
UnsatisfiedLinkError on startup

### ISSUE THREAD

**Issue by AjaxGb** [DV8FromTheWorld/JDA#30]
I'm working on a small, silly project in Eclipse on Windows 8.1, 64-bit. I've been using JDK 1.8.0_20 and JDA 1.2.2_139. My project is working fine in Eclipse, but when I try to pack and run it as a jar, I keep getting the same response:
```
Connecting to Discord...
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\toders\AppDa
ta\Local\Temp\opus360617407824081820.dll: The process cannot access the file bec
ause it is being used by another process
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at net.dv8tion.jda.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java
:121)
        at net.dv8tion.jda.managers.AudioManager.<clinit>(AudioManager.java:311)

        at net.dv8tion.jda.entities.impl.JDAImpl.<init>(JDAImpl.java:62)
        at net.dv8tion.jda.JDABuilder.buildAsync(JDABuilder.java:235)
        at JohnCenaBot.<init>(JohnCenaBot.java:42)
        at JohnCenaBot.main(JohnCenaBot.java:33)
```
(The exact numbers after `opus` vary)

I am relatively new to creating jar files, so it's possible that I'm making a mistake, but I've tried this every way I can find and it still doesn't work. Using a Gradle command to pack all dependencies, referencing the library in the jar's manifest, using Eclipse to pack all referenced libraries. Once or twice it's run perfectly, but the next time it crashes again, with no changes to the files or commands. I started out with Gradle, but after a while I tried making a new, non-Gradle project and just linking to the "Dependencies Included" JDA jar. This does not appear to have had any effect on the outcome. Attached is my non-Gradle Eclipse project; it's really just one class and a sound file.

Edit by Kantenkugel: Removed token-file from zip-file
[JohnCenaBot_noToken.zip](https://github.com/DV8FromTheWorld/JDA/files/145675/JohnCenaBot_noToken.zip)

**Comment by AjaxGb** [comment]
Jeez, thanks @kantenkugel. My bad.

**Comment by kantenkugel** [comment]
Here are a few things that are worth trying:
- Check if another version of JDA is running on the PC currently (The error says that the opus-file can not be used as another program blocks it).and try it with them closed.
- Try deleting the opus*.dll file before launching the bot
- Make sure that JDA is properly put inside of your Jar-file (open the .jar file with any gzip program an check if the opus directory exists as well as the net/dv8tion/jda one)

Please let us know, if you could find out anything new with the given suggestions.
I am also interested in how exactly you are including JDA into your project. gradle/maven, download from build-server or adding the JDA source?

**Comment by kantenkugel** [comment]
By the way: i wish you luck with receiving audio... we didn't test that at all yet (yes, there are packets incoming, but we didn't check if it is easy to use or to play back). Receiving audio is not even really alpha. We are still working on finalizing the receiving part (for 1.3.0 release)

**Comment by kantenkugel** [comment]
And... oh wow... i didn't know that we are polluting the temp-folder with all those opus.dll files

**Comment by AjaxGb** [comment]
@kantenkugel 
* There are no other versions of JDA running.
* I checked, the file seems to be deleted after the program crashes. In any case, I couldn't find any by the names given in the error message. Plenty of other `opusXXXXX...` files, though. Deleting them has no effect.
* The jar I'm working with now looks like [this](https://cloud.githubusercontent.com/assets/7976377/13305697/424acb32-db2b-11e5-8f68-821a744d4445.png).

I've tried the first two of those methods. Haven't tried compiling from source.

**Comment by kantenkugel** [comment]
No, you should not compile from source :) I was just asking to know if you did, cuz that could be a cause of error.
I am really confused, on why this happens... Each instance of JDA should create its own dll-file in the temp-folder to load as library. The docs of the used methods tell us that that file is unique... and we only access it once to load it. 

So somehow JDA locks itself out from the created temp-file (the code closes the output-stream to the file, but maybe it's not free again)... It is either that (we are still using it somehow before the read-attempt), or the .jar-file somehow loses permissions for the file. We will have to test this problem a little bit. This did not occur for anyone else yet, so it's gonna be hard to figure out.

If you find out anything new before we do, please let us know.
Also feel free to join our channel in the Discord API Guild (invite in README-file), to have a better chat

**Comment by DV8FromTheWorld** [comment]
@AjaxGb JDA v1.3.0 has been released. Please try it and see if this problem still exists.
https://github.com/DV8FromTheWorld/JDA/releases/tag/v1.3.0

**Comment by AjaxGb** [comment]
Yeah, it's working now! Thanks!
