### ISSUE TITLE
Create method for specifying maximum auto reconnect delay

### ISSUE THREAD

**Issue by Dankrushen** [DV8FromTheWorld/JDA#306]
I'd just like a method so that I can set the number that JDA#setAutoReconnect() maxes out at (for example, 60 seconds). Currently, it maxes out at 900 seconds (15 minutes); I don't want it that long, as I'll constantly be having internet cut out for prolonged periods of time, but I need it to go back online faster.

Because of this, I propose a simple method "`setAutoReconnectMaxDelay(long maxDelay)`". This method would allow for someone to change the maximum delay from 900 seconds to whatever they desire.

**Comment by DV8FromTheWorld** [comment]
Added as of efe0546 / `3.0.0_169`
`JDABuilder#setMaxReconnectDelay(int)`
