### ISSUE TITLE
GuildController changes not showing up in server

### ISSUE THREAD

**Issue by GhotiMayo** [DV8FromTheWorld/JDA#308]
I am attempting to get my bot to change the Nickname of a member on the server using GuildController. When the bot did not have proper permissions, I saw an error, but now that the permissions server-side are fixed, nothing is changing on the Discord Server.

This is the line of code in a MessageReceivedEvent listener that I am using:

`event.getTextChannel().getGuild().getController().setNickname(event.getMember(), "Spammer");`

**Comment by MinnDevelopment** [comment]
setNickname(Member, String) returns a `RestAction`.
Please read more about RestAction in our wiki: [here](https://github.com/DV8FromTheWorld/JDA/wiki/7\)-Using-RestAction)

You want to call `setNickname(event.getMember(), "Spammer").queue()`

**Comment by GhotiMayo** [comment]
I cannot believe I missed that. I am so sorry for wasting your time on this. Thank you so much for your help!
