### ISSUE TITLE
Connection pool shutdown

### ISSUE THREAD

**Issue by Kodehawa** [DV8FromTheWorld/JDA#314]
Basically, Shard #4 stopped connecting to voice channels. When testing and reading logs, everytime I tried to connect to a voice channel on any guild on that shard, it would throw https://hastebin.com/goyelivoke.vbs and refuse to connect to any VC, forcing me to restart the entire bot.

I never called shutdown() or shutdown(true) at all.

**Comment by DV8FromTheWorld** [comment]
That stack trace has nothing to do with connecting to a voice channel. Doesn't even reference any of the audio related classes.

**Comment by Kodehawa** [comment]
I mean, it just spams that when trying to join a VC, sadly. It's basically a 20mb file filled with that.

**Comment by Kodehawa** [comment]
https://hastebin.com/apeyeyinuv.pl <- That's what I got now before all that spam.

**Comment by MinnDevelopment** [comment]
We need to know what could cause this error, further investigation is required. (In case we do not move away from Unirest)

**Comment by MinnDevelopment** [comment]
This unirest issue should get fixed by #349

**Comment by MinnDevelopment** [comment]
Fixed as of 5a54243
