### ISSUE TITLE
GuildManager not able to remove roles from members

### ISSUE THREAD

**Issue by cuzitsjonny** [DV8FromTheWorld/JDA#319]
I'm using the GuildManager by calling
net.dv8tion.jda.core.entities.Guild#getController()
in a command executor class of my Discord bot.
It is possible to add roles to my users by calling
net.dv8tion.jda.core.managers.GuildController#addRolesToMember(Member, Collection)
but removing roles using
net.dv8tion.jda.core.managers.GuildController#modifyMemberRoles(Member, Collection)
or
net.dv8tion.jda.core.managers.GuildController#removeRolesFromMember(Member, Collection)
doesn't seem to be working.
It's not throwing any exceptions, it's just not applying the update.
My bot has ADMINISTRATOR permissions, so that shouldn't be a problem.

Mentioned command executor for reference:
https://github.com/cuzitsjonny/DiscordBot/blob/master/src/com/cuzitsjonny/discordbot/FactionCommandExecutor.java

**Comment by Almighty-Alpaca** [comment]
It's a `RestAction`, you have to `.queue()` or `complete()` it

**Comment by cuzitsjonny** [comment]
**cries**

This is just embarrassing, I can't believe I forgot the complete() at the end...
Thank you, I'm sorry for wasting your time for this! D:

**Comment by cuzitsjonny** [comment]
Actually now the roles are stacking. So it's still not removing them in the first operation.

![4132132](https://cloud.githubusercontent.com/assets/11801250/25173775/abfe2d3e-24f5-11e7-8a9e-72767d99d453.PNG)

Updated command executor for reference:
https://github.com/cuzitsjonny/DiscordBot/blob/master/src/com/cuzitsjonny/discordbot/FactionCommandExecutor.java

**Comment by cuzitsjonny** [comment]
Alright, I changed my application logic to use modify instead of a combination of add and remove.
Now it's working!

Thanks for the quick reply to my problem though.
