### ISSUE TITLE
JDA.getPresence().setGame(); randomly doesn't work

### ISSUE THREAD

**Issue by BleuzenYT** [DV8FromTheWorld/JDA#323]
When I use 
`JDA.getPresence().setGame(game);`
it mostly updates the game of my bot, but sometimes the old game stays.

`JDA.getPresence().setGame(null);`
also doesn't work everytime. Sometimes it doesn't clear the game, the bot still plays.

I'm using JDA 3.0.0_180.

**Comment by MinnDevelopment** [comment]
You can only update the game 5 times per minute, if you exceed that limit it will silently drop your request.

**Comment by PT400C** [comment]
@MinnDevelopment But after that time, you are able to set the game again? My JDA isn't able to set the game when this limit has passed once. After that the .setGame doesn't do anything.

Same JDA-version

**Comment by MinnDevelopment** [comment]
This limit includes all changes to the presence, not only game but also status and the afk field. If you update any of those you add up to the limit. As you describe it it only sometimes does not work?

**Comment by BleuzenYT** [comment]
@MinnDevelopment Yes. I guess the limit is the problem. It should at least throw an Exception, that we can handle it.

**Comment by PT400C** [comment]
Well, if I pass that limit everything, has to do with presence updating, does not work anymore. I have to restart the bot and wait some time. Then it works again.

**Comment by MinnDevelopment** [comment]
That doesn't sound right, after a minute it should work again. This can only be caused by discord's presence server being under heavy load which means it will update at a later point in time automatically.
Throwing an exception for this setting is difficult because of the aforementioned reason that it is a silent drop of the request.

**Comment by BleuzenYT** [comment]
"it will update at a later point in time automatically" is not true. I tested it and after 2 minutes it still didn't update the game. I have to call setGame() again.

**Comment by MinnDevelopment** [comment]
To figure out if this is a JDA issue I need to see how you interact with `Presence` specifically.

**Comment by PT400C** [comment]
I use this: `jda.getPresence().setGame(Game.of("SHARD "+ shardId + "/"+ totalShards + ""));`

**Comment by MinnDevelopment** [comment]
Actually I might just have found an issue.

**Comment by MinnDevelopment** [comment]
Can you please try to reproduce this with version `3.0.0_181`

**Comment by PT400C** [comment]
Looks like it's working for me now.

**Comment by BleuzenYT** [comment]
The problem is still there. After 2 minutes (just to get sure), it still didn't change the game. I still have to call setGame() again after about 1 minute.

**Comment by MinnDevelopment** [comment]
But it works without having to restart the application?

**Comment by BleuzenYT** [comment]
Yes

**Comment by MinnDevelopment** [comment]
Then this is intended behaviour. The rate limit cannot and will not be handled by JDA. It is a discord limitation that is intended to refrain you from updating your status too often. If you update multiple fields use the new setPresence method to decrease your presence updates.

**Comment by BleuzenYT** [comment]
Hm, ok. Than I have to create my own thread, which counts game updates, waits a minute after 5 and ...

Maybe you can implement something like we have with messages already:
```java
channel.sendMessage("").queue();
```
Something like:
```java
getPresence().setGame(game).queue();
```
Just to make it easier for JDA users.

**Comment by MinnDevelopment** [comment]
This is not possible. RestAction uses the headers of REST responses to spawn rate limit buckets.
Presence uses raw websocket messages which don't get a response from discord. If ratelimited the request is simply dropped and we have no clue that it happens. There is no way for us to know when we hit this limit.

**Comment by BleuzenYT** [comment]
Ok, thank you anyway ;D

**Comment by ShanerX** [comment]
There could be a way to find out when the limit is hit: Just store the time when you are sending the requests, every time there is a request, check how many times in that min. the game has been updated. If it has already hit the limit, send a message informing the user, such as "Sorry, but you must wait 60 seconds before using that command!".

**Comment by jagrosh** [comment]
This won't work because you can't detect if a different connection changes the game or status. No message (and a policy of no message) is better than being an inconsistent message.

**Comment by ShanerX** [comment]
@jagrosh It works if you have only 1 bot running on your account. Thus, it works in some cases.

**Comment by jagrosh** [comment]
Working in some cases is not a good design. It should work all the time. The current system (no message) is reliable.

**Comment by ShanerX** [comment]
I am well aware of that, but on production bots that are used by people who are not the author, an error message may be a better solution.
I believe that this condition 
> It works if you have only 1 bot running on your account
can be easily

**Comment by jagrosh** [comment]
If you want to implement it on things you write and work with, go ahead. Something with as much inconsistency as this has no place in JDA.

**Comment by ShanerX** [comment]
Forgive me if I wasn't clear. I perfectly agree on the fact that JDA cannot implement this. This solution should be implemented by the person who is writing a bot.

**Comment by jagrosh** [comment]
Ah, I misunderstood your intent, I apologize.

**Comment by ShanerX** [comment]
@BleuzenYT , an easier way of performing the check would be to call JDA#getPresence().setGame(Game.of(String)); and checking whether the game matches the string entered afterwards. If not, you're under cooldown.

**Comment by jagrosh** [comment]
That actually wouldn't work. You don't receive any kind of notification if a different login on the same account changes your game. So if you have 2 bots logged into the same account (we'll call them LoginA and LoginB), if LoginA sets the game to "a cool game", and then LoginB sets it to "a weird game", LoginA's JDA will still report the current game as "a cool game" even though it has changed for everyone else.

**Comment by ShanerX** [comment]
Rip, didn't know that.
