### ISSUE TITLE
Editing message through channel causes internal server error

### ISSUE THREAD

**Issue by TheMagzuz** [DV8FromTheWorld/JDA#329]
Executing the following code: 
```java
MessageBuilder mb = new MessageBuilder();
MessageChannel channel = // Predefined channel
String[] messages = {"1", "2", "3", "4"};
Message send = mb.append(messages[messages.length-1]).build();
String id = send.getId();
System.out.println(send.getRawContent() + " : " + id);
channel.sendMessage(send).complete();
for (String msg : messages)
{
	channel.editMessageById(id, msg).queue();
	try {
		Thread.sleep(100);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
}
```
Throws the following errors:
`[12:50:26] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 0: Discord encountered an internal server error! Not good!`
`[12:50:26] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 0: Discord encountered an internal server error! Not good!`
`[12:50:26] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 0: Discord encountered an internal server error! Not good!`
`[12:50:27] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 0: Discord encountered an internal server error! Not good!`

**Comment by ArsenArsen** [comment]
This is in no way a JDA issue. If you could get the error message, to report it to Discord, it would be useful (probably), but still, not a JDA issue.

**Comment by TheMagzuz** [comment]
@ArsenArsen What is the easiest way to get this error message? From what i can tell, there's no way to get it from the exception

**Comment by MinnDevelopment** [comment]
The easiest way would be to get `exception.getResponse().getString()`

**Comment by MinnDevelopment** [comment]
Btw the issue you are having is that you try to use the ID of the message that was built using the `MessageBuilder` to edit the message after sending. However this is not possible since the ID returned by that message is incorrect and will not work.
IDs are assigned to messages _after_ they were sent. You need to get the ID of the message that `sendMessage(msg).complete()` returns.
