### ISSUE TITLE
Issue When Removing 2 Roles Then Adding A Role

### ISSUE THREAD

**Issue by kuroodo** [DV8FromTheWorld/JDA#33]
I've come across some weird issue. Basically this is what I want to accomplish:
- Remove all roles from a specific user
- Afterwards, give the user a specific role.

The code works perfectly fine when I want to remove a single role from a user/the user only has a single role. But when there are multiple roles, it has issues.

What ends up happening/my issue:
- Code successfully removes all of the roles from the user
- When I give them the specific role, it also adds one of the roles I removed (gets a random one)

The user has these 2 roles by default: Red and Regular. I want to remove those 2, and give them the role of Member.

I made a class called ChatHelper. It has methods that simplify my code. The methods are self explanatory and don't interfere with the problem.

This is the code

        User user = CHATHELPER.getUserByUsername("testbot_wckp");
		ArrayList<Role> usersRoles = new ArrayList<Role>();

                // Store current roles in an array
		for (Role role : CHATHELPER.getGuild().getRolesForUser(user)) {
			usersRoles.add(role);
            System.out.println("Added " + role.getName() + " to the array");
		}
                // Remove those roles from the user
		for (Role role : usersRoles) {
			CHATHELPER.getGuild().getManager().removeRoleFromUser(user, role).update();
		}

		CHATHELPER.getGuild().getManager().addRoleToUser(user, CHATHELPER.getRoleByName("Member")).update();

Console output:
Added Regular to the array
Added Red to the array

Here is the output log from my server listener:
- testbot_wckp just had the following roles removed: 
Regular
- testbot_wckp just had the following roles removed: 
Red
- testbot_wckp was just given the following roles: 
Regular
- testbot_wckp just had the following roles removed: 
Regular
- testbot_wckp was just given the following roles: 
Red
- testbot_wckp was just given the following roles: 
Member

The ending result is the user ending up with 2 roles: Member and Red, or Member and Regular.

**Comment by Almighty-Alpaca** [comment]
i would try to not call `GuildManager#update()` multiple times, so i would change
```java
for (Role role : usersRoles) {
    CHATHELPER.getGuild().getManager().removeRoleFromUser(user, role).update();
}
```
to
```java
GuildManager manager = CHATHELPER.getGuild().getManager();
for (Role role : usersRoles) {
    manager.removeRoleFromUser(user, role);
}
manager.update();
```
can you try that and report if that solved the problem?

**Comment by kuroodo** [comment]
That seems to have worked!

Quick question. Why do I have to create a manager variable?

Your code works fine.
But something like this doesn't work at all (it never removes the roles/never updates).

```
for (Role role : usersRoles) {
   CHATHELPER.getGuild().getManager().removeRoleFromUser(user, role);
}

CHATHELPER.getGuild().getManager().update();
```

**Comment by kantenkugel** [comment]
the change of @Almighty-Alpaca should solve the problem!
Basically: all Managers - including the GuildManager - work on the current state of the system.
A state is changed, once we get the corresponding change-event via the socket, not directly after calling .update() on a Manager.

This means, that your code does following:
User has roles Red and Regular
Your remove role Red (manager sends role Regular to the server as current set of roles)
Your remove role Regular from the user, in the same event-loop (Locally user still has both, Red and Regular). We send role Red as remaining role to server - User would now have role Red remaining, after having called both remove...

Similarly the addRole will have the same "unexpected" behaviour.

But therefore we have designed all methods that depend on the current state of JDA to have a builder-style usage (you set all values you want to set, and then call .update() to update multiple changes at once)

**Comment by kantenkugel** [comment]
To answer the 2nd question: .getManager() returns a new instance of the manager (all cached changes are lost)
-> save the manager and call update on the saved one

**Comment by kuroodo** [comment]
This makes a lot of sense!

Thanks for the help explanation (:

**Comment by kantenkugel** [comment]
No problem. This seems to confuse some people, but we had no other good choice when writing the managers.
I will look at having a single instance of the Manager per entity instead of creating a new one. Maybe that happens :)
