### ISSUE TITLE
Any idea why this isn't working?

### ISSUE THREAD

**Issue by StijnSimons** [DV8FromTheWorld/JDA#337]
if(event.getGuild().getMemberById(event.getAuthor().getId()).getRoles().contains("Admin"))

**Comment by Almighty-Alpaca** [comment]
It doesn't work because `getRoles()` returns a `List<Role` and **not** a `List<String>`.

You can btw also change `event.getGuild().getMemberById(event.getAuthor().getId())` to `event.getMember()`

**Comment by StijnSimons** [comment]
Oh, thanks. Is there any way of returning a Role name instead of the Role itself?

**Comment by Almighty-Alpaca** [comment]
you could use java 8's cool (new) streams
```java
getRoles().stream().anyMatch(r -> r.getName().equals("Admin"));
```
or if you don't care about the case
```java
getRoles().stream().anyMatch(r -> r.getName().equalsIgnoreCase("Admin"));
```

**Comment by StijnSimons** [comment]
Thanks so much!
