### ISSUE TITLE
GuildVoice{Join,Move,Leave}Event need a common superclass

### ISSUE THREAD

**Issue by ScoreUnder** [DV8FromTheWorld/JDA#339]
To find if somebody has left a voice channel, you must hook `GuildVoiceMoveEvent` and `GuildVoiceLeaveEvent`, and call their different `getChannelLeft` methods. Similar for joining channels.

These should have a common interface, so that the channel left (or joined) can be determined using the same method, rather than identically named incompatible methods.

**Comment by meowingtwurtle** [comment]
/i@MinnDevelopment I think this can be actually closed now....

**Comment by SparklingComet** [comment]
Shouldn't this get closed as the request was granted?

**Comment by DV8FromTheWorld** [comment]
Odd that the commit didn't close this.
