### ISSUE TITLE
Server Name

### ISSUE THREAD

**Issue by andrei1058** [DV8FromTheWorld/JDA#340]
Hi, how can I get the server name? #

**Comment by Almighty-Alpaca** [comment]
[`Guild#getName()`](http://home.dv8tion.net:8080/job/JDA/javadoc/net/dv8tion/jda/core/entities/Guild.html#getName--)

**Comment by Almighty-Alpaca** [comment]
your IDE's auto complete feature will help you finding methods like this btw
