### ISSUE TITLE
Audit Logs

### ISSUE THREAD

**Issue by clevertoucan** [DV8FromTheWorld/JDA#344]
Would love to see an update that allows JDA to retrieve audit logs from a guild

**Comment by Almighty-Alpaca** [comment]
audit logs are in progress, see [`feature/audit-logs`](https://github.com/DV8FromTheWorld/JDA/tree/feature/audit-logs)

**Comment by MinnDevelopment** [comment]
We have gotten fairly far into audit logs development in JDA.
Here is a small sneak-peak on what you can expect to be able to do
```java
guild.getController().setNickname(guild.getSelfMember(), "Awesome Bot").reason("Wasn't aweseome 'nough").queue()
guild.getController().kick("86699011792191488").reason("Not awesome enough").queue()
```
> Here we add reasons to the `AuditableRestAction`s which are returned by most GuildController methods
```java
AuditLogPaginationAction logs = guild.getAuditLogs();
for (AuditLogEntry entry : logs)
{
    System.out.println("Type: " + entry.getActionType() + "\nReason: " + entry.getReason());
}
```
Output:
```
Type: MEMBER_UPDATE
Reason: Wasn't aweseome 'nough
Type: KICK
Reason: Not awesome enough

**Comment by MinnDevelopment** [comment]
This has been introduced in commit e909ca9
