### ISSUE TITLE
[Question] Steamer mode

### ISSUE THREAD

**Issue by manercraft** [DV8FromTheWorld/JDA#346]
Hello, I have a question, it's possible to force the steamer mode and change the stream title ?

**Comment by MinnDevelopment** [comment]
What do you mean with "streamer mode"?
Do you mean people showing up as "Streaming X"?
If that is what you mean you can achieve that by using `jda.getPresence().setGame(Game.of("X", "https://twitch.tv/something"))`
For more information look into the documentation for __Presence__ and __Presence.setGame__

**Comment by manercraft** [comment]
Oh thank !
