### ISSUE TITLE
JDA stuck on building

### ISSUE THREAD

**Issue by FunkyGamer** [DV8FromTheWorld/JDA#350]
I just restarted my Discord bot and noticed that my commands aren't working anymore.
Looking at the logfile, this is everything I can see:

> [10:49:11] Bot starting ...
> [10:49:12] [Info] [JDA]: Login Successful!
> [10:49:12] [Info] [JDASocket]: Connected to WebSocket

Nothing else is happening.
Normally there are atleast two more log entries, right after the build method call and one in the onReady event.

So it seems like the bot is stuck in the build method somehow and I can't figure out was is wrong.
Recording to the Discord status site the API is up though, so there seemingly can't be a problem on Discords side. Also the bot is logging in properly and also shows as online in my serverlist. But that's about it. I didn't change anything in my code, just restarted the bot.

What could be causing this issue?

**Comment by shikhir-arora** [comment]
That can happen if it gets stuck on loading a server, for example. I know there was an issue with loading BetterDiscord sometimes.

**Comment by MinnDevelopment** [comment]
If you are on build version `3.0.0_194` consider downgrading. The build contains a change that broke the startup for some bots.

**Comment by FunkyGamer** [comment]
@MinnDevelopment Thanks! Downgrading back to 3.0.0_193 fixed the issue!
