### ISSUE TITLE
Online Users

### ISSUE THREAD

**Issue by andrei1058** [DV8FromTheWorld/JDA#352]
Is there a way to get the online users from a server?

**Comment by shikhir-arora** [comment]
Sure, as long as you/the bot(s)/whatever is a member of the guild, of course. There are a few ways you can do it. Here's a way to start out within a guild - `event.getGuild().getMembers().stream()` - finish it off with a lambda expression. (can use something like `getOnlineStatus().toString().equals("ONLINE")` as a crude way of checking each member. Anyway, these were just a few quick pointers.

**Comment by andrei1058** [comment]
Oke, thanks :)

**Comment by Almighty-Alpaca** [comment]
**Never** compare [Enums](https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html) using their `toString()` methods, it defeats their entire purpose. You can compare Enums safely with the `==` operator, e.g. `getOnlineStatus() == OnlineStatus.ONLINE`.

**Comment by shikhir-arora** [comment]
@Almighty-Alpaca 🤦 
yeah... that was something I did and had saved from months ago to quickly check - but yeah, thanks for pointing that out. 👍

**Comment by andrei1058** [comment]
Thanks for help 😄

**Comment by Almighty-Alpaca** [comment]
As it sounds like this issue is resolved I'm closing it now
