### ISSUE TITLE
The provided token is invalid

### ISSUE THREAD

**Issue by a11ce** [DV8FromTheWorld/JDA#359]
I'm using the token from https://discordapp.com/developers/applications/me/<bot id>, and it says the provided token is invalid. I've tried generating new tokens multiple times. I'm using the example code.

**Comment by Sanduhr32** [comment]
Thats no JDA issue... Please be sure you copied the whole token and pasted the whole token in JDABuilder#setToken(String token).

    JDA = new JDABuilder(AccountType.BOT).setToken("<token here>").buildBlocking();

**Comment by Almighty-Alpaca** [comment]
Also be sure to copy the token only and not more
