### ISSUE TITLE
Audio system stops working when unplugging the network

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#360]
I was doing some network recovery testing with one of my niche bots when I discovered that the voice system simply stopped being able to send or leave a channel after being unplugged for a few seconds.

- `AudioManager#getConnectedChannel()` appears to return null
- `AudioManager#closeAudioConnection()` does nothing.
- It doesn't seem that the sending handler is getting any calls.
- The bot can move to a different voice channel, but the above still occurs.
- I am on `3.1.0_204`

**Comment by napstr** [comment]
Wow, what a coincidence, I ran into the very same problem a week ago. Had an in-depth talk with @MinnDevelopment about it. Discord appears to not resume/terminate a lost audio connection unless you change voice regions, or login again (e.g. reviving a shard).

**Comment by napstr** [comment]
I had some luck getting the connection audio connection restored by following this reference http://knowledgebase.progress.com/articles/Article/000044970
and setting the timeout of the machine the bot is running on to rather aggressive values of 

```
echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 1 > /proc/sys/net/ipv4/tcp_keepalive_probes
```
Setting the timeout to 120 had lavaplayer collect the track with `AudioTrackEndReason.CLEANUP`.

I'm not sure if editing the timeout values like this is a good idea.
