### ISSUE TITLE
setNickname hierarchy oversight?

### ISSUE THREAD

**Issue by paladinshiva** [DV8FromTheWorld/JDA#369]
.setNickname when triggered by Owner(isOwner) using will throw the higher role exception even if Owner does not have assigned role or has one that is lower than the Bot roles.
Either Discord treats Owner as a highest role internally and that cannot be changed, which I was not able to find reference to, or a Permission check error somewhere in JDA code that I also could not find...
Send help please.

P.S.
Working just fine if you getSelfMember, will change bot's nickname, or if you are any other member.

**Comment by MinnDevelopment** [comment]
The owner of a guild is not a role. Owners are always above all roles in the hierarchy and thus cannot be banned/kicked/nicknamed.
If you want to check whether you can nickname someone you can try using `Member#canInteract(Member)` (except for self member which doesn't comply to hierarchy when setting nick)

**Comment by paladinshiva** [comment]
Thank you, I suspected as well...
So if SelfMember doesn't comply, then can I use it in a loop for Owner to change my nickname if I am the Owner?

**Comment by MinnDevelopment** [comment]
The owner of a guild can change everyone's nickname

**Comment by paladinshiva** [comment]
Well yes, but Owner can not change Owner's nickname using Bot, unless the Bot is the Owner.
Right?

**Comment by MinnDevelopment** [comment]
That kinda contradicts itself how could the bot be owner and change the owner's nickname? The bot is just another user and has its own permissions not the permissions of the user invoking its commands. So unless the bot is indeed the owner and changes its own nickname it cannot change the owner's nickname.

**Comment by paladinshiva** [comment]
So then unless you "Transfer Ownership" to the specific Bot(if that's even possible), then if you are the Owner you going to have to suck it in and change it yourself...
Haha
Thank you for response!!!
It just bothered me because I was trying to test the command and it wouldn't work...
