### ISSUE TITLE
Images don't upload

### ISSUE THREAD

**Issue by DaMatrix** [DV8FromTheWorld/JDA#379]
I'm trying to upload a PNG image via JDA, and can't get it to work. Using a `File` to the .png on my desktop, reading the file to a `byte[]`, both result in nothing happening at all. No errors in the log, the image never appears though.

Am I missing something? thanks!

**Comment by MinnDevelopment** [comment]
How are you trying to send the file? Please provide more information.

**Comment by MrPowerGamerBR** [comment]
Cannot reproduce, I'm using version "3.1.1_212" (I will try reproducing this with "3.1.1_213" soon)

```java
context.sendFile(new File(Loritta.FOLDER + "angel.png"), "angel.png", new MessageBuilder().append(" ").build());
```

And via input stream
```kotlin
val os = ByteArrayOutputStream()
ImageIO.write(blackWhite, "png", os)
val inputStream = ByteArrayInputStream(os.toByteArray())
context.sendFile(inputStream, "undertale_battle.png", " ");
```

**Comment by Almighty-Alpaca** [comment]
You forgot to `.queue()`, sendFile() returns a [RestAction](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction).

**Comment by kantenkugel** [comment]
classic

**Comment by MrPowerGamerBR** [comment]
@Almighty-Alpaca but I said that I cannot reproduce this issue 🤷‍ Sending images is working fine to me 😉 

I use an external class to handle message sending so I can apply some per-server configurations (and I forgot that when I sent the code I was using here 😋)

**Comment by Almighty-Alpaca** [comment]
I just mentioned it so nobody comes and blames that example to not work

**Comment by DaMatrix** [comment]
I'm using `channel.sendFile(new File("E:\\image.png"), "png", null).queue();`. Adding a file name (`channel.sendFile(new File("E:\\image.png"), "image.png", null).queue();`) doesn't help either.

**Comment by kantenkugel** [comment]
Have you checked what the call returns? Inside of `queue `as callback or the result of `complete`.

You are not seeing anything at all in the channel, right?

**Comment by DaMatrix** [comment]
Nope, nothing. I put a System.out.println("yay"); inside the callback, but nothing.

**Comment by kantenkugel** [comment]
Then i suspect that your file-send code is not even reached and that its not a fault of the sendFile function at all

**Comment by DaMatrix** [comment]
Actually, I forgot to close the bot process, and now (20 minutes after it sent!!!) i got this in the log:
[18:13:24] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 40005: Request entity too large

and no, a System.out.println directly before the sendFile confirms that it IS getting there

**Comment by DaMatrix** [comment]
the image is only 100KB, before you ask

**Comment by MinnDevelopment** [comment]
Could you try reading the file yourself and providing the data as either an InputStream or byte[] to sendFile together with the file name?

**Comment by DaMatrix** [comment]
as i said, i already tried with a byte[] to no avail, and adding the image name didn't help.

**Comment by MinnDevelopment** [comment]
Does this happen for every image or just a specific image file?

**Comment by DaMatrix** [comment]
i've tried 6 different ones, 2 jpegs and 4 pngs

**Comment by DV8FromTheWorld** [comment]
@DaMatrix Are you still experiencing this? Can anyone else reproduce this issue?

**Comment by DaMatrix** [comment]
sorry, i should have closed it. it was caused by a hardware issue, the drive with the images on it wasn't connected properly. it seems to work fine now.
