### ISSUE TITLE
Memory leak of audio connections

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#380]
My bots appear to be suffering from memory leaks. I took a heap dump of my patron bot, which has been running for 30 days with JDA `3.0.0_200`. Looking at the heap dump I see that `java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue` is retaining 53% of my heap.

**Clarification:** The 30 days is with a relatively small bot. For my bot with over 1400x as many guilds this problem is about 10x-15x faster to take up the heap to the point of impacting audio playback.

![image](https://user-images.githubusercontent.com/2582617/27259963-bd415f4a-541f-11e7-830d-ca2178f7a258.png)
The problem appears to be that we have numerous `AudioConnection`s which still holds references to my send handler, which in my case is called `GuildPlayer`:

![image](https://user-images.githubusercontent.com/2582617/27260002-bfb9fbaa-5420-11e7-85a5-78dc12c792c6.png)

I'm not sure why these connections are being retained, but it doesn't look like these connections are getting references from my code without going through JDA code. 

This could possibly be related to https://github.com/DV8FromTheWorld/JDA/issues/357

I use JDA-NAS

**Comment by Frederikam** [comment]
This is how the inbound references looks like to those `AudioConnection`s
![image](https://user-images.githubusercontent.com/2582617/27260094-9a98dd70-5423-11e7-935c-5c084bdbbcbd.png)

**Comment by Repulser** [comment]
+1 Its been killing my bot for a while now

**Comment by Shredder121** [comment]
Don't know if you want the fix on a specific branch, but I found the culprit.

**Comment by MinnDevelopment** [comment]
Fixed as of 69efe74
