### ISSUE TITLE
Bintray Repository

### ISSUE THREAD

**Issue by istamendil** [DV8FromTheWorld/JDA#385]
Hello!
Tried to added JDA as dependency to Maven project. But there aren't newest versions in Bintray Repository. May be I don't understand something but I see the latest version there is only 1.2.2_139: https://bintray.com/bintray/jcenter/net.dv8tion%3AJDA . Please update repo or remove information about using it.

**Comment by MrPowerGamerBR** [comment]
... https://bintray.com/dv8fromtheworld/maven/JDA/3.1.1_219

**Comment by MinnDevelopment** [comment]
Use the bintray link from our README please. https://bintray.com/dv8fromtheworld/maven/JDA/

**Comment by istamendil** [comment]
Thanks to my IDE that autocompleted version and used 1.2 even with right group name. May be Netbeans tries to search for artifact by itself without group name at first or whatever. Anyway bintray makes some mess with copying people's repositories.
