### ISSUE TITLE
Store MessageEmbed as Message?

### ISSUE THREAD

**Issue by imcolexd** [DV8FromTheWorld/JDA#387]
How would I store a MessageEmbed as a Message to (after sending) get the Message's ID?

**Comment by napstr** [comment]
The same way you do it for a regular message.

You get a hold on the Message object (which in turn will give you the message id) by using the result from `complete()` or providing a success handler to `queue()`.

```java
RestAction<Message> ra = channel.sendMessage(myEmbed);

Message myMessage = ra.complete();
long messageId = myMessage.getId();
// or
ra.queue(myMessage -> myMessage.getId());
```

**Comment by MinnDevelopment** [comment]
This seems to be resolved. For support please join our discord server linked in our README or the [discord-api server](https://discord.gg/discord-api).
