### ISSUE TITLE
Coding a Minecraft bot with JDA

### ISSUE THREAD

**Issue by freakyy85** [DV8FromTheWorld/JDA#389]
Getting the following error:
```
11.07 23:10:55 [Server] INFO [UCBot] Enabling Discord Wrapper, making connection ...
11.07 23:10:55 [Server] WARN java.lang.RuntimeException: java.lang.ExceptionInInitializerError
11.07 23:10:55 [Server] WARN at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:335)
11.07 23:10:55 [Server] WARN at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:183)
11.07 23:10:55 [Server] WARN at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:130)
11.07 23:10:55 [Server] WARN at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:496)
11.07 23:10:55 [Server] WARN at de.freakyonline.ucbot.UCBot.onEnable(UCBot.java:19)
11.07 23:10:55 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
11.07 23:10:55 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
11.07 23:10:55 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
11.07 23:10:55 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378)
11.07 23:10:55 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
11.07 23:10:55 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
11.07 23:10:55 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
11.07 23:10:55 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
11.07 23:10:55 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
11.07 23:10:55 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
11.07 23:10:55 [Server] WARN at java.lang.Thread.run(Thread.java:748)
11.07 23:10:55 [Server] WARN Caused by: java.lang.ExceptionInInitializerError
11.07 23:10:55 [Server] WARN at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
11.07 23:10:55 [Server] WARN at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
11.07 23:10:55 [Server] WARN at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
11.07 23:10:55 [Server] WARN at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
11.07 23:10:55 [Server] WARN at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
11.07 23:10:55 [Server] WARN at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
11.07 23:10:55 [Server] WARN at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
```
Here the code:

        try {
            JDA jda = new JDABuilder(AccountType.BOT)
                    .setToken("myToken")
                    .addEventListener(new UCBotDiscordListener())
                    .buildAsync();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

Can you help me fix this?
Thanks!

**Comment by Almighty-Alpaca** [comment]
This happens because Minecraft uses an ancient version of [Apache Commons Lang](https://commons.apache.org/proper/commons-lang/) which lacks many methods JDA is using.
You can fix the error by shading and relocating JDA and it's dependencies into your plugin's jar.

**Comment by freakyy85** [comment]
I'm new to java and I don't know how to shade and relocate JDA?

**Comment by freakyy85** [comment]
ah I found a threat that helped: https://www.spigotmc.org/threads/jda-spigot-plugin-failing-to-enable.201638/

**Comment by DOOMRise1** [comment]
![image](https://user-images.githubusercontent.com/55848566/153750269-18b40dd5-e232-4449-a2de-941831f5f048.png)
![image](https://user-images.githubusercontent.com/55848566/153750288-681bc59d-63da-461a-8ae3-0f8a3ed33133.png)

HOW TO DOWNLOAD JDA.JAR??
???

**Comment by Xirado** [comment]
Don't necropost issues that are over 4 years old.

Use a buildtool like Maven or Gradle. [Example](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#noclassdeffounderror-or-classnotfoundexception-on-startup)

**Comment by SIMULATAN** [comment]
> ![image](https://user-images.githubusercontent.com/55848566/153750269-18b40dd5-e232-4449-a2de-941831f5f048.png)
> ![image](https://user-images.githubusercontent.com/55848566/153750288-681bc59d-63da-461a-8ae3-0f8a3ed33133.png)
> 
> HOW TO DOWNLOAD JDA.JAR??
> ???

Learn and use a build tool like gradle or maven and follow the instructions in the readme of this repo

**Comment by Zemux1613** [comment]
Hey @SIMULATAN,

on https://github.com/DV8FromTheWorld/JDA/releases you can download the jar file. 

I advice the folloing file: 
![grafik](https://user-images.githubusercontent.com/42244022/153768645-6c5e3ed3-01e4-46da-bf63-998229f7f33b.png)
