### ISSUE TITLE
JDA Socket take times to load

### ISSUE THREAD

**Issue by RissCrew** [DV8FromTheWorld/JDA#397]
Hi, 

I'm having some problems why loading my bot (It's a self bot created by me).
The problem is that he take so many time to load.

[18:00:09] [Info] [JDA]: Login Successful!
**[18:00:09]** [Info] [JDASocket]: Connected to WebSocket
**[18:02:23]** [Info] [JDA]: Finished Loading!

I have try on my ide, on a jar executable and on a vps and same problem.
I don't have connection problems.

Can someone help me ?

**Comment by MinnDevelopment** [comment]
I don't see an issue here.
You are using a client account on an api that is made for general bots. JDA will make attempts to load everything accordingly which can take a bit longer if you are connected with a client account to guilds that reach specific online limits.
Such guilds cause JDA to take longer to allocate the cache for that guild and thus will stop the setup from progressing. 

It is not currently possible to change that behaviour and we are unable to change it for now.
