### ISSUE TITLE
Deleting a message?

### ISSUE THREAD

**Issue by File14** [DV8FromTheWorld/JDA#408]
Hello!

 I'm having a problem to delete a message from another user.
On **MessageReceivedEvent** I use event.getMessage().delete();
but it doesn't remove the user's message. 

I have given the bot all permissions when adding the bot to my server and it's in a role that also has all permissions. Anyknow know why it won't remove 

Best Regards,
File14

**Comment by MinnDevelopment** [comment]
The method you are using returns an instance of [`RestAction`](https://github.com/DV8FromTheWorld/JDA/wiki/7\)-Using-RestAction)
In order to execute you have to call one of the execution methods `queue()`/`complete()`/`submit()`. See the linked wiki for more information.

**Comment by File14** [comment]
Thank you, sir! :D
