### ISSUE TITLE
[Suggestion] Add a getGuild() method to MessageChannel

### ISSUE THREAD

**Issue by LemonJuiz** [DV8FromTheWorld/JDA#416]
It just makes since and using my code right now I have to pass a MessageChannel and a Guild when I should be able to get the Guild associated with the MessageChannel. Thanks!

**Comment by kantenkugel** [comment]
A MessageChannel is not bound to a Guild. MessageChannel is a super Interface that gets implemented by TextChannel (Guild), PrivateChannel (private, no Guild) and Groups (also no Guild).

Therefore `MessageChannel#getGuild()` doesn't make much sense.

I suggest you to provide a more specific version to your method (like TextChannel, which has `getGuild()`. You can get it via the event)

**Comment by LemonJuiz** [comment]
Having MessageChannel#getGuild() return null when not a text or voice channel is an option, but it seems using the event does just the thing I wanted. Thanks!

**Comment by ArsenArsen** [comment]
That'd kill the point of the sub interfaces too.

**Comment by Sanduhr32** [comment]
You could try Event#getGuild() if the Event is an instanceof an GuildXEvent it returns a never-null Guild ("normal" MessageReceivedEvent etc are working too but the Guild could be null if the Event has `getGuild()`) Regards Sanduhr
