### ISSUE TITLE
New Application API Example

### ISSUE THREAD

**Issue by xunkar** [DV8FromTheWorld/JDA#42]
Hello, I've been using your library for my own project, but with the new Applications migration I'm left wondering how to authenticate my bot now since there is no password. Could you provide a complete example of how to initialize a bot under this new system? Thank you.

**Comment by DinosParkour** [comment]
You can use [JDABuilder(botToken)](http://ci.dv8tion.net/job/JDA/lastCompletedBuild/javadoc/net/dv8tion/jda/JDABuilder.html#JDABuilder-java.lang.String-) or [JDABuilder#setBotToken](http://ci.dv8tion.net/job/JDA/lastCompletedBuild/javadoc/net/dv8tion/jda/JDABuilder.html#setBotToken-java.lang.String-).

**Comment by Frederikam** [comment]
Here's how my bot handles it:
https://github.com/Frederikam/FredBoat/blob/master/src/main/java/fredboat/FredBoat.java#L89

**Comment by kantenkugel** [comment]
^ You guys are fast!

**Comment by hlaaftana** [comment]
wtf i was just going to respond with no comments then i switch from a tab and boom

**Comment by MinnDevelopment** [comment]
I still don't understand

**Comment by MinnDevelopment** [comment]
Please explain

**Comment by Frederikam** [comment]
![image](https://cloud.githubusercontent.com/assets/2582617/14434284/47d9f274-0012-11e6-89c8-b3399e47c2a3.png)
Rude >:(

**Comment by DV8FromTheWorld** [comment]
@xunkar @DinosParkour the `JDABuilder(botToken)` constructor is going away with JDA v2.0.
Please use `JDABuilder()` and `setBotToken(token)`

**Comment by xunkar** [comment]
Thanks a lot for the quick answer everyone!

**Comment by hlaaftana** [comment]
btw, https://discord.gg/0SBTUU1wZTY3Epi1
