### ISSUE TITLE
Adding custom Audit Log events?

### ISSUE THREAD

**Issue by iAreas** [DV8FromTheWorld/JDA#424]
Is it possible to add custom Audit Log events in Discord? If so, it would be really cool if you'd add it to JDA, because i could track down exceptions and stuff with it.

Thanks!

**Comment by kantenkugel** [comment]
We can't easily add Audit Log events because we don't get Audit logs via events either. We would have to query the Audit Log endpoint every so often to check for new logs which is bad (spamming requests)

**Comment by iAreas** [comment]
If it's not supported by Discord, it's okay. Just wished it was.
