### ISSUE TITLE
Shard deadlock on SHUTTING_DOWN state

### ISSUE THREAD

**Issue by Kodehawa** [DV8FromTheWorld/JDA#426]
Posting as an issue on @MinnDevelopment request.

There's a (rare) issue on shard shutdown which causes some shards to get stuck on SHUTTING_DOWN.
The cause is a deadlock caused by JDA trying to put AND get from a TSynchronizedLongObjectMap at the exact same time (MainWS-ReadThread and MainWS-WriteThread) as seen on the dump, with one waiting to lock the other.
Highlight: https://im-ded-but.mantaro-is.life/90o8563-588.jpg as seen on [here](https://github.com/DV8FromTheWorld/JDA/pull/410#issuecomment-320762473)

{[Thread dump file](https://github.com/DV8FromTheWorld/JDA/files/1205853/deadlock.zip)}
Important output:
```
Found one Java-level deadlock:
=============================
"JDA [33 / 51] MainWS-ReadThread":
  waiting to lock monitor 0x00007fc4640248a8 (object 0x00000001f77083d0, a gnu.trove.impl.sync.TSynchronizedLongObjectMap),
  which is held by "JDA [33 / 51] MainWS-Sending Thread"
"JDA [33 / 51] MainWS-Sending Thread":
  waiting to lock monitor 0x00007fc5b409c778 (object 0x00000001f778b698, a gnu.trove.impl.sync.TSynchronizedLongObjectMap),
  which is held by "JDA [33 / 51] MainWS-ReadThread"
```
 
Important stacktrace data: https://hastebin.com/akazulilih.sql

Status = https://cdn.discordapp.com/attachments/175599601942921216/344188294567034889/unknown.png (Was like this for over 2 minutes until the watcher rebooted it forcefully)

_Running JDA version related to: https://github.com/DV8FromTheWorld/JDA/pull/410 on hash `46802e1` on Minn's request._

Note: Will post more data as I get it.

**Comment by MinnDevelopment** [comment]
Fixed as of 6c7e405
