### ISSUE TITLE
Private Message > RestAction queue returned failure: [ErrorResponseException] 50007

### ISSUE THREAD

**Issue by Alw7SHxD** [DV8FromTheWorld/JDA#434]
`[12:26:10] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user`

whenever sending a private message to a user that has turned off pm's in privacy settings.
is there a way to detect that?

**Comment by MinnDevelopment** [comment]
No, there is not.
You can handle this using the failure consumer which is the second consumer in `queue(Consumer, Consumer)`.

**Comment by Alw7SHxD** [comment]
okay, thank you. now it works.
