### ISSUE TITLE
Catching RestAction queue returned failure: [ErrorResponseException] 50007

### ISSUE THREAD

**Issue by Alw7SHxD** [DV8FromTheWorld/JDA#435]
while trying to send a private message using
```java
user.openPrivateChannel().queue( (channel) -> channel.sendMessage(content).queue() );
```

it'll work fine for users with PM's unlocked for everyone, but with people that has their PM's locked it'll return
```java
[Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
```

so the question is, is there a way to catch that? via `try` and `catch`? 

of course without using the `failure` parameter, which cannot do what i'm trying to achieve.

**Comment by Almighty-Alpaca** [comment]
only if you use `.complete()`. `.queue()` is completely async and thus can't throw exceptions back to the calling thread

**Comment by Alw7SHxD** [comment]
so should i use `.submit()` instead?

**Comment by Alw7SHxD** [comment]
oh okay... https://gyazo.com/95e6d3e7d2fec55846704c2e4eb4987d 
i didn't see the `.` after complete. 😂

**Comment by Almighty-Alpaca** [comment]
np 😄
