### ISSUE TITLE
Throw exception for field larger than MessageEmbed.VALUE_MAX_LENGTH

### ISSUE THREAD

**Issue by NachtRaben** [DV8FromTheWorld/JDA#449]
Spent about an hour trying to figure out why my embeds weren't sending.
The EmbedBuilder doesn't throw an exception when a Field exceeds 1024, not sure if this applies to other embed fields.

**Comment by MinnDevelopment** [comment]
According to this section this is checked unless you specifically disable checking using `new Field(..., ..., ..., false);`
https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java#L543-L548

**Comment by NachtRaben** [comment]
I was using new Field(title, body, inline) when I was running into this, that snippet shows that it should only be checked if checked was specified. Didn't realize it had a 4 arg constructor. Shouldn't the default behavior be to check the length since you go through the hassle of checking URL validity and max overall length on .build()?

**Comment by MinnDevelopment** [comment]
It is the default behaviour as you can see in the other constructor.

**Comment by NachtRaben** [comment]
Just noticed that, I wonder why there wasn't any exceptions being thrown. Odd.

**Comment by NachtRaben** [comment]
https://haste.nachtraben.com/QXw2jcFkOf.cs

The method responsible for generating the embed.
Test command to throw an exception by attempting to send an empty message.
And log output.

**Comment by kantenkugel** [comment]
Well your "Finished adding field." message and all following ones aren't printed so there has to be an exception.

That exception printed in the log is from a different source i guess?

Can you use a debugger and step through? See where the exception bubbles up to. It might get eaten when it reaches the top of a thread without try-catch

**Comment by NachtRaben** [comment]
AppenderBase never throws the exception if the logging event failed, it changes an internal status.
Thanks for pointing that out katenkugel, It was getting eaten.
