### ISSUE TITLE
[Question] Playing a MP3

### ISSUE THREAD

**Issue by StijnSimons** [DV8FromTheWorld/JDA#461]
Is there a good documentation on how to play an mp3?

**Comment by kijube** [comment]
Use the **LavaPlayer** (https://github.com/sedmelluq/lavaplayer)

**Comment by StijnSimons** [comment]
Isnt that for a YT link?

**Comment by kijube** [comment]
Just look at the README file.

**Comment by MinnDevelopment** [comment]
The wiki points you into the right direction, JDA doesn't have any actual sending implementation thus we recommend using lavaplayer as mentioned above.
See: https://github.com/DV8FromTheWorld/JDA/wiki/4)-Making-a-Music-Bot
