### ISSUE TITLE
Possibility to send multiple embeds/files in one Message

### ISSUE THREAD

**Issue by MDWay** [DV8FromTheWorld/JDA#467]
Is it currently possible to send multiple embeds/files in the same Message (and possibly also with some regular text)? I read the current code of the [MessageChannel](https://github.com/DV8FromTheWorld/JDA/blob/1fbf1fcde88d504f47edcb741fc0adc89ac6a4bd/src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java#L358) interface and can't find anything.

**Comment by Sanduhr32** [comment]
Hey MDWay, Discord supports it but JDA doesnt, same for sendFile. Regards Sanduhr

**Comment by MinnDevelopment** [comment]
This is a feature that will be added in a future version of JDA. Currently it is not possible but will be using something called `MessageAction` which will be added in #453

**Comment by Sanduhr32** [comment]
Minn how big is the rewrite? I mean adding another Embed-JSON in the Msg-JSON isnt hard i guess.

**Comment by MinnDevelopment** [comment]
It is not possible to send multiple embeds in normal messages, that is a feature only available to webhooks. Sending multiple files required a change in sending which was easy by adding `MessageAction`.

**Comment by MinnDevelopment** [comment]
Added support for sending multiple files in [v3.4.0](https://github.com/DV8FromTheWorld/JDA/releases/tag/v3.4.0)
