### ISSUE TITLE
Retrieve message content before it's update

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [DV8FromTheWorld/JDA#471]
Is it possible to retrieve the content of a message before it's update ? For example, a message in a MessageUpdateEvent.

**Comment by TheMonitorLizard** [comment]
Your best bet is cache the content of the message.

**Comment by SadiinsoSnowfall** [comment]
hum... ok, but I can't save the content of every messages my bot receive...

**Comment by Kodehawa** [comment]
You don't have to cache all of them. I cache 20k of them and there only are 20k cached messages at any given time, with newer ones replacing the old ones, which is how I think it has to be done, with x amount.

**Comment by SadiinsoSnowfall** [comment]
Ok, thanks for the idea :D

**Comment by MinnDevelopment** [comment]
Since discord does not provide this information and JDA is not keeping a cache of received messages this is not supported.
