### ISSUE TITLE
restartShardById

### ISSUE THREAD

**Issue by duncte123** [DV8FromTheWorld/JDA#472]
https://github.com/DV8FromTheWorld/JDA/blob/e92e0ae3c1c77c8ba181342adecffbe898f03e63/src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java#L748

Maybe it's a good idea to change the name of this method to restartShardById to follow the same name as getShardById.

**Comment by MinnDevelopment** [comment]
The issue tracker is only for master. If you want to comment on PRs or experiments then do so on the respective PR or on discord.

**Comment by Shredder121** [comment]
(This is a GitHub feature, you can select a line and attach that to a new issue)
