### ISSUE TITLE
Add getUserByNickname

### ISSUE THREAD

**Issue by simpleauthority** [DV8FromTheWorld/JDA#475]
My bot needs to be able to find a user by his or her nickname. This does not (as far as I know) exist in JDA. Please add this functionality.

**Comment by duncte123** [comment]
there is Guild#getMembersByNickname

**Comment by kantenkugel** [comment]
Closing Issue as this functionality already exists [link to docs](http://home.dv8tion.net:8080/job/JDA/lastSuccessfulBuild/javadoc/net/dv8tion/jda/core/entities/Guild.html#getMembersByNickname-java.lang.String-boolean-).

**Comment by simpleauthority** [comment]
Thanks. Sorry about that. I'm stupid.

**Comment by MinnDevelopment** [comment]
For these kind of questions please consult the documentation or out discord server.
