### ISSUE TITLE
So... I found this while helping someone with a problem with this method....

### ISSUE THREAD

**Issue by kantenkugel** [DV8FromTheWorld/JDA#476]
https://github.com/DV8FromTheWorld/JDA/blob/7160efdd5f655d32ff315235f6842966932f92c7/src/main/java/net/dv8tion/jda/core/managers/GuildController.java#L144

**Comment by Sanduhr32** [comment]
Uhm Kant, you are Staff, if you cant help yourself something is wrong. I'ld replace the second member with voice channel. Going to PR it.

**Comment by binaryoverload** [comment]
@Sanduhr32 There is a possibility that he is unable to make a PR to fix this. Making issues is also standard procedure so you can keep track on version progress.

**Comment by kantenkugel** [comment]
na... I just posted here for future reference
Just gonna add that change to some other commit and don't mention it

**Comment by binaryoverload** [comment]
👍

**Comment by kantenkugel** [comment]
Its also not urgent enough to do right now. Just add it to the next push of a "proper" commit/change

**Comment by MinnDevelopment** [comment]
Fixed in #440
