### ISSUE TITLE
Can't get TextChannel By ID

### ISSUE THREAD

**Issue by LudwigHornslied** [DV8FromTheWorld/JDA#481]
I tried using both JDA's getTextChannelById and getGuildById both, but it returns null.

**Comment by Fabricio20** [comment]
That means you can't see the channel/guild. You need to be in the guild to be able to fetch it's information(s).

**Comment by Sanduhr32** [comment]
Maybe you didnt copied the right id, so a msg id instead of channel or something like that.

**Comment by LudwigHornslied** [comment]
https://imgur.com/a/9LT7O
Obviously, bot is in the channel right, I checked channel id a bunch of times but I couldn't find problem.

**Comment by Fabricio20** [comment]
Make sure you are using the correct id and that you can see the text channel/voice channel/guild.

If you want further help, you will need to show us your code for this part, for that I then advise moving to JDA's discord.

**Comment by LudwigHornslied** [comment]
`package com.tistory.hornslied.evitaonline.discordbot;

import java.io.File;

import javax.security.auth.login.LoginException;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import com.tistory.hornslied.evitaonline.discordbot.listeners.discord.EventListener;

import net.dv8tion.jda.core.AccountType;
import net.dv8tion.jda.core.JDA;
import net.dv8tion.jda.core.JDABuilder;
import net.dv8tion.jda.core.entities.Game;
import net.dv8tion.jda.core.exceptions.RateLimitedException;

public class EvitaBot extends JavaPlugin //game server plugin {
	private File configFile;
	private FileConfiguration config;
	
	private DiscordManager discordManager;
	
	private JDA jda;
	private String token;
	private String game;
	
	//Work such as main method
	@Override
	public void onEnable() {
		loadConfig();
		buildJDA();
		
		discordManager = new DiscordManager(this, config);
	}
	
	private void loadConfig() {
		configFile = new File(getDataFolder(), "config.yml");
		if(!(configFile.exists())) saveDefaultConfig();
		config = getConfig(); //YAML Config File
		
		token = config.getString("token");
		game = config.getString("game");
	}
	
	private void buildJDA() {
		try {
			jda = new JDABuilder(AccountType.BOT).setToken(token).buildAsync();
		} catch (LoginException e) {
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			e.printStackTrace();
		} catch (RateLimitedException e) {
			e.printStackTrace();
		}
		
		jda.addEventListener(new EventListener());
		jda.getPresence().setGame(Game.of(game));
	}
	
	public JDA getJDA() {
		return jda;
	}
	
	public DiscordManager getDiscordManager() {
		return discordManager;
	}
}
`

`package com.tistory.hornslied.evitaonline.discordbot;

import org.bukkit.configuration.file.FileConfiguration;

import net.dv8tion.jda.core.JDA;
import net.dv8tion.jda.core.entities.TextChannel;

public class DiscordManager {
	private final EvitaBot plugin;
	
	private JDA jda;
	private TextChannel reportChannel;
	private TextChannel chatLogChannel;
	
	public DiscordManager(EvitaBot instance, FileConfiguration config) {
		plugin = instance;
		
		jda = plugin.getJDA();
		reportChannel = jda.getTextChannelById(config.getString("reportchannel")); //get channel ID by YAML config file, it returns null
		chatLogChannel = jda.getTextChannelById(config.getString("chatlogchannel")); //get channel ID by YAML config file, it returns null
	}
	
	public void report(String reporter, String reported, String reason) {
		reportChannel.sendMessage("**" + reporter + "**" + " 님이 **" + reported + "** 님을 신고하셨습니다. 사유: **" + reason + "**").queue(); //error on here
	}
	
	public void sendChatLog(String channel, String nation, String town, String name, String chat) {
		chatLogChannel.sendMessage("[**" + channel + "**]<" + town + nation + name + "> *" + chat + "*").queue(); //error on here
	}
}
`

Here's my code.

**Comment by Fabricio20** [comment]
Looks like a race condition (assuming the channel id is correct), you are building async, which means as soon as you call buildAsync() it returns and then tries to load the channel (DiscordManager), this happens while JDA is still connecting to Discord so JDA doesn't know about the text channel yet.

You can either `buildBlocking()` or wait for a `ReadyEvent` and then get the text channels. (Option 2 is the best imo).

**Comment by LudwigHornslied** [comment]
Thank you for your immediate help! It works fine!
