### ISSUE TITLE
Hacktoberfest 2017 - Looking for contributions

### ISSUE THREAD

**Issue by MinnDevelopment** [DV8FromTheWorld/JDA#486]
It is that time of the year again. From the __1st October__ to the __31st October__ JDA will be open for Pull Requests contributing to the [Hacktoberfest](https://hacktoberfest.digitalocean.com)!
Now before you start going we have some rules for this event in order to avoid spam and bad pull requests.

## Rules

Before you start making changes please view our [CONTRIBUTING.md](https://github.com/DV8FromTheWorld/JDA/tree/master/CONTRIBUTING.md) and our wiki pages for contributing: [Contributing](https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing) & [JDA Structure Guide](https://github.com/DV8FromTheWorld/JDA/wiki/6%29-JDA-Structure-Guide).

- We are not interested in Pull Requests that change a few typos in documentation or symbol names.
- We do not want any Pull Requests that are breaking (renaming of classes, methods, etc.)
- Pull Requests that are obviously split up to farm will not be accepted and marked as invalid (For example changing docs of 2 classes in 2 Pull Requests is not wanted)

> Once you have opened your Pull Requests we might review and request changes. If no response is given we will mark your PR as invalid and close it. Please keep track of our review process.

## What we are looking for

Updates and improvements to the documentation of JDA are always welcome and we are hoping for a lot of contributions in that direction. Code changes are welcome as long
as it is not a breaking change.

Please open all hacktoberfest pull requests with the base of the `hacktoberfest` branch and target that same branch.

- [ ] The documentation of event classes is in need of updates in both method documentation and class-level documentation (excludes all message events such as **MessageReceivedEvent** and similar)
- [ ] Some classes have very brief documentation that can be improved to make the use of it more clear (for instance OrderAction implementations need better class-level docs)
- [ ] Some smaller wrapper classes might need more information on certain features. This may include Presence#setIdle or MessageReaction#getEmote and others.
- [ ] We are planning to rewrite our managers to be used like current RestAction extensions like ChannelAction or similar (this one is really big and a lot of work)
- [x] We need templates for issues and pull requests to improve contributions and issue tracking for the future ( #493 )

### Notes

Before you start making changes please look at already existing Pull Requests and avoid making duplicates. We recommend commenting on this issue about changes that you are currently working on
to inform other contributors about already in-progress changes. You should also look for any comments yourself that might already be claiming what you want to work on.

**Comment by kantenkugel** [comment]
Also: for code changes (additions, functionality changes), please talk to us first. we don't want you to have a lot of work when we wouldn't merge it anyway (because its already in the works/planned or we don't want some particular feature)

**Comment by kantenkugel** [comment]
Oh and don't forget to sign up at the Hacktoberfest website first, if you want your reward

**Comment by MinnDevelopment** [comment]
Thank you for your contributions, we closed this with 7 PRs marked as hacktoberfest PRs.
