### ISSUE TITLE
Received a channel for a guild that isn't a text or voice channel.

### ISSUE THREAD

**Issue by FrostyModz** [DV8FromTheWorld/JDA#491]
https://i.imgur.com/H02txw6.jpg
im using JDA version 3.3.0_260 (So the latest version)

**Comment by kantenkugel** [comment]
**Latest** version is `3.3.1_284` (see Readme)

**Comment by kantenkugel** [comment]
@MinnDevelopment i think we should push a tag + release for 3.3.1

**Comment by MinnDevelopment** [comment]
The latest version is both in the README and every release

![image](https://i.imgur.com/Pc6v9ed.png)

![image](https://i.imgur.com/fJuujnS.png)

We are not making a release for patch bumps.

**Comment by MinnDevelopment** [comment]
Closing as duplicate of #463 and #466
