### ISSUE TITLE
Repositioning voice channels does not work as intended

### ISSUE THREAD

**Issue by Galkon** [DV8FromTheWorld/JDA#497]
Example:

`VoiceChannel new`: the successful callback from `guild.getController().createVoiceChannel`
`VoiceChannel moveBy`: the voice channel to move it near for, retrieved using `new.getGuild().getVoiceChannelsByName("MOVE BY NAME", true).get(0)`
`guild`: retrieved from newest instance `new.getGuild();`

Code I am trying to execute:

`guild.getController().modifyVoiceChannelPositions().selectPosition(new).moveTo(moveBy.getPosition()).queue();`

It doesn't move the channel at all, nothing happens. I am now using this because my previous code also stopped working entirely:

```
Channel channel = event.getGuild().getController().createVoiceChannel(icon + " " + roomType + " " + roomNumber).complete();
ChannelOrderAction action = new ChannelOrderAction(event.getGuild(), ChannelType.VOICE);
Channel startRooms = event.getGuild().getVoiceChannelsByName("MOVE BY NAME", true).get(0);
action.selectPosition(channel).moveTo(startRooms.getPosition()).queue();
```

**Comment by Galkon** [comment]
Forgot to include channels are in different categories... But I don't see any ways of moving a channel into a category.

**Comment by Galkon** [comment]
Thanks to @MinnDevelopment I found out I have to first invoke the setParent(category) method on the channel manager, and then move the channel. Closing issue.

**Comment by DV8FromTheWorld** [comment]
@Galkon Thank you for detailing the answer to this issue when closing it.

**Comment by techied** [comment]
Much appreciated @Galkon
