### ISSUE TITLE
New JDA Version 3.3.1

### ISSUE THREAD

**Issue by FrostyModz** [DV8FromTheWorld/JDA#498]
https://i.imgur.com/ANmaOXB.png

yeaaaa first time using maven. what am i doing wrong?

**Comment by xaanit** [comment]
Not reading the [README](https://github.com/DV8FromTheWorld/JDA#download)

![](https://anna.is-a-good-waifu.com/15734f.png)

**Comment by MinnDevelopment** [comment]
This is not the place to learn maven.
