### ISSUE TITLE
3.3.1 - Can not change log level anymore

### ISSUE THREAD

**Issue by Bleuzen** [DV8FromTheWorld/JDA#501]
Hi, I updated to 3.3.1 and tryed to set the log level with:
```java
SimpleLog.LEVEL = org.slf4j.event.Level.ERROR;
```
But JDA still prints DEBUG messages.

Is there a new way to set the log level?

**Comment by kantenkugel** [comment]
Do you have a SLF4J implementation running? If so, you will have to configure logging there instead of via SimpleLog. The field in SimpleLog is only there to configure the fallback logger and will be removed completely next iteration

**Comment by Bleuzen** [comment]
Yes, I had SLF4J running.

```java
System.out.println("SLF4J: " + SimpleLog.SLF4J_ENABLED);
```
prints `true`

I found a solution. For everyone who has the same problem:

```java
Logger jdaLogger = (Logger) LoggerFactory.getLogger("net.dv8tion.jda");
jdaLogger.setLevel(Level.ERROR);
```

Thanks for the hint @kantenkugel  :D

**Comment by kantenkugel** [comment]
@Bleuzen thats not really the proper solution
You would want to look at the configuration options of your slf4j implementation.

**Comment by Bleuzen** [comment]
@kantenkugel I added logback somewhen, because lavaplayer printed a warning message without. Sorry, I forgot that.

**Comment by kantenkugel** [comment]
yea then you should look at logback's config options https://logback.qos.ch/manual/configuration.html
That way you can customize everything (format, level per class, file loggers,...)
