### ISSUE TITLE
Confusing Javadoc in ListenerAdapter

### ISSUE THREAD

**Issue by Foorack** [DV8FromTheWorld/JDA#505]
"[...] which divides Events for the you."

I suggest removing the word "the" from that sentence to make it more clear.

https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java#L90

**Comment by mhdsmr2** [comment]
I made a pull request, please merge it.

**Comment by kantenkugel** [comment]
@mhdsmr2 and others: Please don't create 1-word PRs. We appreciate you trying to help but especially with docs (not a big issue), we don't need a full commit + PR to fix a single word. Also read through #486

**Comment by mhdsmr2** [comment]
Oh, Okay.
