### ISSUE TITLE
Can't delete own message

### ISSUE THREAD

**Issue by RoccoDev** [DV8FromTheWorld/JDA#508]
`Message toSend = new MessageBuilder().append("aa").build();  
channel.sendMessage(toSend).queue();    
message.delete().complete();      
toSend.delete().queueAfter(5, TimeUnit.SECONDS);`

The last line returns a NPE.
`at net.dv8tion.jda.core.entities.impl.MessageImpl.delete(MessageImpl.java:471)`

**Comment by RoccoDev** [comment]
Message is being sent. If I try to delete it with TextChannel#deleteMessageById it returns a 400 saying "snowflake should be less than or equal to <a big number starting with 9>"

**Comment by MinnDevelopment** [comment]
You can't delete messages from message builder, these messages have no ID assigned and thus cannot be modified or deleted.
You need to use the response message from sendMessage:
```java
channel.sendMessage(toSend).queue( message -> message.delete().queueAfter(5, TimeUnit.SECONDS) );
```

**Comment by RoccoDev** [comment]
Oh, yes, I was wondering what the "-1" in MessageBuilder was for.

**Comment by RasFlor** [comment]
It does now not works

**Comment by WalshyDev** [comment]
Go to discord.gg/0hMr4ce0tIl3SLv5 to receive support

**Comment by 615283** [comment]
@RasFlor what do you mean?

**Comment by MrRJsTha** [comment]
maybe you're bot doesn't have permissions for deleting message
