### ISSUE TITLE
Add emotes to messages

### ISSUE THREAD

**Issue by Kadnium** [DV8FromTheWorld/JDA#513]
How you can add emote of your discord server to bot's message?
I'm trying to do it so it gets all emotes of server and then randomizes one into the message.

**Comment by kantenkugel** [comment]
Just send the result of `Emote#getAsMention()`. You can get a hold of the Emote object via severals getters in `JDA` and `Guild`

**Comment by Kadnium** [comment]
Thanks, got it working.
