### ISSUE TITLE
Json-parse error in GUILD_EMOJIS_UPDATE

### ISSUE THREAD

**Issue by napstr** [DV8FromTheWorld/JDA#514]
https://wastebin.party/ayawedagib.vbs

im not 100% sure whether this is a JDA issue or it's discord just sending wrong things and needs to be shouted at

only one of those in the logs

**Comment by Sanduhr32** [comment]
well if you format the json one emoji name is null thats why the json-parse error appeared.
Second Emoji. I used the [duckduckgo.com tool](https://duckduckgo.com/?q=json+format). ![](https://cdn.discordapp.com/attachments/169484473333710848/367818634615193611/Screenshot_181.png)

**Comment by natanbc** [comment]
https://discordapp.com/developers/docs/resources/emoji#emoji-object The name shouldn't ever be null according to the API

**Comment by Sanduhr32** [comment]
So discord sent a wrong thing or someone made a emoji with that name and JDA became a victim of parsing wrong data.

**Comment by MinnDevelopment** [comment]
@napstr considering this might be a discord bug, the guild_id value is relevant for me.

**Comment by napstr** [comment]
Great, so this was Discord sending wrong stuff after all.
Currently JDA seems to discard the whole chunk of data in such a case. Is this a a deliberate design decision, or is different behavior, like only ignoring the entity that has the wrong data, but parsing all those that are fine, possible to be implemented in the future for slightly better robustness in such cases?

**Comment by MinnDevelopment** [comment]
According to night this has been fixed. 
I currently have no plans of changing this behaviour. If it wasn't such a waste of resources I would even be in favor of closing the connection with an "invalid payload" code here.

**Comment by DV8FromTheWorld** [comment]
Appears this issue has been dealt with.
