### ISSUE TITLE
Add and remove a role, only one works

### ISSUE THREAD

**Issue by M4itreG** [DV8FromTheWorld/JDA#515]
Hello,

I'm really blocked since few day. 
Context : 
A member want validate a newbie. He write $validation @newbie_name and, after verification, I remove "newbie role" then add "Member role".

Here is my method and the problem is identified by comment : 

```java
private void validation_membres(User user, MessageChannel channel, String[] arguments, Guild guild, Member demandeur) {
		String joueurAvalider = "";
		GuildController gc = new GuildController(guild);
		
		for(int i = 0; i < arguments.length; i++) {
			joueurAvalider += arguments[i] + " ";
		}
		Role role_membres = guild.getRolesByName("Membre", true).get(0);
		Role role_newbies = guild.getRolesByName("newbies", true).get(0);		
		
		//if demandeur is member so he can validate a newbie
		if(demandeur.getRoles().contains(role_membres)) {
			//if joueur is a member of serveur
			if(joueurAvalider.startsWith("@")) {
				joueurAvalider = joueurAvalider.replace("@", "");
				Member avalider = guild.getMembersByEffectiveName(joueurAvalider.trim(), false).get(0);
				
				//if joueur is a newbie
				if(avalider.getRoles().contains(role_newbies)) {
					System.out.println("newbies oui");
					//Validation running
					//---------Here is the problem
					gc.removeRolesFromMember(avalider, role_newbies).queue();
					gc.addRolesToMember(avalider, role_membres).queue();
					
					
					if(!avalider.getRoles().contains(role_newbies) && avalider.getRoles().contains(role_membres)) {
						channel.sendMessage(":green_book: Joueur validé !").queue();
					}
				}
				else { //player not a newbie
					channel.sendMessage(":closed_book: Le joueur " + avalider.getEffectiveName() + " n'est pas un " + role_newbies.getName() + ". Il ne peut pas être validé.").queue();
				}
			}
			else { //player unknown on server
				channel.sendMessage(":closed_book: Le joueur à valider doit être tagué. Celà permet de vérifier qu'il est connu du serveur.").queue();
			}
		}
		else { //demandeur not a member
			channel.sendMessage(":closed_book: Uniquement les membres peuvent valider des joueurs.").queue();
		}
	}
```

I have permissions for this because when I do one by one, that works. With this code, role is add but no remove.

I'm lost. This morning, I've found this : [Same problem](https://github.com/DV8FromTheWorld/JDA/issues/33)

But if I do : guild.getManager(). I don't have Add or remove ..

Have you any ideas?
Thank you

**Comment by MinnDevelopment** [comment]
Consult the documentation of [GuildController#addRolesToMember](http://home.dv8tion.net:8080/job/JDA/javadoc/net/dv8tion/jda/core/managers/GuildController.html#addRolesToMember-net.dv8tion.jda.core.entities.Member-net.dv8tion.jda.core.entities.Role...-)

There is a huge warning explaining your issue:

### Warning

**This may not be used together with any other role add/remove/modify methods for the same Member within one event listener cycle! The changes made by this require cache updates which are triggered by lifecycle events which are received later. This may only be called again once the specific Member has been updated by a GuildMemberRoleAddEvent. 
To add _and_ remove Roles from a Member you should use `modifyMemberRoles(Member, Collection, Collection)`**

**Comment by MinnDevelopment** [comment]
The issue you linked is from an old version of JDA (2.x) in which this functionality was different.

**Comment by Sanduhr32** [comment]
he is contructing a GuildController use <b>Guild#getController</b>

**Comment by M4itreG** [comment]
Blocked since 2 days and 1 hour after this post, i found this : 
- removeSingleRoleFromMember
- addSingleRoleFromMember
It's work.

But Thank you @MinnDevelopment, I will try with modifyMemberRoles.
Have a nice day.

**Comment by Sanduhr32** [comment]
Well read my comment again edited it 👀 sorry
