### ISSUE TITLE
Proposal for the ability to configure the websocket gateway URL 

### ISSUE THREAD

**Issue by Frederikam** [DV8FromTheWorld/JDA#519]
When a JDA instance is first connecting to a shard, it will request the gateway URL from the `/gateway` REST endpoint. I intend to rewrite this functionality in such a way that it is possible to override it from the `JDABuilder`, allowing the URL to be replaced.

You might be wondering why anyone would want to do this, as there are currently no available alternatives for the Discord WSS gateway. I am currently working on a project called Dike which behaves as a caching proxy that will keep shards connected even after a Discord library (like JDA) has shutdown. This would potentially allow us to have JDA send OP 2 for hundreds of shards in a very short time without affecting Discord's gateway.

I am opening this issue to discuss these changes and get your approval before writing any code. 

## Proposed changes
* Create the interface `net.dv8tion.jda.core.requests.IGatewayProvider` with a single method:
    * `#getGatewayUrl()` which replaces `WebSocketClient#getGateway()`
* Create the class `net.dv8tion.jda.core.requests.GatewayProviderImpl` which implements the interface as the current JDA behavior. This class would be default.
* Add the method `JDABuilder#setGatewayProvider(IGatewayProvider provider)` which allows replacing the default provider. Would be documented as an advanced feature in the javadoc.

## Additional thoughts
* It might be a good idea to invalidate the cached URL by default if a connection fails. JDA doesn't do this but it is described in the [Discord docs](https://discordapp.com/developers/docs/topics/gateway#get-gateway)
* It might be a good idea to statically cache the URL for all shards, as this is the behaviour that Discord recommends. JDA currently uses a nonstatic field in `WebSocketClient`.

**Comment by adriantodt** [comment]
pinging @natanbc, who is also doing a persistent-gateway https://github.com/natanbc/discord-bot-gateway

**Comment by DV8FromTheWorld** [comment]
I would be open to seeing a PR related to this.

**Comment by MinnDevelopment** [comment]
Added in [3.5.0](https://github.com/DV8FromTheWorld/JDA/releases/tag/v3.5.0)

**Comment by SecretAgent-YT** [comment]
Is this feature still implemented? Not seeing the method in the documentation for the JDABuilder interface...
