### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by xeu100** [DV8FromTheWorld/JDA#525]
When reading the docs, I've tried to find a way of checking Permissions. I would guess that there would be something where you get the user instance and run some sort of method like hasPermission() and using the Permission ENUM... I can't seem to find this, and if someone could point me in the right direction, that would be great.

**Comment by kantenkugel** [comment]
Can you tell me where you searched?
User is just a global user (and therefore can't have permissions). Member is a User inside of a Guild and therefore has permissions for that Guild.
Both Member and Guild have methods to check permissions.
If you would have searched there (or in Guild; Guild points to Member) you would have probably found it.

**Comment by Almighty-Alpaca** [comment]
The [Member](http://home.dv8tion.net:8080/job/JDA/lastSuccessfulBuild/javadoc/net/dv8tion/jda/core/entities/Member.html) class extends [IPermissionHolder](http://home.dv8tion.net:8080/job/JDA/lastSuccessfulBuild/javadoc/net/dv8tion/jda/core/entities/IPermissionHolder.html) which has many methods for permission checking.
