### ISSUE TITLE
SendMessage not working + Creating and sending a private message

### ISSUE THREAD

**Issue by xeu100** [DV8FromTheWorld/JDA#526]
Hi,

I am unable to send a message, however, no errors occur and it knows the name of the channel. I also am unable to figure out how to send a private message.

**Comment by napstr** [comment]
https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction

**Comment by xeu100** [comment]
That solves my message sending issue
However, my private channel issue still exists.

**Comment by MinnDevelopment** [comment]
I have an issue with your issue.
1) You provide no code or any hint to what you actually tried to do
2) You did not read the wiki prior to opening your issue
3) You did not look for other issues
4) You did not join our discord server to ask a very basic question about the lib

The link @napstr provided gives an example on how sending a private message works, not sure how you missed that.
