### ISSUE TITLE
Glitch with tokens

### ISSUE THREAD

**Issue by xeu100** [DV8FromTheWorld/JDA#527]
javax.security.auth.login.LoginException: The provided token is invalid!
	at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:244)
	at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:134)
	at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:541)
	at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:582)
	at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:613)
	at net.loreofcrafters.cloud.Cloud.main(Cloud.java:16)

That is the error I keep getting, however, the token is correct. My code:

package net.loreofcrafters.cloud;

import javax.security.auth.login.LoginException;

import net.dv8tion.jda.core.AccountType;
import net.dv8tion.jda.core.JDA;
import net.dv8tion.jda.core.JDABuilder;
import net.dv8tion.jda.core.exceptions.RateLimitedException;
import net.loreofcrafters.cloud.events.HelpCommand;

public class Cloud {

	public static JDA api;
	
	public static void main(String[] args) {
		try {
			api = new JDABuilder(AccountType.BOT).setToken("REMOVED FOR SECURITY").buildBlocking();
			api.addEventListener(new HelpCommand());
		} catch (LoginException | IllegalArgumentException | InterruptedException | RateLimitedException e) {
			e.printStackTrace();
		}
	}

}

**Comment by kantenkugel** [comment]
Why did you even create this Issue?

**Comment by xeu100** [comment]
I **had** an issue?

**Comment by kantenkugel** [comment]
Well if you **had** an issue that was resolved prior to you creating a issue on GH (this issue was instantly closed), then just don't post it at all

**Comment by kantenkugel** [comment]
This is not a support forum. Try to solve problems yourself first and read our docs before posting stupid questions here. This is meant for bugs, feature requests and at least more complicated questions

**Comment by xeu100** [comment]
It wasn't instantly closed and maybe you don't need to be rude when responding.
