### ISSUE TITLE
Messages not sending

### ISSUE THREAD

**Issue by xeu100** [DV8FromTheWorld/JDA#528]
So, I have created a command parsing/prefix/checking system. Currently, the default prefix is !, however when I edit it, it doesn't send any messages.

Below, are the 2 primary classes. The first class is the actual command and the second is the command system.
https://hastebin.com/mimusamezo.java
https://hastebin.com/bafoqudoze.java

**Comment by kantenkugel** [comment]
For the last time: only post JDA issues here. Not general "I don't know why this is not working. Must be JDA".

If the only thing you changed in code (prefix) is not related to JDA, its not a JDA issue!

Not being good in a programming language is not bad or a shame. But polluting a libraries issue page with problems with your own code that don't even have to do with said lib is just bad.

Seing as you are already in our Guild where we offer coding support, please post there first and confirm if its actually a JDA problem. So far, all 3 of your "Issues" that you posted within the last 3 hours are just on your part.
