### ISSUE TITLE
How give a streaming link

### ISSUE THREAD

**Issue by Ohw222** [DV8FromTheWorld/JDA#536]
How i can set the presence to a streamink link lithe that : 
![capture5](https://user-images.githubusercontent.com/24877481/31940652-37ec92ec-b8bf-11e7-8bc4-cc884fe8db2c.PNG)

**Comment by kantenkugel** [comment]
To add to @WalshyDev comment: Or do it directly through the `JDABuilder` if it is static and predetermined for the bot
