### ISSUE TITLE
getAsMention fails for public role

### ISSUE THREAD

**Issue by EclipsedSolari** [DV8FromTheWorld/JDA#538]
I'm trying to send a message invoking the `@everyone` ping. My code (simplified) is something like this:

    Guild server;
    Role everyone;
    RestAction<Message> sendMessageAction;
    MessageBuilder messageBuilder;
    Message message;

    server = commandChannel.getGuild();
    everyone = server.getPublicRole();

    messageBuilder = new MessageBuilder();
    messageBuilder.append(everyone.getAsMention() + " test");
    message = messageBuilder.build();
    sendMessageAction = channel.sendMessage(message);
    sendMessageAction.complete();

The message comes through the Discord client as `@@everyone test` and does not actually ping `@everyone`. A bit of debug printing shows that a "normal" `@everyone` message looks like this to `message.getRawContent`:

    @everyone test

whereas the failing `@@everyone` message looks like this:

    <@&351278506111401984> test

Even more interesting, simply doing

    messageBuilder.append("@everyone test")

rather than invoking `everyone.getAsMention` properly pings `@everyone`. In addition, manually entering `<@&351278506111401984> test` into the Discord client produces a failing `@@everyone test` message identical to the bot's failure.

I'm not sure exactly what's wrong, or whether it applies to more roles than `@everyone`. Individual user pings via `getAsMention` work correctly. The raw role-ping message appears to match [Discord's requirements for role pings](https://discordapp.com/developers/docs/reference#message-formatting), too. This may actually be a Discord bug?

**Comment by MinnDevelopment** [comment]
The everyone ping is a literal as in `@everyone` just like `@here` they are keywords

**Comment by MinnDevelopment** [comment]
These mentions existed before discord added role mentions

**Comment by EclipsedSolari** [comment]
So I'm meant to use `messageBuilder.append("@everyone test")` rather than `everyone.getAsMention`? If that's the case, please feel free to close this issue. I was under the impression `@everyone` and `@here` were just special context-dependent roles.

**Comment by MinnDevelopment** [comment]
The role is only present to modify permissions

**Comment by EclipsedSolari** [comment]
Understood. Thank you!
