### ISSUE TITLE
Join a guild programmatically?

### ISSUE THREAD

**Issue by Jiggleton** [DV8FromTheWorld/JDA#541]
Sorry if this isn't entirely an "issue" with the API, but I really want to know if this is a feature or even possible. I want to connect to a new guild with a specified invite with a client account. I've been looking all over for methods and or documentation about this idea. Is it even possible within the API? Is there some kind of RestAction for joining a new guild? Thanks in advance!

**Comment by MinnDevelopment** [comment]
It is not allowed to join a guild automatically. Use the official discord features.
JDA does not support forbidden API features.
