### ISSUE TITLE
getRoles() returning Static reference error.

### ISSUE THREAD

**Issue by Squidkingdom** [DV8FromTheWorld/JDA#549]
```java
if (objMsg.getContent().equalsIgnoreCase("!test")) {
	//addSingleRoleToMember​( e.getMember(), )
	objChannel.sendMessage(getRoles().toString());
}
```
}` This is the general code I want to execute to list the roles I have in the Guild. It gives me a Static reference error. I've tried some loops and cant figure it out.

**Comment by MinnDevelopment** [comment]
Where are you even trying to get roles from? Roles are part of guilds and thus not in a static context.

**Comment by Squidkingdom** [comment]
Ive done this in the onMessage() (or whatever the message function is that you are supposed to override) When that gave me an error I tried giving it its own method. That still didn't work.

**Comment by Almighty-Alpaca** [comment]
Can you give us the full code that is involved and describe what exactly it is supposed to do? The piece in your question does literally nothing at all.

**Comment by MinnDevelopment** [comment]
It seems as if your issue is less of an issue with the library and more of an issue with your understanding of the fundamentals of the java language itself.

**Comment by Squidkingdom** [comment]
Not necessarily, I just don't know where `Guild.getRoles` is supposed to be called without getting this error. I know this error and why I'm getting it I just don't know if there is just something in JDA i'm blatantly missing. I have asked Stackoverflow. They just mark me as a duplicate and refer me to something that doesn't work.

**Comment by Sanduhr32** [comment]
Guild is an interface and you have to use a INSTANCE of the interface not the interface ITSELF

**Comment by MinnDevelopment** [comment]
This is pretty clearly an issue with your understanding of basic OOP, the method has to be called on an instance of the "Guild" class.
The direct call without that context is impossible. You do `getRoles()` on nothing which is interpreted as a static reference to a method that has no signature and thus will not compile.

```java
Guild guild; // you have to get this from somewhere, for example an event or channel instance
if (objMsg.getContent().equalsIgnoreCase("!test")) {
	//addSingleRoleToMember​( e.getMember(), )
	objChannel.sendMessage(guild.getRoles().toString());
}
```

Ways of getting a guild can be found in the [documentation](http://home.dv8tion.net:8080/job/JDA/javadoc/) by searching for signatures of "getGuild".

**Comment by MinnDevelopment** [comment]
Considering this has nothing to do with this library I'm closing this issue.

**Comment by Squidkingdom** [comment]
I'm sorry, I completely forgot the bots can be in more than one guild and assumed that Guild automatically returned the guild the bot was in. DERP. Thank you all so much for your help anyway. I can't express my appreciation enough. Making the switch from some other languages and focusing more on syntax than basic programming OOP skills. 
Thank you, squid
