### ISSUE TITLE
Role not being assinged

### ISSUE THREAD

**Issue by Murfity** [DV8FromTheWorld/JDA#551]
Hello, I'm calling `guild.getController().removeRolesFromMember(objMember, guild.getRolesByName("@MUTED", true));
	objChannel.sendMessage("You have been moved to @MUTED").queue();
	` In the `public void onMessageReceived` event that is Overridden. It executes perfectly with no errors and DEBUG tells me that it is running the code and succeeding.  The sendMessage also works. However when I check back in with discord. The role doesn't show up. Im new to this library and could use some help!

Thank you, Murf

**Comment by MinnDevelopment** [comment]
`removeRolesFromMember(...)` returns a RestAction. Refer to the documentation of the RestAction class. 
You have to call either `queue(...)`, `complete(...)` or `submit(...)` to execute it.

**Comment by Murfity** [comment]
OK, I knew I had to do that. It's just 4 am. Here and I'm not in a good state of mind. So sorry for a dumb question but that you for a response!
