### ISSUE TITLE
Read Subs and Followers

### ISSUE THREAD

**Issue by Murfity** [DV8FromTheWorld/JDA#552]
Is there a method to get the names of subscribers on twitch. I know that in the client version it says to connect your twitch account to get rewards for subscribing. Therefore I assume its in the back-end stuff on discord's behalf. I was wondering if JDA had something that handles that.

**Comment by MinnDevelopment** [comment]
Twitch subscribers are managed from an extension. Each subscriber (implied they linked their twitch account to discord) is assigned a designated sub role. 
This role is distinguished by one property from regular roles, the role is managed. To check whether a role is managed you can simply use Role.isManaged() on any role instance.

Keep in mind that other extensions may also manage roles which share this same property and it is not easily distinguishable which is a twitch role and which isn't.
For example the roles for bots are also managed by the bot's application.

**Comment by Murfity** [comment]
A Discord extension?
Do you know where to learn more. I know this isn't in your job description but I don't exactly know what to look for.

**Comment by kantenkugel** [comment]
Twitch subscribers/followers are actually managed by discords backend itself. There is no way of seeing who someone subscribed to (or even what accounts he linked with discord). Only thing you can do is get a role with proper name (Subscriber) that is managed and check for members having that role.
