### ISSUE TITLE
EventListener for a member joining a channel

### ISSUE THREAD

**Issue by DaanvVeen** [DV8FromTheWorld/JDA#554]
[docs]: http://home.dv8tion.net:8080/job/JDA/javadoc/

Hi,

I have a really simple question, hoping one of you guys could help me out!

I was wondering if there is a listener which is called when a server member joins (connects to)  a VoiceChannel. I searched the [documentation][docs], but couldn't find one that fits, since they don't really have a description. 
To make it extra clear, I'm looking for a method which can be Overridden such as the onMessageReceived method. 

Thanks in advance!
Kind regards.

**Comment by MinnDevelopment** [comment]
You want the `GuildVoiceJoinEvent`

**Comment by Almighty-Alpaca** [comment]
All voice releated events are in the [`net.dv8tion.jda.core.events.guild.voice`](http://home.dv8tion.net:8080/job/JDA/javadoc/net/dv8tion/jda/core/events/guild/voice/package-summary.html) package.

**Comment by DaanvVeen** [comment]
Thanks guys! It was the GuildVoiceJoinEvent I was looking for. Don't know how i could not find that in the first place

**Comment by MinnDevelopment** [comment]
There is a reason why the issue template doesn't have a type for "simple question". For questions like these you should join our official discord.
