### ISSUE TITLE
sendMessage in a specific channel

### ISSUE THREAD

**Issue by ThibautCuchet** [DV8FromTheWorld/JDA#561]
Hi, 
I would like to send a message in a specific channel where nobody send message
I try to use jda.getGuildById(id).getTextChannelById(id).sendMessage(message).queue() but I have a NullPointerException.

Can you help me ?

**Comment by natanbc** [comment]
either the bot is not in the guild or the channel doesn't exist

**Comment by MinnDevelopment** [comment]
Please read the issue template.

**Comment by Almighty-Alpaca** [comment]
There are only 2 possible things that can be `null`: The guild or the channel. That means that either that the bot isn't in the guild/the channel doesn't exist or that one of your IDs is invalid.

**Comment by ThibautCuchet** [comment]
I take the id in discord so I think id is right

**Comment by MinnDevelopment** [comment]
Join the discord server for help: [invite](https://discord.gg/0hMr4ce0tIl3SLv5)

**Comment by kantenkugel** [comment]
@Almighty-Alpaca OR... the jda object
