### ISSUE TITLE
Posting message without any event

### ISSUE THREAD

**Issue by Jerem584** [DV8FromTheWorld/JDA#564]
### Issue Type

- [x] Bug Report

### Description

Hey ! i'm trying to send a message but without any event; with jda instance & 2 different class;

But i got a problem; when i'm calling getJda to get simple jda; Ok it connect 1 time; But when i'm getting guild & channel & trying to post message; 

It reconnect 9 times ... Anyone got the solution ?

**Comment by Sanduhr32** [comment]
I thinks its an issue of your internet and not an JDA issue

**Comment by Jerem584** [comment]
Its not my connection; Just i'm calling multiple time jda build blocking... and if i try to use buildblocking out of void; it just say u must throws; but u can't cause you're not in a void

**Comment by Jerem584** [comment]
and i can't just retrieve jda without reconnect

**Comment by Sanduhr32** [comment]
Reuse 1 JDA instance and dont spam JDABuilder#buildBlocking()

**Comment by Jerem584** [comment]
How ?  can you provide example please ?

**Comment by MinnDevelopment** [comment]
This is not the place to learn java.

**Comment by Jerem584** [comment]
Oh my god; I tried all things but don't work

**Comment by Jerem584** [comment]
OMG! thanks for help
