### ISSUE TITLE
addReaction with Emote

### ISSUE THREAD

**Issue by NutellaBoiii** [DV8FromTheWorld/JDA#582]
Hey, i have a problem, i dont know to use Emojis/Emotes. Is there any list with ids?

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
