### ISSUE TITLE
Add role to a user

### ISSUE THREAD

**Issue by liovy** [DV8FromTheWorld/JDA#588]
Hello,

I searched on Google how to add a role by its name. Can you help me?
I tried this:
`event.getGuild().getController().addRolesToMember(event.getMember(), event.getJDA().getRolesByName("MYGROUP", true)).complete();`
But it return me an error. (https://pastebin.com/VmcAix3m)
It's hard for me to understand how to add a role to a member.

P.S.: Sorry for my English

**Comment by WalshyDev** [comment]
`Can't modify a role with higher or equal highest role than yourself!`
Role hierarchy my friend. The highest role on the bot is below the one it is trying to assign.

**Comment by liovy** [comment]
Okay thanks, sorry for this issue. xD

**Comment by kantenkugel** [comment]
@liovy is this resolved then? If so, please close the issue
