### ISSUE TITLE
Issue with guilds

### ISSUE THREAD

**Issue by Kaxyn** [DV8FromTheWorld/JDA#593]
I am using the 'AccountType.CLIENT' mode to automate helpful actions for my account. However, when I join a new guild, the commands I had setup with my locally hosted bot do not work on that guild unless I restart the bot.

**Comment by WalshyDev** [comment]
Well that's an issue with your code but regardless, check this image out: https://media.discordapp.net/attachments/125227483518861312/391571235802447873/unknown.png
