### ISSUE TITLE
Inconsistent errors thrown from JDA#get[blank]ById(String)

### ISSUE THREAD

**Issue by LJNeon** [DV8FromTheWorld/JDA#598]
## General Troubleshooting
- [x] I have checked for similar issues.
- [x] I have updated to the latest JDA version.
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.
## Issue
Inconsistent errors thrown from `JDA#get[blank]ById(String)`
### Issue Type
- [x] Bug Report
- [ ] Feature Request
### Description
`JDA#getCategoryById(String)` throws an `InvalidArgumentException`, but as far as I can tell all the other `JDA#get[blank]ById(String)` methods throw a `NumberFormatException`, which is inconsistent.

**Comment by kantenkugel** [comment]
Did you check other `getXById` methods? would be nice to see all inconsistencies, not just those 2

**Comment by LJNeon** [comment]
I checked all the ones I could remember off the top of my head (`TextChannel`, `VoiceChannel`, `PrivateChannel`, and `Emote`). The docs are down and the alternative docs are blocked (school computer) so couldn't check in more depth than that.

**Comment by MinnDevelopment** [comment]
You can check the source code. This only a docs inconsistency and NumberFormatException is an IllegalArugmentException
