### ISSUE TITLE
[Request]Getting a selected users authenticated applications as an AccountType.BOT

### ISSUE THREAD

**Issue by burpingdog1** [DV8FromTheWorld/JDA#612]
One of my friends wanted a bot for their discord that would check if the new user who joined is currently part of the Steam Group by checking the authenticated steam app(by getting the link) and if they were it would auto assign a role. I tried looking into this and did multiple coding trials which ended to not work(Sorry if this is already a thing and I missed on it)

**Comment by burpingdog1** [comment]
I was told that it wasn't an implemented feature; therefore I posted it here because issues on github are used for requests

**Comment by Sanduhr32** [comment]
This is still a discord *client* feature and not for *bots*.
