### ISSUE TITLE
Can't set name

### ISSUE THREAD

**Issue by Squidkingdom** [DV8FromTheWorld/JDA#624]
I keep trying to call `Application.getManager().setName("");` but I get a static reference error. I'm not very familiar with the LIB and I can't get it answered anywhere else. Thanks, Squid

**Comment by WalshyDev** [comment]
There may be another way for this but from what I can tell you cannot get the ApplicationManager from the Bot itself, it has to be from a Client.
`api.asClient().getApplicationById("").complete().getManager().setName("name");`

Also please note: The github issue tracker is reserved for feature requests and bug reports. Go to discord.gg/0hMr4ce0tIl3SLv5 (JDA Discord) to receive the needed help.

**Comment by Squidkingdom** [comment]
how do I get the Id?

**Comment by WalshyDev** [comment]
For the Application? Should be the bot ID (Unless it's a really old one but that's unlikely). Again though, use the Discord not here ;)

**Comment by Squidkingdom** [comment]
Yep! Already joined
