### ISSUE TITLE
[BUG] NoClassNotFoundException

### ISSUE THREAD

**Issue by TheTARDIS2176** [DV8FromTheWorld/JDA#626]
Having an issue with Discord JDABuilder, when I run the program, it executes the core but throws a ClassNotFoundException with the following error: okhttp3.OkHttpClient$Builder.

Could this issue be resolved? 

Thanks.

**Comment by Sanduhr32** [comment]
Please join the official support guild. Link can be found in the README.md.

Its a common misstake by many users.

**Comment by napstr** [comment]
Use a proper build tool like [this](https://gradle.org/) or [this](https://maven.apache.org/).

**Comment by TheTARDIS2176** [comment]
I know how to compile and create the bots, I've made several of them. This is an issue within the JDA.

It's legitimately this line of code:
`jda = new JDABuilder(AccountType.BOT).setToken(token).buildBlocking();`

**Comment by natanbc** [comment]
You didn't pack your dependencies correctly. A NoClassDefFoundError means a needed class was absent at runtime.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
