### ISSUE TITLE
Add react event

### ISSUE THREAD

**Issue by VitorBlog** [DV8FromTheWorld/JDA#631]
I are trying to use GenericMessageReactionEvent and MessageReactionAddEvent but that give me a error and say to remove @Override note anyone can help?

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
