### ISSUE TITLE
When someone ban an other user, how to get the name of the guy who banned the banned user? 

### ISSUE THREAD

**Issue by SwannL** [DV8FromTheWorld/JDA#638]
Hello,

When I check GuildBanEvent, I can only find getUser() which return the banned user. But I can't find a way to get the name of the guy who banned him. It is not in Ban object (only username and reason). It is not in GuildBanEvent (or I did not find it...)

Does someone know how to do? 

Thanks for reading.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
