### ISSUE TITLE
Get all messages from member in specific channel

### ISSUE THREAD

**Issue by yKsenomorf** [DV8FromTheWorld/JDA#642]
Hello. I want to get all messages from provided member (or user) in specific channel. However, Guild, nor MessageChannel hasn't got a method called "getMessages()" or "getMessagesFromUser()".

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
