### ISSUE TITLE
com.android.builder.dexing.DexArchiveBuilderException

### ISSUE THREAD

**Issue by gocrafterlp** [DV8FromTheWorld/JDA#649]
com.android.builder.dexing.DexArchiveBuilderException on Android

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

This Gradle exception occurs when trying to build app with JDA

**Comment by natanbc** [comment]
https://developer.android.com/studio/write/java8-support.html

**Comment by gocrafterlp** [comment]
@natanbc thank you
