### ISSUE TITLE
Not receiving any voice until you play any sound first

### ISSUE THREAD

**Issue by DarkSupremo** [DV8FromTheWorld/JDA#653]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the 3.5.1_339.
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Discord Bug

### Description

Already reported it on discord, posting here just to track the issue..

I'm having an strange behavior with the `handleCombinedAudio`, i added an very simple implementation, like this one: #429
It was working fine day 20,It's entering the `handleCombinedAudio` just fine every 20ms, but it's not returning the user that is speaking (`combinedAudio.getUsers()` always return empty) and `combinedAudio.getAudioData(1.0)` just return 0's... i see that in trace log it print as expected:

```
[JDA AudioWS-ReadThread (guildId: 425482112074907666)] TRACE net.dv8tion.jda.core.audio.AudioWebSocket - -> USER_SPEAKING_UPDATE {"op":5,"d":{"speaking":true,"user_id":"189899612675375104","ssrc":1}}

[JDA AudioWS-ReadThread (guildId: 425482112074907666)] TRACE net.dv8tion.jda.core.audio.AudioWebSocket - -> USER_SPEAKING_UPDATE {"op":5,"d":{"speaking":false,"user_id":"189899612675375104","ssrc":1}}
```

Doing some tests, i saw that if i send any audio first after joining the voice channel, it start to work and i receive audios fine.

**Comment by jvtrigueros** [comment]
I can confirm, the way I have been getting around this is by saturating the voice channel with silence:
```kotlin
class SilenceAudioSendHandler: AudioSendHandler {
  var canProvide = true

  override fun provide20MsAudio(): ByteArray {
    val silence = arrayOf(0xF8.toByte(), 0xFF.toByte(), 0xFE.toByte())
    return silence.toByteArray()
  }

  override fun canProvide(): Boolean {
    return canProvide
  }

  override fun isOpus(): Boolean {
    return true
  }
}
```

**Comment by DarkSupremo** [comment]
@jvtrigueros i don't know if that will impact performance somehow, but sending it for just an few seconds when you join in an voice channel is enough to keep it working, like this:

`package tech.gdragon.discord.audio

import net.dv8tion.jda.core.audio.AudioSendHandler
import java.util.*

class SilenceAudioSendHandler: AudioSendHandler {
    var canProvide = true
    var startTime = Date().time

    override fun provide20MsAudio(): ByteArray {

        // send the silence only for 5 seconds
        if (((Date().time - startTime) / 1000) > 5) {
            canProvide = false
        }

        val silence = arrayOf(0xF8.toByte(), 0xFF.toByte(), 0xFE.toByte())
        return silence.toByteArray()
    }

    override fun canProvide(): Boolean {
        return canProvide
    }

    override fun isOpus(): Boolean {
        return true
    }
}`

**Comment by jvtrigueros** [comment]
Good idea! I thought I had to be consistently submitting audio. I’ll give that snippet a shot.

**Comment by Sanduhr32** [comment]
I was having the same issue and didnt try that yet. Thank you for the solution. I will inform everyone who asked me for help ^^.

**Comment by wdavies973** [comment]
Anyone have a Java implementation of this solution?
