### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by 0xSigmoid** [DV8FromTheWorld/JDA#673]
...

**Comment by WalshyDev** [comment]
Guild#getMemberById
The docs are very helpful you know. http://home.dv8tion.net:8080/job/JDA/javadoc/net/dv8tion/jda/core/entities/Guild.html

Either way, the issue tracker isn't for support please join the Discord server for that
Invite: https://discordapp.com/invite/0hMr4ce0tIl3SLv5
