### ISSUE TITLE
[Question] Adding role for streamers

### ISSUE THREAD

**Issue by 99jopety** [DV8FromTheWorld/JDA#677]
Hi im trying to give a person a role name Now Live, when they are streaming, and then remove it when they no longer stream (through twitch)
.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
