### ISSUE TITLE
java.lang.NoClassDefFoundError: net/dv8tion/jda/core/JDABuilder

### ISSUE THREAD

**Issue by LoYungSum** [DV8FromTheWorld/JDA#679]
Error: https://hastebin.com/ciwakoqaju.vbs
pom.xml: https://hastebin.com/gayudegire.xml
Project structure: https://imgur.com/a/EOUEUuH

I'm new to Maven so please teach me

**Comment by MinnDevelopment** [comment]
This is not the place to learn maven.

**Comment by ArsenArsen** [comment]
Here's a hint: build a fatjar. Google for how. But I agree with @MinnDevelopment, this is not a JDA related issue so it's not fit for this place. There are many other places made specifically for this purpose.
