### ISSUE TITLE
Manual or automatic OnlineStatus change?

### ISSUE THREAD

**Issue by koflin** [DV8FromTheWorld/JDA#695]
This is a feature request. Would it be possible for you guys to determine if a user changed his online status by himself or if it got changed automatically to idle.

**Comment by kantenkugel** [comment]
Not possible afaik. Would have been easier if you just asked in the server tbh.

**Comment by kantenkugel** [comment]
For reference, this is all we get: https://discordapp.com/developers/docs/topics/gateway#presence-update
