### ISSUE TITLE
Roles of members not changing

### ISSUE THREAD

**Issue by QuartzMiner6000** [DV8FromTheWorld/JDA#698]
The roles of members are for some reason not changing.
This is the code:
`((ArrayList<Member>)members).get(first).getGuild().getController().modifyMemberRoles(((ArrayList<Member>) members).get(first), collection1, collection2);
((ArrayList<Member>)members).get(second).getGuild().getController().modifyMemberRoles(((ArrayList<Member>) members).get(second), collection1, collection2);`

**Comment by QuartzMiner6000** [comment]
The roles of members are for some reason not changing.
This is the code:
`((ArrayList<Member>)members).get(first).getGuild().getController().modifyMemberRoles(((ArrayList<Member>) members).get(first), collection1, collection2);
((ArrayList<Member>)members).get(second).getGuild().getController().modifyMemberRoles(((ArrayList<Member>) members).get(second), collection1, collection2);`

**Comment by Chaotic-Doom** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to discord.gg/0hMr4ce0tIl3SLv5 to receive the needed help.

**Comment by MinnDevelopment** [comment]
@QuartzMiner6000 You forgot to execute the RestAction. See [Using RestAction](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction).

**Comment by QuartzMiner6000** [comment]
Thank you @MinnDevelopment!
