### ISSUE TITLE
Issue with messages

### ISSUE THREAD

**Issue by WattMann** [DV8FromTheWorld/JDA#701]
So, when my bot send a message (Embed, Normal message) message: "Už si verifikovaný!" it looks like this: "UĹľ si verifikovanĂ˝!"

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
