### ISSUE TITLE
Sending embed messages are delayed

### ISSUE THREAD

**Issue by KodingKing1** [DV8FromTheWorld/JDA#702]
### Bug Report

So I intend on publishing a Discord bot and love using JDA, however I have noticed recently that sending embeds usually take 3-4 seconds to send with gigabit Ethernet on my server, and normal messages send instantly. If this is out of your control then all good, I was just wondering if this is normal and/or if anybody else is experiencing this issue.
By the way I am using queue to send embeds/messages.

**Comment by TBNRShadowDev** [comment]
If something is slow and JDA hasn't been changed recently then it's very likely a Discord back-end update or your client-side problem.
Personally I haven't been experiencing Embed Message delays, and I'm using .queue() as well.

**Comment by KodingKing1** [comment]
Thanks for the fast reply, I have been testing this on my local machine and it is getting fasted message sending speeds with basic messages than my gigabit VPS has been getting using embeds. At first I assumed it was a database issue, but did some debugging and found that the database retrieves data instantly.

**Comment by MinnDevelopment** [comment]
This is a discord issue.

**Comment by KodingKing1** [comment]
Thank you for the responses.

**Comment by jagrosh** [comment]
In the future, please use the issue template.

That aside, this is a normal delay if the Discord guild has the Explicit Content Filter turned on (in a manner that affects the bot) or if the user receiving the embed in Direct Messages has Safe Direct Messaging enabled.

**Comment by KodingKing1** [comment]
Ok, thank you all. I tried to use the issue template, sorry it wasn't great lol.
