### ISSUE TITLE
Typo in GuildLeaveEvent javadoc

### ISSUE THREAD

**Issue by LXGaming** [DV8FromTheWorld/JDA#707]
## Issue
https://github.com/DV8FromTheWorld/JDA/blob/3092875bd5fd1eec10f4973a34a13ab6b4170c6e/src/main/java/net/dv8tion/jda/core/events/guild/GuildLeaveEvent.java#L24

### Issue Type

- [ ] Bug Report
- [ ] Feature Request

### Description

`Cane bse used to detect when you leave a Guild.` -> `Can be used to detect when you leave a Guild.`

**Comment by MinnDevelopment** [comment]
A typo is not a bug, you can PR a fix however.
