### ISSUE TITLE
There was an error in the WebSocket connection

### ISSUE THREAD

**Issue by EspriitYT** [DV8FromTheWorld/JDA#716]
02:38:33 web.1   |  java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.updateTraces(WebSocketClient.java:160)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:940)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
02:38:33 web.1   |      at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
02:38:33 web.1   |  [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - There was an error in the WebSocket connection
02:38:33 web.1   |  java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.updateTraces(WebSocketClient.java:160)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1034)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
02:38:33 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
02:38:33 web.1   |      at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
02:38:34 web.1   |      at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
02:38:34 web.1   |  [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - There was an error in the WebSocket connection
02:38:34 web.1   |  java.lang.NoSuchMethodError: org.json.JSONArray.spliterator()Ljava/util/Spliterator;
02:38:34 web.1   |      at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:182)
02:38:34 web.1   |      at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:39)
02:38:34 web.1   |      at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
02:38:34 web.1   |      at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
02:38:34 web.1   |  [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - There was an error in the WebSocket connection
02:38:34 web.1   |  java.lang.NoSuchMethodError: org.json.JSONArray.spliterator()Ljava/util/Spliterator;
02:38:34 web.1   |      at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:182)
02:38:34 web.1   |      at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:39)
02:38:34 web.1   |      at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
02:38:34 web.1   |      at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
02:38:34 web.1   |      at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
02:38:34 web.1   |      at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by EspriitYT** [comment]
Resolved 

Some Dependencies is not supported by JDA

like httpclient, json, httpasyncclient and httpmime

http://prntscr.com/k7afs3

**Comment by Sanduhr32** [comment]
The 2014 version of org.jsonis slightly outdated and does not have methods JDA requires. You can patch this by updating your org.json dependency to at least the latest 2017 version afaik.

Did you know that the github issue tracker is reserved for bugs reports and feature request? I bet you did not!
Next time just ask in the support guild, which is linked in the readme of this repository.

**Comment by kantenkugel** [comment]
Technically this was a bug report, but this exact issue is in our FAQ and already avail as other issues, so a search should've revealed the solution

**Comment by Sanduhr32** [comment]
Somehow i still do not understand how so many Maven users have this issue while i just met 1 or max 2 guys with this issue using Gradle. Kant feel free to spam my DM on discord xD

**Comment by MinnDevelopment** [comment]
The very first time this was reported was on gradle and I can remember many others using gradle that had this problem

**Comment by Wqrld** [comment]
How would i fix this on Gradle?
