### ISSUE TITLE
DefaultAudioSendSystem not sending audio on 3.7.0

### ISSUE THREAD

**Issue by expert700** [DV8FromTheWorld/JDA#717]
## General Troubleshooting
  
- [X] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [X] Bug Report
- [ ] Feature Request

### Description

Just as the title says, voice is silently broken in 3.6.0_378 and up. Both my own bot and the lavaplayer demo bot are otherwise working and do not show any errors, yet there is no sound being sent through Discord.

**Comment by MinnDevelopment** [comment]
Please update your version. We are currently on 3.7.0_382.

**Comment by expert700** [comment]
I am using 3.7.0_382. I went back and observed that 3.6.0_378 is the update that broke it.

**Comment by MinnDevelopment** [comment]
Please be more specific about what your issue is, rather than "it doesn't work".

**Comment by MinnDevelopment** [comment]
Ok I think I know your problem, I will investigate further when I have more time. In the meantime try using [jda-nas](https://github.com/sedmelluq/jda-nas).

**Comment by expert700** [comment]
Oh, well thanks for the quick help. It's not actually a pressing problem, I can remain on 377 for the foreseeable future. I just noticed a problem and wanted to report it. 

If it helps at all I just tried running both my bot and the lavaplayer demo bot on a raspberry pi running the latest raspbian and java 9 with the same results.

**Comment by MinnDevelopment** [comment]
Is the problem resolved on build `3.7.0_384`?

**Comment by expert700** [comment]
As far as I can tell everything is working on 3.7.0_384. Thanks for the quick fix!
