### ISSUE TITLE
Token is invalid...

### ISSUE THREAD

**Issue by Azrod245** [DV8FromTheWorld/JDA#765]
I started to make a bot but when i try to lunch it says this:

```
javax.security.auth.login.LoginException: The provided token is invalid!
	at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:276)
	at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:214)
	at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:161)
	at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:608)
	at BotDiscord.BotDiscord.main(BotDiscord.java:24)
```

and my code:

```java
public class BotDiscord 
{
	
	public static void main(String[] args)
	{
		
		try {
			JDA jda = new JDABuilder(AccountType.BOT).setToken("RDNIZYZXs1vfz5-eG2LQu73QjHP6pqH0").buildAsync();
			System.out.println("Bot ok!");
		} catch (LoginException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}
```

I have the last version of JDA and i tried a multiple token by https://discordapp.com/developers/applications/ 

I tried to solve the problem for hours and i didn't found the solution...
I also saw a same Issues but i did'nt found the solution in it....
Thanks for help.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
