### ISSUE TITLE
The bot does not receive private messages.

### ISSUE THREAD

**Issue by ImagePrototype** [DV8FromTheWorld/JDA#775]
The bot does not receive private messages.
https://pastebin.com/3rafmR72

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
