### ISSUE TITLE
Methods for sending a non event triggered message

### ISSUE THREAD

**Issue by Niall7459** [DV8FromTheWorld/JDA#787]
Hi I’ve had a look around the API and can’t seem to find a way to send a message to a channel. The only way I can do this is responding on an event.

In this instance I would like to send a message at certain times, when desired, but there is no function (I’m aware of) to obtain a Channel object to #sendMessage

Such code may look like

Channel channel = server.getChannelByName(“general”)
channel.sendMessage()

The current way we have to do is this
Channel channel = event.getChannel()

Is there a way to get the channel object and send a message without need for the Event object? 

Thanks!

**Comment by Artuto** [comment]
To send a Message you must have **Message** Channel instance

**Comment by Niall7459** [comment]
My bad, this is what I meant, is there anyway to get a MessageChannel instance independently (without an Event). Or would I have to get the user to execute a command and then store that MessageChannel in a variable?

**Comment by Sanduhr32** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to discord.gg/0hMr4ce0tIl3SLv5 to receive the needed help.

**Comment by Niall7459** [comment]
Marked as solved.

**Comment by DV8FromTheWorld** [comment]
For reference, you can get a MessageChannel instance (TextChannel, PrivateChannel, or Group) from any of the following

Given a JDA instance..

```
JDA jda = ...

jda.getTextChannelById(...)
jda.getPrivateChannelById(...)
jda.getUserById(...).getPrivateChannel()
jda.getGuildById(...).getTextChannelById(...)
jda.getGuildById(...).getTextChannels()
jda.getGuildById(...).getMemberById(...).getUser().getPrivateChannel()

//For Clients
jda.asClient().getGroupById(...)
```

**Comment by Niall7459** [comment]
This probably sounds stupid but, what is the correct way to get a JDA instance?

**Comment by Sanduhr32** [comment]
You store it or grab it from an event. You should never store any JDA entity. Messages are fine as an exception, everything else should be stored as longs with the matching id.

**Comment by kantenkugel** [comment]
As appendix to @Sanduhr32 's comment: JDA itself is fine to be stored (even tho its technically an entity as well)
