### ISSUE TITLE
Example 2 does not work - MessageChannel.getName() does not exist

### ISSUE THREAD

**Issue by fwyrl** [DV8FromTheWorld/JDA#79]
The second example does not work - the getName() call in event.getChannel().getName() does not work.

I think this is potentially related to the fact that although the Channel interface has a getName(), the MessageChannel interface, which getChannel() returns, does not.

event.getTextChannel().getName() works, but I don't think it would work in a private chat, as that's a separate interface.

Minor issue, but I felt that I should mention it, since it's on the front page of the API, essentially.

**Comment by Almighty-Alpaca** [comment]
You're totally right, it has to be `event.getTextChannel().getName()`. 
`getChannel() ` used to return a `TextChannel` before `MessageChannel`s were implemented, but that was months ago. That it doesn't work in `PrivateChannel`s isn't a problem cause the `TextChannelUpdate...Event`s will only be called for `TextChannel`s  and not for `PrivateChannel`s

**Comment by DV8FromTheWorld** [comment]
Which class specifically are you talking about?

**Comment by Almighty-Alpaca** [comment]
The second one in the README.md file on the front page

**Comment by DV8FromTheWorld** [comment]
Ah, Okay.

**Comment by MinnDevelopment** [comment]
I think you could make `PrivateChannel#getName()` as a shortcut to `PrivateChannel#getUser().getUsername()` anyway

**Comment by DV8FromTheWorld** [comment]
This has been fixed as of: 637a984f84751b28a475aaf8f6cbc2d0b27b4410
