### ISSUE TITLE
JDA instance

### ISSUE THREAD

**Issue by VoltexYT** [DV8FromTheWorld/JDA#790]
How to get JDA Instance?

I need to send a message to a channel without event.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
