### ISSUE TITLE
Hacktoberfest 2018

### ISSUE THREAD

**Issue by MinnDevelopment** [DV8FromTheWorld/JDA#792]
We will be participating in the annual hacktoberfest once again this year. For the special purpose of this we created a branch based on `development` specifically for minor detail changes that can be accumulated into a single build. All hacktoberfest pull requests should be based on and targeted towards the `hacktoberfest` branch.

What qualifies as hacktoberfest pull request?

- Documentation changes
- Minor logic changes
- Minor new features (such as single method additions)
- README changes of any kind
- GitHub file changes

What we don't want to see

- If you fix a typo that is fine, but don't make 5 PRs each fixing a single typo
- Code style changes
- Breaking changes

[Hacktoberfest Details](https://hacktoberfest.digitalocean.com/details)

If your change is one of the listed cases then please use the opportunity of this event for your pull request. We recommend commenting on this issue if you start working on a change in order to avoid multiple users working on the same thing.

Once the hacktoberfest concludes we will be making a new release with the changes.

Happy contributing from the JDA team!

**Comment by sank20** [comment]
Hi, I'd like to start with some easy issues to fix. Is there any list of issues or suggestions that I can refer to?

**Comment by Devoxin** [comment]
[https://github.com/DV8FromTheWorld/JDA/issues](List of issues), any with level `novice` I'd imagine

**Comment by BenjaminUrquhart** [comment]
I'm going to add `JDA#getUsersByPrefix` and `ShardManager#getUsersByPrefix` methods to get users whose usernames start with a given string.
