### ISSUE TITLE
screen sharing of sites like YouTube.

### ISSUE THREAD

**Issue by Draww** [DV8FromTheWorld/JDA#797]
## Issue
In recent updates, a feature has been added in servers to users to share screen. I think this feature can be used for screen sharing. sites like YouTube

### Issue Type

- [ ] Bug Report
- [x] Feature Request

**Comment by MinnDevelopment** [comment]
We only implement official features of the API, this has not been published or announced through any of our channels.

**Comment by natanbc** [comment]
![image](https://user-images.githubusercontent.com/22461307/46772172-03dd5900-cccd-11e8-8b0e-c3e359005685.png)

**Comment by MinnDevelopment** [comment]
Thank you for the update. If this is not supported for bots we will not be implementing it in JDA either.
