### ISSUE TITLE
Has a user blocked my bot?

### ISSUE THREAD

**Issue by BalintGergely** [DV8FromTheWorld/JDA#807]
Is there a way to check if my bot is blocked by a user?

I am trying to write a basic command based chat bot on my friend's server. The bot might DM the members in response to certain commands they write in normal chat channels. We want to give our members the option to disable this feature by blocking the bot. (So that the bot ignores their messages completely.) Now the next two questions might be one and the same...

- Is there a way to check if a call to `User.openPrivateChannel().complete()` would succeed before performing the operation?

- Is there a way to check if the bot was blocked by a specific user? Relationships are `JDA.asClient()` only.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
