### ISSUE TITLE
try catch error

### ISSUE THREAD

**Issue by TheMajster** [DV8FromTheWorld/JDA#829]
[ForkJoinPool.commonPool-worker-1] ERROR net.dv8tion.jda.core.requests.RestAction - RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message

`     try{
                            textChannel.addReactionById(messageID, em).queue()
                        }catch (ex:IllegalArgumentException){
                            println(3333333)

                        } catch (ex:ErrorResponseException){
                            println(22222222222222)
             
                        }`

Exception dont work

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
