### ISSUE TITLE
Sign In, Sign Up

### ISSUE THREAD

**Issue by applke** [DV8FromTheWorld/JDA#847]
Hi! Is it possible to signIn or SignUp by using api?

**Comment by napstr** [comment]
No.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
