### ISSUE TITLE
Missing Permission bit

### ISSUE THREAD

**Issue by austinv11** [DV8FromTheWorld/JDA#92]
I was taking a look at your source for `Permission` as I was having a weird issue with the position of permissions in my library and it seems that you are missing the `Use External Emojis` bit which is at position 18.

**Comment by Almighty-Alpaca** [comment]
You are totally right, we are missing that permission. That's probably because it hasn't been announced in the api-changes channel nor was it added to the official discord docs yet.

**Comment by Almighty-Alpaca** [comment]
Added in 15c327c275cff4a4e40b4755512421e98a67a43c
