### ISSUE TITLE
setNickname

### ISSUE THREAD

**Issue by Taliraz** [DV8FromTheWorld/JDA#925]
Hello,
I don't undertand what i'm doing wrong with the function but it doesn't work

```java
@Command(name="change")
	private void change(Guild guild,GuildController controller,MessageChannel channel,User user,String[]args) {
		channel.sendMessage(user.toString()).complete();
		Member member=guild.getMember(user);
		channel.sendMessage(member.toString()).complete();
		channel.sendMessage(controller.toString()).complete();
		controller.setNickname(member,"test").complete();
	}
```

**Comment by Sanduhr32** [comment]
The github issue tracker is reserved for feature requests and bug reports. Please join the discord guild from the README.md

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
