### ISSUE TITLE
Error on updating Bot's Icon

### ISSUE THREAD

**Issue by fwyrl** [DV8FromTheWorld/JDA#94]
While using 2.2.0_334, I updated the bot's icon, and found this in console. It doesn't seem major, but it does say to report it!

[22:21:40] [Warning] [JDASocket]: Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["verified"] not found.
	USER_UPDATE -> {"bot":true,"id":"[REDACTED]","avatar":"[REDACTED]","username":"[REDACTED]","discriminator":"6748"}

Note, I've removed the bot's id, avatar, and username because I don't know how dangerous each code is.

**Comment by DV8FromTheWorld** [comment]
I'll mark this on our todo list.

**Comment by Xetanai** [comment]
Tested myself and didn't get any error in build 345.
My code:
```
public static void main(String[] args) {
		JDA jda = null;
		try {
			jda = new JDABuilder().setBotToken([REDACTED]).buildBlocking();
			
			jda.getAccountManager().setAvatar(AvatarUtil.getAvatar(new File("E:/Photos/Other/Assets/Avatars/RubixDev_new.png")))
			    .update();
		} catch (LoginException | IllegalArgumentException | InterruptedException | UnsupportedEncodingException ignored) {}
	}

**Comment by DV8FromTheWorld** [comment]
Yep. I also just double checked this. It doesn't happen anymore.

Considering this is from 15 days ago, that was around the time that Discord rolled out some changes to OAuth and 2FA systems. Most likely they had a hickup and didn't send us all of the info.

This shouldn't happen anymore, so I'm going to close the issue. Feel free to reopen if you get the error again.
