### ISSUE TITLE
How to join to guild with invite code

### ISSUE THREAD

**Issue by t0rasan20131** [DV8FromTheWorld/JDA#945]
How to join to guild with invite code

**Comment by natanbc** [comment]
Bots can't use invites. They must be added to guilds with oauth2 by someone with the Manage Server permission.

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
