### ISSUE TITLE
Activity methods not accessable

### ISSUE THREAD

**Issue by XenoPyax** [DV8FromTheWorld/JDA#953]
![grafik](https://user-images.githubusercontent.com/44356373/53889937-91786700-4027-11e9-9384-52388738d927.png)

**Comment by DRSchlaubi** [comment]
What JDK and JDA version are you using?

**Comment by DV8FromTheWorld** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to discord.gg/0hMr4ce0tIl3SLv5 to receive the needed help.
