### ISSUE TITLE
Creating a role with no permissions then moving it causes it to gain two permissions

### ISSUE THREAD

**Issue by Mikusch** [DV8FromTheWorld/JDA#963]
### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

As the title says, creating a role and then moving it using the `GuildController` changes it's permissions.

Example code:
```
var controller = event.getGuild().getController();
Role role = controller.createRole()
        .setName("My awesome role")
        .setPermissions(0L)
        .complete();
controller.modifyRolePositions().selectPosition(role).moveTo(1).queue();
event.getChannel().sendMessage("New role with permissions " + role.getPermissionsRaw() + " was moved to position " + role.getPositionRaw()).queue();
```
Output: `New role with permissions 0 was moved to position 1`

As expected. However, fetching the role again using `Guild#getRoleById(long)` reveals that it now has two permissions: `MESSAGE_EXT_EMOJI` and `MESSAGE_ADD_REACTION`. The Discord client shows this as well. Somehow, moving the role caused it to gain two permissions. This behaviour is consistent and can be replicated. Deleting the line of code that moves the role will leave the role with no permissions, as intended.

A role that already existed before JDA logged in does not seem to have this behaviour.

I have tested moving the role in the `.queue()` callback as well. I've also tried putting a `Thread.sleep(5000)` after creating the role and before attempting to move it. Both of these tests have had the same result.

Tested on `4.ALPHA.0_58` but this issue goes back to at least June 2018. I apologize if this is known or a non-issue.

**Comment by MinnDevelopment** [comment]
This also happens in the official discord client so its safe to say this is a discord issue.

**Comment by MinnDevelopment** [comment]
I recommend moving this issue to the [discord-api-docs](https://github.com/discordapp/discord-api-docs) as its not directly related to JDA.

**Comment by DV8FromTheWorld** [comment]
`modifyRolePositions` is based on the Cache.
The cache is only updated when it receives a dispatch over the websocket to create the role.
In all of your testing scenarios (complete, thread.sleep, queue), the cache hasn't been updated yet.

What happens if you move the role after you receive the RoleCreatedEvent?

**Comment by Mikusch** [comment]
Just wrote a small test that moves the role when a `RoleCreateEvent` is fired - same results. Contains no permissions when you inspect it immediately after moving, then `MESSAGE_EXT_EMOJI` and `MESSAGE_ADD_REACTION` when you fetch it again.

**Comment by MinnDevelopment** [comment]
This has nothing to do with cache, its a discord bug.
