### ISSUE TITLE
Have Channel Overrides Return Null Instead of Throwing NullPointerException

### ISSUE THREAD

**Issue by Techno3600** [DV8FromTheWorld/JDA#985]
Hey, this is just a quick suggestion. Often I find it hard to code when everything I'm trying to work with throws a NullPointerException. I wish the stuff in channel overrides would instead return null so the api itself is easier to work with. Let me know if this is possible.

**Comment by MinnDevelopment** [comment]
You completely ignored the issue template and your description is too vague to understand. I have no idea what you are talking about when all you use to describe your issue is "stuff in X throws Y". Providing a stack trace and related code would make the issue usable.

**Comment by MinnDevelopment** [comment]
Since this is neither a bug report nor a feature request I advice you to ask for support in our discord server instead. [Invite](https://discord.gg/0hMr4ce0tIl3SLv5)

If you disagree, feel free to open a proper issue with enough information to interpret as a bug report or feature request.
